// 数字图像处理题库（练习题 + 复习大纲）
const questionsDip = [
    {id: 1, type: 'single', question: "采集数字图像过程里，采样操作的准确含义是（）", options: ["把连续的空间坐标离散成一个个像素点", "把连续变化的亮度灰度值划分成有限等级", "用来控制图像能区分多少种明暗灰度", "决定图像每个像素存储需要多少比特"], answer: "A", answerText: "A"},
    {id: 2, type: 'judge', question: "HSV 彩色模型由青、品红、黄三种颜色组成。", options: [], answer: "错误", answerText: "错误"},
    {id: 3, type: 'judge', question: "人类视网膜上有两类光感受器:锥状体和杆状体,其中杆状体负责完成昼视觉。", options: [], answer: "错误", answerText: "错误"},
    {id: 4, type: 'single', question: "关于人类视网膜光感受器的功能,以下说法正确的是（）", options: ["锥状体负责夜视觉,杆状体负责昼视觉", "锥状体对颜色敏感,杆状体对弱光敏感", "杆状体在中央凹分布密集,主导高分辨率视觉", "两类细胞均能同时处理颜色和弱光信号"], answer: "B", answerText: "B"},
    {id: 5, type: 'single', question: "线性灰度变换公式 g(x,y)=a* f(x,y)+c，当放大系数 a>1、偏移量 c<0 时，变换效果为（）", options: ["整体画面提亮，明暗对比度缩小", "整体画面压暗，明暗对比度扩大", "整体画面提亮，明暗对比度扩大", "整体画面压暗，明暗对比度缩小"], answer: "B", answerText: "B"},
    {id: 6, type: 'single', question: "对偏暗、对比度偏弱的图像做直方图均衡处理，其核心作用是（）", options: ["统一降低图像整体亮度", "拉伸灰度分布区间，提升画面对比度", "大幅减少图像可用灰度等级", "消除图像里的高斯、椒盐噪声"], answer: "B", answerText: "B"},
    {id: 7, type: 'single', question: "图像进行灰度线性变换时, k=1,b>0,可以实现()功能。", options: ["降低图像对比度", "增强图像对比度", "降低图像亮度", "增强图像亮度"], answer: "D", answerText: "D"},
    {id: 8, type: 'single', question: "以下操作不能增强图像对比度的是()", options: ["直方图均衡", "空间平滑", "灰度线性变换", "灰度伽马变换"], answer: "B", answerText: "B"},
    {id: 9, type: 'single', question: "()的目的就是突出图像的边缘和轮廓信息,使图像看起来比较清晰。", options: ["空间平滑", "中值滤波", "空间放大", "空间锐化"], answer: "D", answerText: "D"},
    {id: 10, type: 'single', question: "对模糊照片做空间域锐化运算，该操作核心作用为（）", options: ["消除画面里的随机噪声点", "强化物体轮廓、微小纹理细节", "弱化前景，模糊背景画面", "压缩灰度动态范围，降低对比度"], answer: "B", answerText: "B"},
    {id: 11, type: 'single', question: "空间域模板中心系数为正、邻域系数为负，全部系数相加等于 0，该模板属于？", options: ["均值平滑模板", "拉普拉斯锐化模板", "高斯平滑模板", "中值滤波模板"], answer: "B", answerText: "B"},
    {id: 12, type: 'single', question: "相比于均值滤波，高斯滤波降噪同时可以更好保留图像的？", options: ["背景亮度", "边缘细节", "整体灰度均值", "直流分量"], answer: "B", answerText: "B"},
    {id: 13, type: 'single', question: "相较于均值滤波，中值滤波针对脉冲椒盐噪声最大的优势是（）", options: ["计算耗时更少", "抑制噪声同时边缘保留能力更强", "对高斯噪声降噪效果最优", "画面整体平滑程度更高"], answer: "B", answerText: "B"},
    {id: 14, type: 'single', question: "在处理含有胡椒噪声和盐粒噪声的图像时,下列哪种方法最有效?()", options: ["中值滤波", "均值滤波", "高斯滤波", "拉普拉斯滤波"], answer: "A", answerText: "A"},
    {id: 15, type: 'single', question: "下列图像处理中属于图像平滑处理的是()", options: ["直方图均衡", "中值滤波", "Hough 变换", "Roberts 算子"], answer: "B", answerText: "B"},
    {id: 16, type: 'single', question: "检测图像中异常的孤立点,优先选用哪种检测算子()", options: ["Roberts", "Prewitt", "Sobel", "Laplacian"], answer: "D", answerText: "D"},
    {id: 17, type: 'single', question: "在图像去噪过程中,如果噪声主要集中在高频部分,应优先考虑哪种滤波器?()", options: ["低通滤波器", "高通滤波器", "带通滤波器", "带阻滤波器"], answer: "A", answerText: "A"},
    {id: 18, type: 'single', question: "下列滤波器中,具有边缘保护机制的是()", options: ["算数均值滤波器", "自适应局部降噪滤波器", "修正的α均值滤波器", "谐波均值滤波器"], answer: "B", answerText: "B"},
    {id: 19, type: 'judge', question: "均值平滑滤波器可用于锐化图像边缘。", options: [], answer: "错误", answerText: "错误"},
    {id: 20, type: 'judge', question: "双边滤波器可以在保留边缘细节的同时去除噪声。", options: [], answer: "正确", answerText: "正确"},
    {id: 21, type: 'single', question: "脉冲型椒盐噪声的视觉外观特征是（）", options: ["只出现在画面高亮白色区域", "随机散布纯黑、纯白两种孤立噪点", "整图亮度均匀缓慢偏移", "只会干扰图像低频平滑区域"], answer: "B", answerText: "B"},
    {id: 22, type: 'single', question: "关于 Sobel 边缘算子与拉普拉斯（Laplacian）算子对比，描述正确的是（）", options: ["Sobel 依靠一阶梯度计算，拉普拉斯采用二阶微分", "二者都可以精准识别水平、垂直不同朝向的边缘", "拉普拉斯属于平滑滤波算子，Sobel 属于锐化算子", "Sobel 只能处理灰度图，拉普拉斯仅适配彩色图"], answer: "A", answerText: "A"},
    {id: 23, type: 'single', question: "根据二维傅里叶变换平移定理，图像在 x-y 空间内整体平移一段距离后，频谱会出现哪", options: ["幅度频谱数值改变，相位频谱无变化", "幅度频谱完全不变，相位频谱附加线性偏移量", "幅度、相位频谱均保持原样无变化", "幅度与相位频谱全部发生改变"], answer: "B", answerText: "B"},
    {id: 24, type: 'single', question: "图像傅里叶频谱中低频分量对应的图像内容是（）", options: ["孤立噪点、脉冲干扰", "物体边缘、细小纹理细节", "大面积平缓区域、图像整体轮廓", "高频细节与突变边界"], answer: "C", answerText: "C"},
    {id: 25, type: 'single', question: "振铃效应是影响图像复原质量的因素，使用下面哪种滤波器可以免受振铃效应的影响。", options: ["理想低通", "巴特沃斯低通", "高斯低通", "切比雪夫"], answer: "C", answerText: "C"},
    {id: 26, type: 'single', question: "关于巴特沃斯高通滤波器的描述,正确的是:", options: ["一阶滤波器不会产生振铃效应", "阶数越高,锐化效果越柔和", "其传递函数在频域呈现矩形形状", "不能用于医学图像增强"], answer: "A", answerText: "A"},
    {id: 27, type: 'judge', question: "高斯低通滤波器在选择小的截止频率时存在振铃效应和模糊现象。", options: [], answer: "错误", answerText: "错误"},
    {id: 28, type: 'single', question: "约束最小二乘图像复原算法中，一般选用哪种微分算子作为平滑约束条件？", options: ["Sobel", "拉普拉斯", "Roberts", "Prewitt"], answer: "B", answerText: "B"},
    {id: 29, type: 'single', question: "匀速直线运动模糊的退化函数 H(u, v)依赖哪些物理参数?", options: ["速度和时间", "加速度和距离", "频率和振幅", "角度和方向"], answer: "A", answerText: "A"},
    {id: 30, type: 'single', question: "一幅运动模糊的图像被高斯噪声所干扰,选择一种适用的滤波器来完成此图像复原。()", options: ["维纳滤波", "中值滤波器", "均值滤波器", "逆滤波"], answer: "A", answerText: "A"},
    {id: 31, type: 'single', question: "通常,电子电路噪声、低照明度和/或高温带来的传感器噪声属于()", options: ["瑞利噪声", "高斯噪声", "椒盐噪声", "均匀噪声"], answer: "B", answerText: "B"},
    {id: 32, type: 'single', question: "关于两者技术特点,正确的是:", options: ["直方图均衡化属于典型的复原技术", "逆滤波处理必须知道退化函数", "图像增强会引入新的信息", "盲去卷积属于增强范畴"], answer: "B", answerText: "B"},
    {id: 33, type: 'single', question: "区域生长分割算法中，属于最核心、默认终止条件的是（）", options: ["区域面积达到设定阈值", "不存在符合相似性准则的邻域像素", "分割出指定个数区域", "运行时间到达上限"], answer: "B", answerText: "B"},
    {id: 34, type: 'single', question: "启动区域生长分割算法，不属于该算法必需配置项的是（）", options: ["初始种子像素点", "像素相似度生长判断规则", "区域停止扩张的判定条件", "彩色图像三通道直方图数据"], answer: "D", answerText: "D"},
    {id: 35, type: 'single', question: "在数字图像处理中,当遇到光照不均或背景复杂的图像时,为什么传统的全局阈值方法可", options: ["因为光照不均会导致图像整体亮度降低", "因为背景复杂会增加图像的颜色多样性", "因为光照不均或背景复杂会导致灰度直方图缺乏明显的双峰特征", "因为光照不均会使图像边缘模糊"], answer: "C", answerText: "C"},
    {id: 36, type: 'single', question: "以下阈值分割方法中能够实现不均匀光照图像分割的是()", options: ["最大类间方差法(OTSU)", "最大熵法", "最小误差法", "自适应阈值法"], answer: "D", answerText: "D"},
    {id: 37, type: 'single', question: "在区域生长法分割图像的过程中,以下哪个不是关键要素?()", options: ["种子点的选择", "生长准则", "颜色直方图", "邻域定义"], answer: "C", answerText: "C"},
    {id: 38, type: 'single', question: "以下哪种分割算法思想是:把图像分割看作对像素进行分类的问题,将像素映射到特征空", options: ["聚类法", "分水岭法", "登山法", "分裂合并法"], answer: "A", answerText: "A"},
    {id: 39, type: 'single', question: "分水岭（Watershed）图像分割算法的核心模拟模型是（）", options: ["根据像素相似度逐步合并小区域", "通过梯度阈值提取物体边缘轮廓", "模拟地形洼地逐步注水、修建堤坝的过程", "依靠像素灰度聚类划分不同目标"], answer: "C", answerText: "C"},
    {id: 40, type: 'judge', question: "在光照不均或背景复杂的条件下,采用全局阈值方法可以有效地分割图像。", options: [], answer: "错误", answerText: "错误"},
    {id: 41, type: 'judge', question: "分块自适应法可以有效解决光照不均或背景复杂的图像分割问题。", options: [], answer: "正确", answerText: "正确"},
    {id: 42, type: 'judge', question: "图像分割所得的区域一定是一个连通集。", options: [], answer: "错误", answerText: "错误"},
    {id: 43, type: 'single', question: "下面不属于 DCT 离散余弦变换特征的是（）", options: ["实数运算", "能量集中", "对称正交", "复数运算"], answer: "D", answerText: "D"},
    {id: 44, type: 'single', question: "JPEG 有损压缩流程中离散余弦变换 DCT 承担的核心工作是（）", options: ["直接删减像素来缩小图像尺寸", "把空间域像素矩阵变换为频率域系数矩阵", "把彩色 RGB 图像转为单通道灰度图", "识别并提取物体边缘轮廓线条"], answer: "B", answerText: "B"},
    {id: 45, type: 'single', question: "在图像压缩操作中，压缩比数值越大，代表（）", options: ["解压还原后的画面清晰度越高", "压缩后的文件占用存储空间更小", "编码、解码运算耗时更短", "压缩过程丢失的像素信息越少"], answer: "B", answerText: "B"},
    {id: 46, type: 'single', question: "无损压缩编码技术最关键的特点是（）", options: ["能实现超高压缩倍率，但画面存在失真", "解码之后可以 100%复原原始图像数据，无信息丢失", "仅能针对黑白二值图像执行压缩", "压缩完成后图像对比度、清晰度会轻微下降"], answer: "B", answerText: "B"},
    {id: 47, type: 'fill', question: "JPEG 图像压缩标准中,对图像进行 DCT 变换后,经过______处理再进行熵编码,该过程会", options: [], answer: "A**", answerText: "A**"},
    {id: 48, type: 'single', question: "以下图像压缩编码方法中,属于有损压缩的是()", options: ["Huffman 编码", "行程编码", "算数编码", "基于 DCT 的连续变换"], answer: "D", answerText: "D"},
    {id: 49, type: 'single', question: "下列哪种编码方法在压缩时不需要预先知道数据的概率分布?", options: ["霍夫曼编码", "算术编码", "LZW 编码", "预测编码"], answer: "C", answerText: "C"},
    {id: 50, type: 'judge', question: "LZW 编码适合处理完全随机分布的数据。", options: [], answer: "错误", answerText: "错误"},
    {id: 51, type: 'judge', question: "所有无损压缩方法都可以完全恢复原始图像数据。", options: [], answer: "正确", answerText: "正确"},
    {id: 52, type: 'judge', question: "霍夫曼编码的码表需要在压缩文件中保存。", options: [], answer: "正确", answerText: "正确"},
    {id: 53, type: 'single', question: "霍夫(Hough)变换是图像处理中经典算法，主要用来提取图像哪一类特征（）", options: ["色块纹理、粗糙度特征", "RGB、HSI 色彩分量特征", "直线、圆形这类规则几何形状", "像素灰度统计直方图"], answer: "C", answerText: "C"},
    {id: 54, type: 'single', question: "图像缩放几何变换里，易出现锯齿、计算量最小的插值方式是（）", options: ["最近邻插值", "双线性插值", "双三次插值", "样条插值"], answer: "A", answerText: "A"},
    {id: 55, type: 'single', question: "关于图像距离度量,错误的是:", options: ["$D_4$ 距离满足三角不等式", "$D_8$ 距离是 $D_4$ 距离的下限值", "欧氏距离 $(D_2) ≤D_8$ 距离", "当两点在同一对角线时 $D_4=D_8$"], answer: "D", answerText: "D"},
    {id: 56, type: 'single', question: "能够实现图像缩放的函数是()", options: ["resize", "getRotationMatrix2D", "warpAffine", "Flip"], answer: "A", answerText: "A"},
    {id: 57, type: 'single', question: "以下基于形态学的图像处理方法中可以实现平滑图像轮廓,同时去掉细长的突起、边缘、", options: ["腐蚀", "膨胀", "开运算", "闭运算"], answer: "C", answerText: "C"},
    {id: 58, type: 'fill', question: "数字图像采集时，______操作决定空间分辨率（像素疏密）；______操作划分灰度等级，", options: [], answer: "采样；量化", answerText: "采样；量化"},
    {id: 59, type: 'fill', question: "图像获取即图像的数字化过程,包括______、______、______和______。", options: [], answer: "采样、量化、扫描、存储", answerText: "采样、量化、扫描、存储"},
    {id: 60, type: 'fill', question: "在数字图像处理中,常用的图像类型包括______、彩色图像和______。", options: [], answer: "二值图像；灰度图像", answerText: "二值图像；灰度图像"},
    {id: 61, type: 'fill', question: "人类的视觉系统有增强边缘对比度的机制,往往会在不同灰度区域的边界处出现“下冲”", options: [], answer: "马赫带效应", answerText: "马赫带效应"},
    {id: 62, type: 'fill', question: "空间域滤波中，模板中心系数为正、四周系数为负、整体系数和为 0，是______滤波模板", options: [], answer: "锐化（拉普拉斯锐化）", answerText: "锐化（拉普拉斯锐化）"},
    {id: 63, type: 'fill', question: "约束最小二乘图像复原，采用______算子作为平滑约束条件。", options: [], answer: "拉普拉斯", answerText: "拉普拉斯"},
    {id: 64, type: 'fill', question: "高斯滤波对比均值滤波，优势是平滑降噪同时更好保留图像______。", options: [], answer: "边缘（细节）", answerText: "边缘（细节）"},
    {id: 65, type: 'fill', question: "给出三种图像降噪的方法:________________________。", options: [], answer: "均值滤波、中值滤波、高斯滤波", answerText: "均值滤波、中值滤波、高斯滤波"},
    {id: 66, type: 'fill', question: "从频率域看,______滤波可以对图像进行平滑去噪处理,______滤波可对图像进行边缘锐", options: [], answer: "低通；高通", answerText: "低通；高通"},
    {id: 67, type: 'fill', question: "现需对模糊文本图像进行锐化:若使用巴特沃斯高通滤波器,出现了振铃效应,应调整", options: [], answer: "阶数/截止频率；边缘处的明暗振荡条纹", answerText: "阶数/截止频率；边缘处的明暗振荡条纹"},
    {id: 68, type: 'fill', question: "二维傅里叶变换频谱坐标原点$F(0,0)$为直流分量，数值大小对应整幅图像的______平", options: [], answer: "整体（全局）", answerText: "整体（全局）"},
    {id: 69, type: 'fill', question: "在傅里叶变换中,去中心化后的频域图像的直流分量反映了空间图像的______。", options: [], answer: "平均亮度", answerText: "平均亮度"},
    {id: 70, type: 'fill', question: "图像在空间域发生平移,其幅度谱______,相位______。(填“不变”或“改变”)", options: [], answer: "不变；改变", answerText: "不变；改变"},
    {id: 71, type: 'fill', question: "逆滤波复原直接对退化传递函数求逆运算，当退化函数频域取值趋近于______时，噪声", options: [], answer: "0（零点）", answerText: "0（零点）"},
    {id: 72, type: 'fill', question: "图像复原（恢复）算法的核心目标：消除成像过程引入的______与退化失真，还原原始", options: [], answer: "噪声（模糊退化因素）", answerText: "噪声（模糊退化因素）"},
    {id: 73, type: 'fill', question: "图像复原和图像增强的区别:______的目的是主观的,______的目的是客观的。", options: [], answer: "图像增强；图像复原", answerText: "图像增强；图像复原"},
    {id: 74, type: 'fill', question: "阈值分割的关键是寻找合适的阈值。Otsu’s 方法是______的阈值求取方法。", options: [], answer: "最大类间方差", answerText: "最大类间方差"},
    {id: 75, type: 'fill', question: "区域生长是一种图像____方法,实现该方法的两个重要元素是________和________。", options: [], answer: "分割；种子点的选取；生长准则\n\n\f**解析**：种子点、相似性生长准则是区域生长的两大核心要素。", answerText: "分割；种子点的选取；生长准则\n\n\f**解析**：种子点、相似性生长准则是区域生长的两大核心要素。"},
    {id: 76, type: 'fill', question: "当遇到光照不均或背景复杂的图像时,可以通过采用______的方法来改善图像分割效果,", options: [], answer: "分块自适应；单独计算最佳阈值", answerText: "分块自适应；单独计算最佳阈值"},
    {id: 77, type: 'fill', question: "哈夫曼(Huffman)编码属于______前缀编码，符号发生概率越高，分配的码字长度越短，", options: [], answer: "变长；反", answerText: "变长；反"},
    {id: 78, type: 'fill', question: "灰度直方图用来统计图像数据，横轴为灰度等级，纵轴对应该灰度级别像素出现的", options: [], answer: "像素个数（频次/概率）", answerText: "像素个数（频次/概率）"},
    {id: 79, type: 'fill', question: "哈夫曼编码、算术编码、行程编码都归属于______编码，依托信源熵理论实现压缩。", options: [], answer: "熵（无损熵）", answerText: "熵（无损熵）"},
    {id: 80, type: 'fill', question: "按照处理坐标空间划分，图像增强技术分为直接操作像素点的______处理，和先变换频", options: [], answer: "空间；频率", answerText: "空间；频率"},
    {id: 81, type: 'fill', question: "能够将多个符号编码为一个区间小数的无损压缩方法是______。", options: [], answer: "算术编码", answerText: "算术编码"},
    {id: 82, type: 'fill', question: "将图像分解成各个比特平面有助于分析图像中每个比特的相对重要性。___________比", options: [], answer: "高阶；低阶", answerText: "高阶；低阶"},
    {id: 83, type: 'fill', question: "在图像的比特平面分解中,______比特平面包含最显著的视觉信息。", options: [], answer: "最高有效位（高阶/MSB）", answerText: "最高有效位（高阶/MSB）"},
    {id: 84, type: 'fill', question: "像素坐标(x,y)的 4 邻域（四连通邻域）包含四个坐标：______、______、______、______。", options: [], answer: "(x+1,y)、(x-1,y)、(x,y+1)、(x,y-1)", answerText: "(x+1,y)、(x-1,y)、(x,y+1)、(x,y-1)"},
    {id: 85, type: 'fill', question: "三种像素距离度量里，两点之间真实直线几何长度用______距离计算。", options: [], answer: "欧氏", answerText: "欧氏"},
    {id: 86, type: 'fill', question: "若以 4-邻接定义通路,则黑色像素集 S 中包含______个连通分量;若用 8-邻接来定义通路,", options: [], answer: "3；1；不是", answerText: "3；1；不是"},
    {id: 87, type: 'fill', question: "边界描绘子的常见类型包括______、______和多边形近似等。(写出两种即可)", options: [], answer: "链码；傅里叶描绘子", answerText: "链码；傅里叶描绘子"},
    {id: 88, type: 'fill', question: "在图像数学形态学中,闭运算是先进行______运算,后进行______运算。", options: [], answer: "膨胀；腐蚀", answerText: "膨胀；腐蚀"},
    {id: 89, type: 'judge', question: "采样间隔越大，分辨率越低。（）", options: [], answer: "正确", answerText: "采样间隔越大→像素数越少→空间分辨率越低。"},
    {id: 90, type: 'judge', question: "灰度线性变换斜率大于1时，图像对比度增强。（）", options: [], answer: "正确", answerText: "k>1时灰度区间被拉伸，对比度增大。"},
    {id: 91, type: 'judge', question: "直方图均衡化可以直接对RGB三通道分别处理。（）", options: [], answer: "错误", answerText: "直接对RGB三通道分别均衡化会改变颜色比例，造成色彩失真，应在HSI空间仅对I通道处理。"},
    {id: 92, type: 'judge', question: "均值滤波是线性滤波，可以有效去除高斯噪声。（）", options: [], answer: "正确", answerText: "均值滤波是线性平滑滤波器，对高斯噪声有良好抑制效果。"},
    {id: 93, type: 'judge', question: "高频强调滤波能在增强边缘的同时保留低频信息。（）", options: [], answer: "正确", answerText: "高频强调滤波在高通滤波基础上加偏移量，保留低频背景信息。"},
    {id: 94, type: 'judge', question: "双线性插值比最近邻插值效果更好且计算更简单。（）", options: [], answer: "错误", answerText: "双线性插值效果更好但计算更复杂；最近邻插值计算最简单但易产生锯齿。"},
    {id: 95, type: 'judge', question: "直方图规定化可以将图像直方图变换为指定形状。（）", options: [], answer: "正确", answerText: "直方图规定化（匹配）可指定目标直方图形状。"},
    {id: 96, type: 'judge', question: "高分辨率图像比低分辨率图像包含更多细节信息。（）", options: [], answer: "正确", answerText: "分辨率越高，像素越密集，细节越丰富。"},
    {id: 97, type: 'judge', question: "Canny边缘检测中的非极大值抑制可将粗边缘细化为单像素宽边缘。（）", options: [], answer: "正确", answerText: "非极大值抑制是Canny算法的关键步骤，用于细化边缘。"},
    {id: 98, type: 'judge', question: "逆滤波在存在噪声时，高频成分被噪声主导，复原效果很差。（）", options: [], answer: "正确", answerText: "退化函数零点附近噪声被放大，逆滤波对噪声极其敏感。"},
    {id: 99, type: 'judge', question: "无损压缩的压缩比高，但图像质量会下降。（）", options: [], answer: "错误", answerText: "这是有损压缩的特点。无损压缩压缩比通常较低，但可100%复原原始数据。"},
    {id: 100, type: 'judge', question: "中值滤波是线性滤波的一种。（）", options: [], answer: "错误", answerText: "中值滤波是非线性滤波，取邻域中值而非加权平均。"},
    {id: 101, type: 'essay', question: "简述数字图像处理的定义及其三个层次。", options: [], answer: "定义：利用计算机对数字图像进行数学运算和加工处理。\n三个层次：\n（1）低级处理：输入输出均为图像（如去噪、增强）；\n（2）中级处理：输入图像，输出特征（如分割、描述）；\n（3）高级处理：理解识别（如图像理解、模式识别）。", answerText: "定义：利用计算机对数字图像进行数学运算和加工处理。\n三个层次：\n（1）低级处理：输入输出均为图像（如去噪、增强）；\n（2）中级处理：输入图像，输出特征（如分割、描述）；\n（3）高级处理：理解识别（如图像理解、模式识别）。"},
    {id: 102, type: 'essay', question: "简述傅里叶变换在图像处理中的物理意义及频域滤波基本步骤。", options: [], answer: "物理意义：将图像从空间域转换到频率域，分解为不同频率的正弦波叠加。\n低频→整体轮廓和大面积平缓区域；高频→边缘、细节、纹理和噪声。\n频域滤波步骤：\n①傅里叶变换\n②频域原点中心化\n③与滤波器传递函数相乘\n④反中心化\n⑤逆傅里叶变换回空间域", answerText: "物理意义：将图像从空间域转换到频率域，分解为不同频率的正弦波叠加。\n低频→整体轮廓和大面积平缓区域；高频→边缘、细节、纹理和噪声。\n频域滤波步骤：\n①傅里叶变换\n②频域原点中心化\n③与滤波器传递函数相乘\n④反中心化\n⑤逆傅里叶变换回空间域"},
    {id: 103, type: 'essay', question: "简述数字图像采样和量化的概念及区别。", options: [], answer: "采样：对连续图像的空间坐标进行离散化（决定空间分辨率）。\n量化：对连续灰度值进行离散化（决定灰度分辨率）。\n区别：采样离散化空间坐标，量化离散化灰度幅值。", answerText: "采样：对连续图像的空间坐标进行离散化（决定空间分辨率）。\n量化：对连续灰度值进行离散化（决定灰度分辨率）。\n区别：采样离散化空间坐标，量化离散化灰度幅值。"},
    {id: 104, type: 'essay', question: "简述傅里叶变换的四个基本性质。", options: [], answer: "（1）线性性：线性组合的变换等于变换的线性组合。\n（2）平移性：空间域平移→幅度谱不变、相位谱附加线性偏移。\n（3）旋转性：空间域旋转→频率域相同角度旋转。\n（4）卷积定理：空间域卷积=频率域乘积。", answerText: "（1）线性性：线性组合的变换等于变换的线性组合。\n（2）平移性：空间域平移→幅度谱不变、相位谱附加线性偏移。\n（3）旋转性：空间域旋转→频率域相同角度旋转。\n（4）卷积定理：空间域卷积=频率域乘积。"},
    {id: 105, type: 'essay', question: "直方图均衡化计算：给定一幅4×4的8级灰度图像（灰度级0~7），灰度矩阵如下，请写出直方图均衡化的完整计算过程并给出结果矩阵。\n灰度矩阵：\n3 3 3 2\n5 5 3 5\n7 6 3 2\n6 6 3 5", options: [], answer: "解题步骤：\n①统计各灰度级像素个数和概率 p(rk)=nk/N（N=16）\n灰度级0:0个 p=0\n灰度级1:0个 p=0\n灰度级2:2个 p=2/16=0.125\n灰度级3:5个 p=5/16=0.3125\n灰度级4:0个 p=0\n灰度级5:4个 p=4/16=0.25\n灰度级6:3个 p=3/16=0.1875\n灰度级7:2个 p=2/16=0.125\n\n②计算CDF\nCDF(0)=0, CDF(1)=0, CDF(2)=0.125, CDF(3)=0.4375\nCDF(4)=0.4375, CDF(5)=0.6875, CDF(6)=0.875, CDF(7)=1.0\n\n③均衡化映射 sk=round(CDF×7)\ns0=0, s1=0, s2=1, s3=3, s4=3, s5=5, s6=6, s7=7\n\n④结果矩阵：\n3 3 3 1\n5 5 3 5\n7 6 3 1\n6 6 3 5", answerText: "解题步骤：\n①统计各灰度级像素个数和概率 p(rk)=nk/N（N=16）\n灰度级0:0个 p=0\n灰度级1:0个 p=0\n灰度级2:2个 p=2/16=0.125\n灰度级3:5个 p=5/16=0.3125\n灰度级4:0个 p=0\n灰度级5:4个 p=4/16=0.25\n灰度级6:3个 p=3/16=0.1875\n灰度级7:2个 p=2/16=0.125\n\n②计算CDF\nCDF(0)=0, CDF(1)=0, CDF(2)=0.125, CDF(3)=0.4375\nCDF(4)=0.4375, CDF(5)=0.6875, CDF(6)=0.875, CDF(7)=1.0\n\n③均衡化映射 sk=round(CDF×7)\ns0=0, s1=0, s2=1, s3=3, s4=3, s5=5, s6=6, s7=7\n\n④结果矩阵：\n3 3 3 1\n5 5 3 5\n7 6 3 1\n6 6 3 5"},
    {id: 106, type: 'essay', question: "霍夫曼编码计算：某图像有5个灰度级A、B、C、D、E，概率分别为 P(A)=0.4, P(B)=0.3, P(C)=0.1, P(D)=0.1, P(E)=0.1。请：①计算信息熵 H ②构造霍夫曼树并给出各符号编码 ③计算平均码长 ④计算编码效率。", options: [], answer: "①信息熵 H = -Σp(i)log₂p(i)\n= -[0.4log₂0.4 + 0.3log₂0.3 + 3×0.1log₂0.1]\n= -[0.4×(-1.322) + 0.3×(-1.737) + 0.3×(-3.322)]\n= 2.0465 bit\n\n②霍夫曼编码（自底向上合并最小概率对）：\nC(0.1)+D(0.1)=CD(0.2)\nE(0.1)+CD(0.2)=ECD(0.3)\nB(0.3)+ECD(0.3)=BECD(0.6)\nA(0.4)+BECD(0.6)=ROOT(1.0)\n编码（左0右1）：A=0, B=10, C=110, D=1110, E=1111\n\n③平均码长 L_avg = Σp(i)×li\n= 0.4×1 + 0.3×2 + 0.1×3 + 0.1×4 + 0.1×4 = 2.1 bit\n\n④编码效率 η = H/L_avg × 100% = 2.0465/2.1 = 97.45%", answerText: "①信息熵 H = -Σp(i)log₂p(i)\n= -[0.4log₂0.4 + 0.3log₂0.3 + 3×0.1log₂0.1]\n= -[0.4×(-1.322) + 0.3×(-1.737) + 0.3×(-3.322)]\n= 2.0465 bit\n\n②霍夫曼编码（自底向上合并最小概率对）：\nC(0.1)+D(0.1)=CD(0.2)\nE(0.1)+CD(0.2)=ECD(0.3)\nB(0.3)+ECD(0.3)=BECD(0.6)\nA(0.4)+BECD(0.6)=ROOT(1.0)\n编码（左0右1）：A=0, B=10, C=110, D=1110, E=1111\n\n③平均码长 L_avg = Σp(i)×li\n= 0.4×1 + 0.3×2 + 0.1×3 + 0.1×4 + 0.1×4 = 2.1 bit\n\n④编码效率 η = H/L_avg × 100% = 2.0465/2.1 = 97.45%"},
];
