// 综合作业二-Verilog HDL与数字IC设计
const questionsZuoye2 = [

    {id: 1, type: 'single', question: "IP 核的核心特点是", options: ["与芯片制造工艺紧密相关", "未经过验证的宏模块", "可移植到不同半导体工艺", "仅能用于 ASIC 设计"], answer: "C", answerText: ""},
    {id: 2, type: 'single', question: "数字集成电路设计流程中，RTL 编码属于哪个阶段", options: ["系统设计阶段", "电路设计和代码编写阶段", "电路验证阶段", "后端设计阶段"], answer: "B", answerText: ""},
    {id: 3, type: 'single', question: "Verilog HDL 中，存储器型变量本质上是", options: ["wire 型变量阵列", "reg 型变量阵列", "integer 型变量阵列", "real 型变量阵列"], answer: "B", answerText: ""},
    {id: 4, type: 'single', question: "下列哪种语句只能用于仿真，不能用于可综合电路设计?", options: ["begin-end", "fork-join", "if-else", "case"], answer: "B", answerText: ""},
    {id: 5, type: 'single', question: "casex 语句与 case 语句的区别是", options: ["忽略 x 和 z 位的比较", "只忽略 x 位的比较", "只忽略 z 位的比较", "按位或比较"], answer: "A", answerText: ""},
    {id: 6, type: 'single', question: "结构化建模中，顶层模块的特点是", options: ["可以被多个模块调用", "不被任何其他模块调用", "只能包含门级元件", "只能包含开关级元件"], answer: "B", answerText: ""},
    {id: 7, type: 'single', question: "Verilog HDL 中内置的基本门级元件不包括", options: ["and", "nmos", "or", "xor"], answer: "B", answerText: ""},
    {id: 8, type: 'single', question: "优先编码器的特点是", options: ["平等编码", "只对优先级最高的编码", "输出十进制", "需要时钟"], answer: "B", answerText: ""},
    {id: 9, type: 'single', question: "奇偶校验器的作用是", options: ["纠错", "加密", "检错", "压缩"], answer: "C", answerText: ""},
    {id: 10, type: 'single', question: "模 256 计数器需要的寄存器位宽是", options: ["4 位", "8 位", "16 位", "32 位"], answer: "B", answerText: ""},
    {id: 11, type: 'single', question: "门级延时使用 2 个值(d1,d2)时，截止延时与到 x 延时取", options: ["d1", "d2", "min(d1,d2", "max(d1,d2"], answer: "C", answerText: ""},
    {id: 12, type: 'single', question: "函数(function)中不能包含", options: ["输入端口", "延时/时序控制", "循环语句", "赋值语句"], answer: "B", answerText: ""},
    {id: 13, type: 'single', question: "任务与函数的主要区别是", options: ["函数可调用任务", "任务不能调用函数", "函数不能含延时，任务可以", "任务必须有返回值"], answer: "C", answerText: ""},
    {id: 14, type: 'single', question: "在数字芯片设计中，软核(Soft Core)最突出的特点是", options: ["性能最优、面积固定", "以 Verilog/VHDL 源码提供，灵活性最高，可综合适配不同工艺", "已经完成物理实现，直接以版图形式集成", "只能用于特定厂家的 FPGA 芯片"], answer: "B", answerText: ""},
    {id: 15, type: 'single', question: "关于固核(Firm Core)的定位，正确的是", options: ["未经过综合的 Verilog 源码，完全灵活", "经过逻辑综合的门级网表，完成了布局布线，物理版图固定", "经过逻辑综合得到门级网表，未做最终物理版图，可部分调整布局", "性能、面积、功能均不可修改"], answer: "C", answerText: ""},
    {id: 16, type: 'single', question: "在 Verilog HDL 数字集成电路设计流程中，不属于 Verilog HDL 直接应用范 围的步骤是", options: ["RTL 编码", "物理验证", "综合", "时序验证"], answer: "B", answerText: ""},
    {id: 17, type: 'single', question: "关于 Verilog HDL 在数字集成电路设计流程中的作用，下列说法正确的是", options: ["Verilog HDL 可以直接用于物理综合与布局布线", "Verilog HDL 的应用范围覆盖了从总体方案到工艺实现的所有阶段", "Verilog HDL 主要用于系统建模、RTL 编码、功能验证与时序验证等阶段", "综合和物理验证阶段也完全依赖 Verilog HDL"], answer: "C", answerText: ""},
    {id: 18, type: 'single', question: "下列关于 Verilog 标识符的命名规则，说法正确的是", options: ["标识符可以以数字开头", "标识符可以包含空格和特殊符号(如 @、#", "标识符区分大小写，data 和 Data 是不同的标识符", "标识符长度没有任何限制"], answer: "C", answerText: ""},
    {id: 19, type: 'single', question: "下列字符串中，属于合法 Verilog 标识符的是", options: ["123_data", "data@in", "_clk_1", "input"], answer: "C", answerText: ""},
    {id: 20, type: 'single', question: "下列关于 Verilog 标识符命名的说法，错误的是", options: ["普通标识符只能由字母、数字、下划线_和美元符号$组成", "普通标识符不能以数字开头", "signal 是合法的标识符", "signal$是非法的标识符"], answer: "D", answerText: ""},
    {id: 21, type: 'single', question: "下列关于 Verilog HDL 四种基本逻辑数值状态的说法，错误的是", options: ["0 代表低电平、逻辑 0 或 “假”", "1 代表高电平、逻辑 1 或 “真”", "x 或 X 表示确定的逻辑状态", "z 或 Z 表示高阻态"], answer: "C", answerText: ""},
    {id: 22, type: 'single', question: "关于 Verilog 中 reg 类型的描述，正确的是", options: ["只能在连续赋值语句中使用", "是一种寄存器类型，常用于时序逻辑中存储数据", "只能表示一位二进制数", "不能被初始化"], answer: "B", answerText: ""},
    {id: 23, type: 'single', question: "下列关于 Verilog 数据类型的说法，错误的是", options: ["wire 类型默认值为高阻态 z", "reg 类型可以在 always 块中被赋值", "time 类型用于存储仿真时间，其单位由 `timescale 指令决定", "reg 类型只能在时序逻辑中使用，组合逻辑中无法使用"], answer: "D", answerText: ""},
    {id: 24, type: 'single', question: "在 Verilog 中，下列关于 wire 和 reg 类型的描述，错误的是", options: ["wire 类型用于表示物理连线，常用于组合逻辑", "reg 类型在仿真中存储数值，常用于时序逻辑", "wire 类型可以在 always 块中直接赋值", "reg 类型可以在 initial 块中赋值"], answer: "C", answerText: ""},
    {id: 25, type: 'single', question: "关于 Verilog 中 localparam 与 parameter 的区别，说法正确的是", options: ["localparam 可以在模块外部被重载", "parameter 只能在模块内部使用，不能被重载", "localparam 的值在模块内部定义后不可修改，不能被外部重载", "parameter 可以用于定义常量，localparam 不能用于定义常量"], answer: "C", answerText: ""},
    {id: 26, type: 'single', question: "在 Verilog 中，执行无符号数算术运算时，若运算结果超出变量位宽范围， 会发生的现象是", options: ["自动扩展位宽以保存完整结果", "高位自动截断，仅保留低位部分", "运算结果自动变为不定态 x", "直接报错终止仿真"], answer: "B", answerText: ""},
    {id: 27, type: 'single', question: "在 Verilog 中，全等操作符 === 与相等操作符 == 的核心区别是", options: ["=== 仅用于整数比较，== 可用于任意类型", "=== 会严格比较 x 和 z 状态，== 对包含 x 或 z 的比较结果为不定态", "== 会严格比较 x 和 z 状态，=== 则忽略 x 和 z", "全等操作符 === 不能用于条件分支语句中"], answer: "B", answerText: ""},
    {id: 28, type: 'single', question: "下列关于 Verilog 中相等与全等操作符的说法，错误的是", options: ["== 属于逻辑相等比较，常用于仿真中的条件判断", "=== 属于全等比较，常用于测试平台中精确匹配信号状态", "== 可以在可综合代码中用于比较包含 x 或 z 的信号", "=== 比较时，x 只能和 x 相等，z 只能和 z 相等"], answer: "C", answerText: ""},
    {id: 29, type: 'single', question: "已知 a=4'b1010，执行归约运算&a 的结果是", options: ["1'b0", "1'b1", "4'b0000", "4'b1111"], answer: "A", answerText: ""},
    {id: 30, type: 'single', question: "关于 Verilog 按位运算的描述，正确的是", options: ["对多个信号整体进行逻辑判断，结果为 1 位", "对两个操作数的每一位分别运算，结果位宽与操作数相同", "对单信号逐位运算，最终归约成 1 位结果", "只能用于 0 和 1 的逻辑判断"], answer: "B", answerText: ""},
    {id: 31, type: 'single', question: "Verilog 中条件运算符的标准格式是", options: ["表达式 1 ? 表达式 2 : 表达式 3", "表达式 1 : 表达式 2 ? 表达式 3", "if (表达式 1) 表达式 2 else 表达式 3", "表达式 1 -> 表达式 2 : 表达式 3"], answer: "A", answerText: ""},
    {id: 32, type: 'single', question: "语句 out = sel ? a : b;中，sel 为 1 时执行结果是", options: ["out 赋值为 a", "out 赋值为 b", "输出不定态", "输出高阻态"], answer: "A", answerText: ""},
    {id: 33, type: 'single', question: "语句 out = sel ? a : b;中，sel 为 0 时执行结果是", options: ["out 赋值为 a", "out 赋值为 b", "输出不定态", "输出高阻态"], answer: "B", answerText: ""},
    {id: 34, type: 'single', question: "对比同步清零和异步清零两种方式，异步清零优势在于", options: ["时序同步性更好", "复位动作即时生效", "布线难度更低", "建立时间要求宽松"], answer: "B", answerText: ""},
    {id: 35, type: 'single', question: "分析下列代码: class Packet; integer i = 4; virtual function integer get; get = i; endfunction endclass class LinkedPacket extends Packet; integer I = 1; function integer get; get = -I; endfunction endclass module test; LinkedPacket lp = new; Packet p = lp; initial begin $display(\"%0d\", p.i); // 输出① $display(\"%0d\", p.get); // 输出② end endmodule 程序执行后，①和②的输出结果分别是", options: ["1, -2", "4, -1", "1, -4", "4, 1"], answer: "B", answerText: ""},
    {id: 36, type: 'single', question: "下图是通过逻辑抽象得到原始状态转移图，请判断下图中哪两个状态是等 价状态?", options: ["S0 与 S1", "S1 与 S2", "S2 与 S3", "S3 与 S4"], answer: "C", answerText: ""},
    {id: 37, type: 'single', question: "根据输出逻辑的划分，Verilog 有限状态机主要分为", options: ["同步状态机、异步状态机", "Moore 型、Mealy 型", "单进程状态机、多进程状态机", "二进制编码、格雷码编码状态机"], answer: "B", answerText: ""},
    {id: 38, type: 'single', question: "下列变量名(标识符)中，全部符合 Verilog HDL 命名规则的一组是", options: ["2_1mux、 \\din", "n@238、 \\wait", "out*、Always", "COUNT、B25_38"], answer: "D", answerText: ""},
    {id: 39, type: 'single', question: "下列 Verilog 代码片段中，哪一项能正确实现一个模 16(0~15)的二进制计 数器，且代码结构最优?(假设 count 为 4 位寄存器，clk 为时钟，rst 为复位 信号)", options: ["always @(posedge clk) begin if (rst) count <= 4'b0000; else if (count == 4'b1111) count <= 4'b0000; else count <= count + 1; end", "always @(posedge clk) begin if (rst) count <= 4'b0000; else count <= count + 1; end", "always @(posedge clk) begin if (rst) count <= 4'b0000; else if (count == 4'b1000) count <= 4'b0000; else count <= count + 1; end", "always @(negedge clk) begin count <= count + 1; end"], answer: "B", answerText: ""},
    {id: 40, type: 'single', question: "已知 Verilog 中定义变量 A=4'b101011，下列关于归约运算符的表达式及其 结果，哪一项是错误的?", options: ["B = &A //B=1’b0", "B = |A // B=1’b1", "B = ^A //B =1’b1", "B =~^A //B=1'b1"], answer: "C", answerText: ""},
    {id: 41, type: 'single', question: "`timescale 10ns/1ns module delay_tb; reg set; parameter d = 1.55; initial begin #d set = 0; #d set = 1; end endmodule 根据 timescale 指令的定义和仿真行为，下列哪一项对模块中延迟行为的描述是 完全正确的?", options: ["模块的时间单位为 1ns，时间精度为 10ns，因此延迟#d 实际为 1.55ns，set 在 1.55ns 和 3.1ns 时分别被赋值。", "由于时间精度为 1ns，参数 d=1.55 将被截断为 1.5，因此两次延迟均为15ns，set 在 15ns 和 30ns 时赋值。", "时间单位为 10ns，时间精度为 1ns，d=1.55 将四舍五入为 1.6，实际延迟为 16ns，因此 set 在 16ns 和 32ns 时分别被赋值。", "时间单位为 10ns，d=1.55 表示 15.5ns，因精度为 1ns，故直接取整为15ns，set 在 15ns 和 30ns 时赋值。"], answer: "C", answerText: ""},
    {id: 42, type: 'single', question: "软核(Soft Core)最准确的描述是?​", options: ["在 FPGA 上直接烧录的二进制配置文件", "经过物理版图验证的 ASIC 掩模文件", "经过功能验证、5000 门以上、可用 Verilog HDL 或 VHDL 描述可综合设计", "已固化在芯片中、不可修改的硬件逻辑模块 C42、从灵活性到物理实现的顺序，以下 IP 核类型排列正确的是?"], answer: "B", answerText: ""},
    {id: 43, type: 'single', question: "关于 SystemVerilog IEEE 1800-2005 标准，以下哪项描述最准确?", options: ["它是独立开发的新语言，与 Verilog HDL 无任何语法兼容性。", "它是 VHDL 语言的扩展版本，主要用于软件建模。", "它建立在 Verilog HDL 基础上，是 IEEE 1364 Verilog-2001 标准的扩展增强，兼容 verilog-2001，面向下一代硬件设计与验证,", "它于 2001 年发布，主要用于替代 VHDL 成为主流硬件描述语言。"], answer: "C", answerText: ""},
    {id: 44, type: 'single', question: "若 a = 4’b1111, b = 4’b0000，则 a && b 的结果是?", options: ["0", "1", "x", "不确定"], answer: "A", answerText: ""},
    {id: 45, type: 'single', question: "在 Verilog HDL 的数据流建模中，连续赋值语句(assign)的赋值目标必须是 什么类型?​", options: ["reg 型", "integer 型", "wire 型", "parameter 型"], answer: "C", answerText: ""},
    {id: 46, type: 'single', question: "在以下代码片段中，repeat(8)#50 clock=~clock;的作用是? initial begin clock =0; repeat(8)#50 clock =~clock; end", options: ["产生 8 个周期的时钟信号，每个周期 50 个时间单位", "产生 4 个完整周期的时钟信号(高低电平各 8 次", "产生 8 个上升沿，每个间隔 50 个时间单位", "无限翻转 clock，共持续 400 个时间单位"], answer: "B", answerText: ""},
    {id: 47, type: 'single', question: "对比三种结构化建模方式，说法正确的是", options: ["开关级建模抽象层次最高，通用性最强", "门级建模直接描述晶体管导通与关断状态", "模块级建模适合大型复杂数字系统设计", "结构化建模都无法转换为实际硬件电路"], answer: "C", answerText: ""},
    {id: 48, type: 'single', question: "在 Verilog 设计中，若时序逻辑代码出现电平敏感的 always @(*)，该写法 会", options: ["正常生成纯时序电路", "综合出组合逻辑，破坏时序电路结构", "仅影响仿真，不影响综合结果", "自动转换为时钟边沿触发"], answer: "B", answerText: ""},
    {id: 49, type: 'single', question: "同步时序电路的主要特点是", options: ["所有寄存器共用同一个时钟信号", "各寄存器使用独立时钟，互不干扰", "复位信号可随时生效，不受时钟控制", "输出仅由当前输入直接决定"], answer: "A", answerText: ""},
    {id: 50, type: 'single', question: "在 `timescale 1ns / 1ps 下，#5.5555 实际延迟时间会被取为", options: ["5.555ns", "5.556ns", "5.5ns", "5.6ns"], answer: "B", answerText: ""},
    {id: 51, type: 'single', question: "对于下述程序，程序执行到第 40 个时间单位时停止仿真，则打印输出的 最后一个仿真时刻是", options: ["35", "40", "45", "30"], answer: "A", answerText: ""},
    {id: 52, type: 'single', question: "分析下列代码： always @(posedge clk) begin a <= b; b <= a; end 关于执行结果，正确的是", options: ["a 和 b 完成数据交换", "a 和 b 都变成原值不变", "a 被 b 覆盖，b 不变", "b 被 a 覆盖，a 不变"], answer: "A", answerText: ""},
    {id: 53, type: 'fill', question: "寄存器变量 a、b 的值分别为 4’b1110 和 4’b0000，则 a &&b=____; a || b=____;", options: [], answer: "0；1", answerText: "0；1"},
    {id: 54, type: 'fill', question: "`timescale 用于定义仿真____和____。", options: [], answer: "时间单位；时间精度", answerText: "时间单位；时间精度"},
    {id: 55, type: 'fill', question: "Testbench 中产生时钟、复位等激励，主要使用____过程块。", options: [], answer: "initial", answerText: "initial"},
    {id: 56, type: 'fill', question: "双端口 RAM 拥有两套独立的地址、数据总线，支持同时____和____。", options: [], answer: "读；写", answerText: "读；写"},
    {id: 57, type: 'fill', question: "Verilog 中可无限循环的循环语句是____，常用于生成仿真时钟。", options: [], answer: "forever", answerText: "forever"},
    {id: 58, type: 'fill', question: "8421BCD 码是用____位二进制数表示一位十进制数。", options: [], answer: "4", answerText: "4"},
    {id: 59, type: 'fill', question: "十进制数 6 的 8421 BCD 码是 ____，其对应的余 3 码是 ____。", options: [], answer: "0110；1001", answerText: "0110；1001"},
    {id: 60, type: 'fill', question: "Verilog 中条件运算符的标准语法形式为____。", options: [], answer: "条件 ? 真表达式 : 假表达式", answerText: "条件 ? 真表达式 : 假表达式"},
    {id: 61, type: 'fill', question: "一位全加器的两个输出是___和_及____输出。", options: [], answer: "进位", answerText: "进位"},
    {id: 62, type: 'fill', question: "阅读下列 Verilog 代码: `timescale 10ns/1ns module delay_tb; reg set; parameter d=1.55; initial begin #d set = 0; #d set = 1; end endmodule 根据 timescale 指令定义，时间精度为____，时间单位为____ ，参数 d 对应的 实际延迟时间为____。", options: [], answer: "1ns；10ns；16ns", answerText: "1ns；10ns；16ns"},
    {id: 63, type: 'fill', question: "描述组合逻辑电路的方式有：结构描述、逻辑代数、____和____。", options: [], answer: "真值表；抽象描述；抽象描述、真值表", answerText: "真值表；抽象描述；抽象描述、真值表"},
    {id: 64, type: 'fill', question: "请给出下列程序运行后两个$display 语句输出的值。 class Packet; integer i=l; virtual function integer get; get =i; endfunction endclass class LinkedPacket extends Packet; integer I =2; function LinkedPacket get; get = -I; endfunction endclass LinkedPacket lp = new; Packet p= lp; $display(\"%0d\" ,p.i); $display(\"%0d\",p.get); 第一个$display 给出的值为______ ；第二个$display 给出的值为 ______ 。", options: [], answer: "1；-2", answerText: "1；-2"},
    {id: 65, type: 'fill', question: "请阅读以下代码，给出程序运行后 b 和 c 的输出结果。 module shift_tb; reg [5:0] a, b, c, d; reg [7:0] e; initial begin a = 6'b101011; b = a >> 3; c = a << 7; $display(\"%b\", b); $display(\"%b\", c); end endmodule 程序执行后，b 的输出结果为______ ；c 的输出结果为_____。", options: [], answer: "6'b000101；6'b000000", answerText: "6'b000101；6'b000000"},
    {id: 66, type: 'fill', question: "一位全加器的两个输出是___及___输出。", options: [], answer: "和；进位", answerText: "和；进位"},
    {id: 67, type: 'fill', question: "语句 and A1(out,in1,in2)，该与门中______是输入信号，______是输出信 号。", options: [], answer: "in1;in2；out", answerText: "in1;in2；out"},
    {id: 68, type: 'fill', question: "阅读下列 Verilog 代码: `timescale 10ns/1ns module delay_tb; reg set; parameter d=1.55; initial begin #d set = 0; #d set = 1; end endmodule 根据 timescale 指令定义，时间精度为______，时间单位为______ ，参数 d 对应的实际延迟时间为______。", options: [], answer: "1ns；10ns；16ns", answerText: "1ns；10ns；16ns"},
    {id: 69, type: 'fill', question: "显式连续赋值语句必须以____关键字开头，常用于模块内部描述组合逻 辑。", options: [], answer: "assign", answerText: "assign"},
    {id: 70, type: 'fill', question: "连续赋值语句本质属于____逻辑描述，语句会持续监控输入并实时更新输 出。", options: [], answer: "组合", answerText: "组合"},
    {id: 71, type: 'fill', question: "若 always 块敏感列表为@(a or b)，该代码会综合为____逻辑。", options: [], answer: "组合", answerText: "组合"},
    {id: 72, type: 'fill', question: "电平敏感的 always 块若分支条件书写不全，综合后会产生____，引发逻辑 错误。", options: [], answer: "锁存器", answerText: "锁存器"},
    {id: 73, type: 'fill', question: "Verilog 中调用已有模块的操作称为模块____。", options: [], answer: "实例化", answerText: "实例化"},
    {id: 74, type: 'fill', question: "调用模块的语法格式:模块名 <参数值列表> 实例名(____);", options: [], answer: "端口名列表", answerText: "端口名列表"},
    {id: 75, type: 'fill', question: "语句 and g1(y,a,b,c); 表示该与门有____个输入信号。", options: [], answer: "3", answerText: "3"},
    {id: 76, type: 'fill', question: "数据流建模、行为级建模、____建模，是描述组合逻辑的三大主流方式。", options: [], answer: "结构化(门级)", answerText: "结构化(门级)"},
    {id: 77, type: 'fill', question: "当控制端 T=0 时，时钟有效沿到来后，T 触发器的状态____。", options: [], answer: "保持不变", answerText: "保持不变"},
    {id: 78, type: 'fill', question: "若 T 触发器初始状态 Q=0，T=1，连续输入 2 个时钟脉冲后，输出 Q=____。", options: [], answer: "0", answerText: "0"},
    {id: 79, type: 'fill', question: "____编码的相邻状态之间仅有 1 位电平发生翻转，能有效降低电路毛刺与 功耗。", options: [], answer: "格雷", answerText: "格雷"},
    {id: 80, type: 'fill', question: "独热(One Hot)编码实现 N 个状态，需要____个寄存器。", options: [], answer: "N", answerText: "N"},
    {id: 81, type: 'fill', question: "状态数少、追求高速与简易译码，一般选择____编码。", options: [], answer: "独热(One Hot)", answerText: "独热(One Hot)"},
    {id: 82, type: 'fill', question: "仿真时间单位与精度必须使用____命令声明，避免仿真出错。", options: [], answer: "`timescale", answerText: "`timescale"},
    {id: 83, type: 'fill', question: "函数(function)必须具备至少一个____端口。", options: [], answer: "输入", answerText: "输入"},
    {id: 84, type: 'fill', question: "____内部可以包含时序延迟(#、@)，而____内部不允许出现任何延迟。(任 务/函数)", options: [], answer: "任务；函数", answerText: "任务；函数"},
    {id: 85, type: 'fill', question: "产生 50% 占空比时钟的核心语句:always #半周期 时钟变量 = ____;", options: [], answer: "~ 时钟变量", answerText: "~ 时钟变量"},
    {id: 86, type: 'fill', question: "三延时格式除上升、下降延时外，还额外定义了____状态的延时", options: [], answer: "截止(高阻)", answerText: "截止(高阻)"},
    {id: 87, type: 'fill', question: "FIFO 没有外部地址线，读写地址由内部____自动产生。", options: [], answer: "指针", answerText: "指针"},
    {id: 88, type: 'fill', question: "initial 语句的核心用途是仿真初始化、赋值初值和产生____。", options: [], answer: "测试激励", answerText: "测试激励"},
    {id: 89, type: 'fill', question: "只能完成纯组合运算、无延时、必须有返回值的子程序是____。", options: [], answer: "函数(function)", answerText: "函数(function)"},
    {id: 90, type: 'fill', question: "判断两个数值严格相等(包含 x、z 状态)的操作符是____。", options: [], answer: "===(全等)", answerText: "===(全等)"},
    {id: 91, type: 'fill', question: "数据流建模的抽象层级介于____建模和门级建模之间。", options: [], answer: "行为级", answerText: "行为级"},
    {id: 92, type: 'judge', question: "采用过程语句对组合电路进行描述时，需要对全部的输入信号列入敏感事件 列表", options: [], answer: "正确", answerText: ""},
    {id: 93, type: 'judge', question: "4’b10111011 等价于 4’b1011", options: [], answer: "正确", answerText: ""},
    {id: 94, type: 'judge', question: "在 VerilogHDL 的整数及其表示格式中，可以用二进制、八进制、十进制和 十六进制灯数制表示，其中位宽仅表示的是二进制数的位宽", options: [], answer: "正确", answerText: ""},
    {id: 95, type: 'judge', question: "reg 型是数据储存单元的抽象类型，其对应硬件电路元件具有状态保持作 用，能够存储数据如触发器、锁存器等。", options: [], answer: "正确", answerText: ""},
    {id: 96, type: 'judge', question: "寄存器变量 a、b 的值分别为 4’b1010 和 4’b0000，则!a=1， !b=1，a &&b=0; a || b=1;", options: [], answer: "错误", answerText: ""},
    {id: 97, type: 'judge', question: "A=8’b11010001，则 A>>4 的结果是 48‘b00001001;而 A<<4 的结果是 4=8'b00010000", options: [], answer: "错误", answerText: ""},
    {id: 98, type: 'judge', question: "assign out=?a:b; 若 sel 为 0， 则 out=a;若 sel 为 1，则 out=b。", options: [], answer: "正确", answerText: ""},
    {id: 99, type: 'judge', question: "在 Verilog HDL 程序设计中，功能描述是在电路上相当于器件的内部电路结 构。", options: [], answer: "正确", answerText: ""},
    {id: 100, type: 'judge', question: "串行语句块采用关键字“begin”和“end”，其中的语句按串行方式顺序执 行，不可以用于可综合电路程序和仿真测试程序。", options: [], answer: "错误", answerText: ""},
    {id: 101, type: 'judge', question: "串行语句块中每条语句给出的延时都是相对于前一条语句执行结束的相对 时间，其串行语句块的结束时间与块中最后一条语句执行结束时间无关。", options: [], answer: "错误", answerText: ""},
    {id: 102, type: 'judge', question: "fork - join 块内语句同时且并行执行。", options: [], answer: "正确", answerText: ""},
    {id: 103, type: 'judge', question: "在使用 case 语句时，应包含所有状态，如果没包含全，那么缺省项必须 写，否则将产生锁存器。", options: [], answer: "正确", answerText: ""},
    {id: 104, type: 'judge', question: "在 Verilog HDL 中，模块可以被任何其它模块调用，这种调用实际上是将 模块所描述的电路复制并连接的。", options: [], answer: "正确", answerText: ""},
    {id: 105, type: 'judge', question: "实例中端口的次序与模块定义的次序不同。", options: [], answer: "错误", answerText: ""},
    {id: 106, type: 'judge', question: "模块实例化与调用程序相同。每个实例都是模块的一个完全的拷贝，相互 独立、并行。", options: [], answer: "错误", answerText: ""},
    {id: 107, type: 'judge', question: "对一个 wire 类型的信号使用多条 assign 语句进行赋值，综合工具会报告 多驱动冲突错误。", options: [], answer: "正确", answerText: ""},
    {id: 108, type: 'judge', question: "initial 和 always 块是测试模块中常用的过程块，initial 块和 always 块都 只执行一次。", options: [], answer: "错误", answerText: ""},
    {id: 109, type: 'judge', question: "在四值逻辑(0、1、X、Z)​ 中，逻辑电平 0 和 1 并不对应某一个精确的电 压值，而对应一个电压范围。", options: [], answer: "正确", answerText: ""},
    {id: 110, type: 'judge', question: "任务(task)和函数(function)都可以包含时序控制语句。", options: [], answer: "错误", answerText: ""},
    {id: 111, type: 'judge', question: "对于语句 notif1 #(10,20) U2(out,in,ctrl)，其上升延时为 20 个时间单位。", options: [], answer: "错误", answerText: ""},
    {id: 112, type: 'judge', question: "Testbench 是一个测试平台，信号集成在模块内部，没有输入输出。", options: [], answer: "正确", answerText: ""},
    {id: 113, type: 'judge', question: "测试模块中常用的过程块有 initial 和 always 过程块，对于 initial 过程块 来说，只执行一次。always 过程块只要符合触发条件，就可以循环执行。", options: [], answer: "正确", answerText: ""},
    {id: 114, type: 'judge', question: "分频器是使得单位时间内脉冲次数减少的电路。", options: [], answer: "正确", answerText: ""},
    {id: 115, type: 'judge', question: "优先编码器不允许多个输入信号同时有效。", options: [], answer: "错误", answerText: ""},
    {id: 116, type: 'judge', question: "$finish(n)，当 n=2 时，仅给出仿真时间和位置。", options: [], answer: "错误", answerText: ""},
    {id: 117, type: 'judge', question: "超前进位加法器是一种高速加法器，每级进位由附加的组合电路产生，高 位运算不需等待低位运算完成，因此可提高运算速度。", options: [], answer: "正确", answerText: ""},
    {id: 118, type: 'judge', question: "数据比较器是用来对两个二进制数的大小进行比较，或检测是否相等的逻 辑电路。", options: [], answer: "正确", answerText: ""},
    {id: 119, type: 'judge', question: "数据比较器包含两个部分:一是比较两个数的大小;二是检测两个数是否一 致。", options: [], answer: "正确", answerText: ""},
    {id: 120, type: 'judge', question: "对于 3 位二进制 8-3 线编码器来说，任何时刻允许同时出现两个或两个 以上的有效信号。", options: [], answer: "错误", answerText: ""},
    {id: 121, type: 'judge', question: "优先编码器允许多个输入信号同时有效:但它只按其中优先级别最高的有效 输入信号编码，对级别低输入信号不予理睬。", options: [], answer: "正确", answerText: ""},
    {id: 122, type: 'judge', question: "译码器也称最小项发生器。", options: [], answer: "正确", answerText: ""},
    {id: 123, type: 'judge', question: "奇偶校验既能检测部分传输错误，也能进行错误校正。", options: [], answer: "错误", answerText: ""},
    {id: 124, type: 'judge', question: "阻塞赋值语句中，前一条语句未完成则后一条无法执行。", options: [], answer: "正确", answerText: ""},
    {id: 125, type: 'judge', question: "组合电路的特点是:电路中任意时刻的稳态输出仅仅取决于该时刻的输入， 而与电路原来的状态无关。", options: [], answer: "正确", answerText: ""},
    {id: 126, type: 'judge', question: "相较于 VHDL，Verilog HDL 具备开关级电路的描述能力，这是两者的重 要区别之一。", options: [], answer: "正确", answerText: ""},
    {id: 127, type: 'judge', question: "相等运算符 == 可以正确判断 x、z 不定态和高阻态是否相等。", options: [], answer: "错误", answerText: ""},
    {id: 128, type: 'judge', question: "parameter 参数可以在模块实例化时重新修改赋值。", options: [], answer: "正确", answerText: ""},
    {id: 129, type: 'judge', question: "对同一 wire 信号多次使用 assign 赋值，不会产生逻辑冲突。", options: [], answer: "错误", answerText: ""},
    {id: 130, type: 'judge', question: "Testbench 需要定义输入输出端口，和设计模块格式一致。", options: [], answer: "错误", answerText: ""},
    {id: 131, type: 'judge', question: "FIFO 无需外部地址信号，内部自动生成读写地址指针。", options: [], answer: "正确", answerText: ""},
    {id: 132, type: 'judge', question: "算术运算中，存在未知态 x 参与运算时，运算结果一定为 x。", options: [], answer: "正确", answerText: ""},
    {id: 133, type: 'judge', question: "归约运算是对总线所有位运算，最终输出 1 位逻辑结果。", options: [], answer: "正确", answerText: ""},
    {id: 134, type: 'judge', question: "函数(function)内部可以使用#延时、@敏感触发等时序语句。", options: [], answer: "错误", answerText: ""},
    {id: 135, type: 'judge', question: "模块端口位置关联实例化，允许随意调换端口顺序。", options: [], answer: "错误", answerText: ""},
    {id: 136, type: 'judge', question: "多输入门电路的端口列表中，输入端口在前，输出端口在后。", options: [], answer: "错误", answerText: ""},
    {id: 137, type: 'judge', question: "建立时间是时钟沿之后数据保持稳定的最小时间。", options: [], answer: "错误", answerText: ""},
    {id: 138, type: 'judge', question: "case 语句如果不写 default 分支，组合逻辑中会综合出锁存器。", options: [], answer: "正确", answerText: ""},
    {id: 139, type: 'judge', question: "fork-join 语句块可以被综合成实际硬件电路。", options: [], answer: "错误", answerText: ""},
    {id: 140, type: 'judge', question: "8421BCD 码有效取值范围是 0000~1001，其余为非法码。", options: [], answer: "正确", answerText: ""},
    {id: 141, type: 'essay', question: "在传统 Verilog 模块例化过程中，存在哪些常见设计问题？为什么说引入 interface 语法能有效改善这些问题？", options: [], answer: "", answerText: "元件例化语句不标出信号是作为输入还是输出信号;相关模块的例化代码可\n能隔了很远;模块接口部分的代码在语法上有可改进地方;不同模块可能复用一部\n分接口;添加一个接口，需要修改多处代码；interface 将分散、冗余、易错的端\n口连接，转变为集中、复用、清晰的接口封装，能够有效改善上述问题。"},
    {id: 142, type: 'essay', question: "简述 begin-end 语句块和 fork-join 语句块的区别。", options: [], answer: "", answerText: "串行语句块采用的是关键字“begin\"和\"end\"，其中的语句按串行方式顺序执\n行，可用于可综合电路程序和仿真测试程序。并行语句块采用的是关键字”\nfork\"和“join\"，其中的语句按并行方式执行，只能用于仿真测试程序，不能用\n于可综合电路程序。"},
    {id: 143, type: 'essay', question: "阅读以下 Verilog 代码，回答后面的问题。 module comp_11( count, clk, rst ); output [3:0] count; input clk,rst; reg [3:0] count; always @ (posedge clk) if (rst) count<=4'b0000: else if (count==4'b 1010) count<=4'b0000 else count<=count+1; endmodule （1）上述代码使用的是反馈清零法还是反馈置数法实现的计数器？并指出其清 零方式。 （2）请仿照上图中代码给出 16 进制计数器的 always 语句。", options: [], answer: "", answerText: "（1）反馈清零法。同步清零 D 触发器，清零信号检测仅在时钟上升沿进\n行。\n（2）always @(posedge clk) begin\nif (rst)\ncount <= 4'b0000;\nelse\ncount <= count + 1;\nend"},
    {id: 144, type: 'essay', question: "简述数据流建模的特点", options: [], answer: "", answerText: "以数据如何流动、运算、传递为核心，只关心数据怎么运算、组合、传\n输，不写硬件门电路，也不用 always 时序/条件判断，抽象层级介于行为级\n和门级中间。"},
    {id: 145, type: 'essay', question: "什么是 FIFO？同步 FIFO 和异步 FIFO 分别适用于什么场景？", options: [], answer: "", answerText: "FIFO 即先进先出缓存器，无外部地址线，读写地址由内部指针自动生成；\n同步 FIFO：读写使用同一时钟，结构简单，适用于同时钟域数据缓存；\n异步 FIFO：读写使用不同时钟，主要用于跨时钟域的数据传输。"},
    {id: 146, type: 'essay', question: "对以下代码进行补全 4 选 1 数据选择器： module mux4_1(out,in0,in1,in2,in3,sel); output out; input in0,in1,in2,in3; input[1:0] sel; reg out; //被赋值信号定义为“reg”类型 ______@( in0 or in1 or in2 or in3 or sel) //敏感信号列表 case(____) 2'b00: out=in0; 2'b01: out=in1; 2'b10: out=in2; 2'b11: out=in3; ______ : out=2'bx; endcase endmodule", options: [], answer: "", answerText: "always ，sel， default"},
];