// 语音识别题库（第1-7章 + 第11-13章）
const questionsSpeech = [

    // ── 第1章 语音识别概论 ──
    {id: 1, type: 'single', question: "语音的标准定义是（）", options: ["语言的物质外壳、声学表现形式", "文字的书面载体", "人说话包含的语义内容", "声音的频谱特征"], answer: "A", answerText: "语音是语言的物质外壳，即语言的声学表现形式。"},
    {id: 2, type: 'single', question: "基音周期 T 与基频 F0 的数学关系为（）", options: ["F0=T", "F0=1/T", "F0=T2", "F0=T/2"], answer: "B", answerText: "基音周期的倒数为基频，公式 F0=1/T，基频区间 70~450Hz。"},
    {id: 3, type: 'single', question: "人类发声三大模块中，唇、齿、舌、面颊属于哪一类结构，核心作用是（）", options: ["谐振腔，提供发声气流", "振动源，产生基频振动", "调音器官，改变声道形状调整共振峰", "能量源，控制呼吸气流大小"], answer: "C", answerText: "调音器官：包括唇､齿､舌､面颊等，控制谐振腔形状。"},
    {id: 4, type: 'single', question: "从最小语音单元逐级组合，正确层级顺序是（）", options: ["音节→音素→词语", "音素→音节→词语", "声母→音素→音节", "韵母→音节→音素"], answer: "B", answerText: "音素是最小语音单位；一个或多个音素按规律组合为音节。"},
    {id: 5, type: 'single', question: "下列关于浊音、清音激励源描述正确的是（）", options: ["清音声带周期性振动，浊音无振动", "浊音为准周期冲击序列，清音为随机噪声", "二者激励源均为随机噪声，仅声道不同", "二者均依靠声带振动发声"], answer: "B", answerText: "课本图 1-2 产生语音的激励模型。"},
    {id: 6, type: 'single', question: "正常人耳能够感知的完整声音频率区间是（）", options: ["70~450Hz", "3400Hz", "1kHz~10kHz", "20Hz~20kHz"], answer: "D", answerText: "正常人耳感知的频率范围：20Hz~20kHz。"},
    {id: 7, type: 'single', question: "贝叶斯识别公式中 P(W)语言模型主要解决的问题是（）", options: ["不同人群、语速带来的发音波形差异", "汉语同音词语义歧义，约束语句通顺程度", "语音时域波形振幅计算", "提取语音时域声学特征"], answer: "B", answerText: "语言模型 P(W)解决“说什么不确定”，汉语同音词极多，过滤语义不通的候选。"},
    {id: 8, type: 'single', question: "完整传统流水线语音识别系统中，解码器的输入不包含以下哪一项（）", options: ["声学模型输出概率", "语言模型输出概率", "语音原始时域波形", "发音词典"], answer: "C", answerText: "课本第 6 页主流的语音识别系统框架图中，原始语音先经过特征提取模块生成特征序列，再送入解码器；解码器输入为提取后的声学特征、声学模型、语言模型、发音词典，原始波形不会直接送入解码器。"},
    {id: 9, type: 'single', question: "关于 DTW 动态时间规整算法的局限描述，正确的是（）", options: ["适配多人连续长对话语音识别", "识别效果高度依赖语音端点检测，仅适合小词汇孤立词", "内置神经网络自动提取语音深层特征", "2012 年提出，是深度学习第一代声学模型"], answer: "B", answerText: "DTW 的识别效果过分依赖于端点检测，不适合用于连续语音识别，非常适合用于小词汇量孤立词语音识别系统。"},
    {id: 10, type: 'single', question: "不属于当前国内语音识别核心落地痛点的是（）", options: ["远场噪声鲁棒性差", "方言标注语料稀缺", "安静室内识别低于 60%", "中英混杂识别效果差"], answer: "C", answerText: "安静环境识别准确率可达 95% 以上；复杂场景、低资源、语种混杂为挑战。"},
    {id: 11, type: 'fill', question: "调整声道形状，会改变前五个____，进而改变元音音色。", options: [], answer: "共振峰", answerText: "共振峰的位置、带宽和幅度决定元音音色，改变声道形状可改变共振峰，改变音色。"},
    {id: 12, type: 'fill', question: "浊音基频 F0=250Hz，对应基音周期 T 为____。", options: [], answer: "0.004s", answerText: "公式 F0=1/T，代入可得 T=1/250=0.004s。"},
    {id: 13, type: 'fill', question: "在人类语音产生的激励模型中，语音信号可表示为 x(n)=e(n)*h(n)，其中 e(n)表示____，h(n)表示____；当发浊音时，e(n)通常为____，而发清音时，e(n)通常为____。", options: [], answer: "激励源；声道模型；准周期冲击序列；随机噪声", answerText: "课本图 1-2 明确 e(n)是声源激励、h(n)代表声道滤波模块。此外，浊音依靠声带周期性振动产生规律冲击激励，清音声带松弛无振动，气流摩擦生成无规律随机噪声，二者 e(n)形式存在本质区别。"},
    {id: 14, type: 'fill', question: "人耳结构包括外耳、中耳和____三部分。", options: [], answer: "内耳", answerText: "课本第 2 页图 1-3。"},
    {id: 15, type: 'fill', question: "普通话拼音系统包含 27 个声母、____个不带声调韵母。", options: [], answer: "38", answerText: "课本表 1-1 普通话的声母和韵母（不带声调）分类表。"},
    {id: 16, type: 'fill', question: "语音识别贝叶斯化简公式中，与发音匹配相关概率项是____。", options: [], answer: "P(O|W)", answerText: "第一项 P(O|W)由声学模型决定。"},
    {id: 17, type: 'fill', question: "传统流水线语音识别系统，连接特征序列与两大模型的核心模块是____。", options: [], answer: "解码器", answerText: "课本第 6 页图 1-6。"},
    {id: 18, type: 'fill', question: "2009 年 Hinton 团队将____用于 TIMIT 音素识别，开启深度学习语音时代。", options: [], answer: "DNN/深度神经网络", answerText: "课本第 10 页第三阶段时间线整合。"},
    {id: 19, type: 'fill', question: "WER 统计的三类识别错误：替换、____、插入。", options: [], answer: "删除", answerText: "错误形式：Substitution (替换)、Deletion (删除)、Insertion (插入) 。"},
    {id: 20, type: 'fill', question: "衡量中文短句识别汉字误差的指标缩写为____。", options: [], answer: "CER", answerText: "字错误率 Character Error Rate。"},
    {id: 21, type: 'judge', question: "语音的产生是由声带直接产生气流形成的。（）", options: [], answer: "错误", answerText: "气流来自肺，声带只是振动源。"},
    {id: 22, type: 'judge', question: "基频数值越高人声越低沉，成年人基频整体高于儿童群体。（）", options: [], answer: "错误", answerText: "儿童基频更高，该题目逻辑颠倒。"},
    {id: 23, type: 'judge', question: "中耳三块听小骨仅具备放大声压单一功能。（）", options: [], answer: "错误", answerText: "听小骨放大声压、保护内耳、配合调节中耳气压。"},
    {id: 24, type: 'judge', question: "人耳只能感知 1kHz 以上的声音。（）", options: [], answer: "错误", answerText: "人耳感知声音的频率范围是 20Hz–20kHz。"},
    {id: 25, type: 'judge', question: "时域语音波形仅能存储文字信息，无法携带身份、情绪特征。（）", options: [], answer: "错误", answerText: "波形形简意丰，承载身份、语种、情绪信息。"},
    {id: 26, type: 'judge', question: "依靠声学模型能同时解决 “怎么说” 和 “说什么” 两层随机问题。（）", options: [], answer: "错误", answerText: "声学、语言模型分别对应两层不确定性"},
    {id: 27, type: 'judge', question: "语音识别的目标是找到最可能的观测序列。（）", options: [], answer: "错误", answerText: "语音识别的目标是找到最可能的词序列。"},
    {id: 28, type: 'judge', question: "DTW 算法可以解决不同语速语音时序不对齐问题。（）", options: [], answer: "正确", answerText: "DTW 通过时间弯折实现不等长匹配"},
    {id: 29, type: 'judge', question: "口语多轮对话、多人交替插话会降低语音识别准确率。（ ）", options: [], answer: "正确", answerText: "电话、会议多人口语场景识别效果差。"},
    {id: 30, type: 'judge', question: "TIMIT 是美式口音英文专用语音标注数据集。（）", options: [], answer: "正确", answerText: "TIMIT 为经典英文语音库"},
    {id: 31, type: 'essay', question: "结合语音识别双重随机过程，分别说明声学模型 P(O|W)、语言模型 P(W)的作用，解释二者缺一不可的原因。", options: [], answer: "（1）作用：人类发音存在两层随机性：“怎么说不确定”、“说什么不确定”；声\n学模型 P(O|W)匹配语音特征与文字发音，解决“怎么说”的差异，抵消不同人、\n语速、噪声造成发音不同的问题；语言模型 P(W)建模词语通顺概率，解决“说什\n么”的歧义，过滤大量同音不通顺候选。\n（2）原因：语音识别目标是最大化 P(O|W)·P(W)，仅靠声学模型会出现大量同\n音错字，仅靠语言模型无法匹配语音波形，二者必须配合。", answerText: "（1）作用：人类发音存在两层随机性：“怎么说不确定”、“说什么不确定”；声\n学模型 P(O|W)匹配语音特征与文字发音，解决“怎么说”的差异，抵消不同人、\n语速、噪声造成发音不同的问题；语言模型 P(W)建模词语通顺概率，解决“说什\n么”的歧义，过滤大量同音不通顺候选。\n（2）原因：语音识别目标是最大化 P(O|W)·P(W)，仅靠声学模型会出现大量同\n音错字，仅靠语言模型无法匹配语音波形，二者必须配合。"},
    {id: 32, type: 'essay', question: "简述语音识别三大技术阶段，并说明每一代核心模型与核心局限。", options: [], answer: "模板匹配（代表 DTW）：仅支持小词汇孤立词，极度依赖端点检测，无法处理\n连续长语音；\n统计模型（代表 GMM-HMM）：可大规模连续识别，但依赖人工设计声学特征，\n精度后期遇瓶颈；\n深度学习（DNN-HMM、E2E 端到端）：自动提取语音深层特征，但训练需要\n海量标注语音数据。", answerText: "模板匹配（代表 DTW）：仅支持小词汇孤立词，极度依赖端点检测，无法处理\n连续长语音；\n统计模型（代表 GMM-HMM）：可大规模连续识别，但依赖人工设计声学特征，\n精度后期遇瓶颈；\n深度学习（DNN-HMM、E2E 端到端）：自动提取语音深层特征，但训练需要\n海量标注语音数据。"},
    {id: 33, type: 'essay', question: "已知一句话的识别结果如下：\n参考文本（Reference）：I LIKE READING ENGLISH BOOKS\n识别结果（Hypothesis）：I LOVE READING NEW ENGLISH BOOK\n统计替换、删除、插入三类错误数量，并计算 WER。", options: [], answer: "（1）统计参考总词数\n已知 Ref 分词：I, LIKE, READING, ENGLISH, BOOKS，则 NRef=5。\n（2）对齐并统计错误类型\n1）对齐\nRef\nI\nLIKE\nREADING\n#\nENGLISH BOOKS\nHyp\n#\nLOVE\nREADING\nNEW\nENGLISH\nBOOK\n2）错误统计\n I→#：删除错误；\n LIKE→LOVE：替换错误；\n #→NEW：插入错误；\n BOOKS→BOOK：替换错误；\n因此，NDel=1,Nsub=2,NIns=1。\n（3）带入公式计算 WER\n(S+D+I)/NRef =\n(S+D+I)/NRef + (S+D+I)/NRef + (S+D+I)/NRef 1 + 2 + 1\n=\n= 80%\n(S+D+I)/NRef\n5", answerText: "（1）统计参考总词数\n已知 Ref 分词：I, LIKE, READING, ENGLISH, BOOKS，则 NRef=5。\n（2）对齐并统计错误类型\n1）对齐\nRef\nI\nLIKE\nREADING\n#\nENGLISH BOOKS\nHyp\n#\nLOVE\nREADING\nNEW\nENGLISH\nBOOK\n2）错误统计\n I→#：删除错误；\n LIKE→LOVE：替换错误；\n #→NEW：插入错误；\n BOOKS→BOOK：替换错误；\n因此，NDel=1,Nsub=2,NIns=1。\n（3）带入公式计算 WER\n(S+D+I)/NRef =\n(S+D+I)/NRef + (S+D+I)/NRef + (S+D+I)/NRef 1 + 2 + 1\n=\n= 80%\n(S+D+I)/NRef\n5"},

    // ── 第2章 语音信号基础 ──
    {id: 34, type: 'single', question: "声波在空气中属于哪种波（）", options: ["纵波", "横波", "电磁波", "球面波"], answer: "A", answerText: "声波在空气中是一种纵波，振动方向和传播方向一致。"},
    {id: 35, type: 'single', question: "参考标准声压 p0 数值为（）", options: ["2×10-3Pa", "2×10-5Pa", "2×10-6Pa", "2×10-4Pa"], answer: "B", answerText: "参考声压 p0=2×10-5Pa。"},
    {id: 36, type: 'single', question: "动圈麦克风核心缺点是（）", options: ["需供电", "灵敏度低、体积大", "功耗高", "抗干扰差"], answer: "B", answerText: "动圈麦缺点：精度、灵敏度较低，体积大；优点是长线传输稳定。"},
    {id: 37, type: 'single', question: "低阻抗麦克风阻抗标准为（）", options: ["＞1000Ω", "＜500Ω", "＜1000Ω", "2000Ω~3000Ω"], answer: "C", answerText: "阻抗划分：低阻抗＜1000Ω；高阻抗 2000Ω~3000Ω。"},
    {id: 38, type: 'single', question: "多人会议收录环境音最合适指向（）", options: ["超心形", "心形", "全指向", "单指向"], answer: "C", answerText: "全指向 360°同等收音，适合多人、环境氛围采集。"},
    {id: 39, type: 'single', question: "双麦线形阵列一共可生成多少拾音波束（）", options: ["2", "9", "6", "3"], answer: "D", answerText: "双麦阵列 0~180°形成 3 个波束，单波束覆盖 60°。"},
    {id: 40, type: 'single', question: "麦克风阵列波束形成无法实现的功能（）", options: ["声源二维定位", "室内去混响降噪", "多说话人声源分离", "提升音频原始采样率"], answer: "D", answerText: "波束仅做空间信号处理，不能修改采样、量化原始参数。"},
    {id: 41, type: 'single', question: "均匀量化最主要缺陷是（）", options: ["大信号误差大", "小信号信噪比极低", "计算复杂", "存储量大"], answer: "B", answerText: "均匀量化台阶统一，语音小信号多，量化误差大、噪声明显。"},
    {id: 42, type: 'single', question: "A 律 13 折线压缩核心目的是（）", options: ["放大大信号音量", "细化语音小信号量化台阶", "降低音频采样率", "提升立体声分离度"], answer: "B", answerText: "非均匀压扩，弱语音区间分段更细，减小小信号噪声。"},
    {id: 43, type: 'single', question: "不同音频格式互相转换通用中转媒介（）", options: ["MP3 文件", "线性 PCM WAV", "A-law raw", "FLAC"], answer: "B", answerText: "编码转换时，所有格式统一转 PCM WAV 再二次编码。"},
    {id: 44, type: 'fill', question: "声压级计算公式为：SPL = ____，声压级单位为____。", options: [], answer: "20log(p/p₀)；分贝 /dB", answerText: "课本 24 页公式 2-1。"},
    {id: 45, type: 'fill', question: "动圈式麦克风依靠____感应实现声电转换，电容式麦克风属于____感应类型，普通电容麦必须外接____才能工作。", options: [], answer: "电磁；静电；电源", answerText: "2.2 麦克风分类核心原理对比。"},
    {id: 46, type: 'fill', question: "驻极体麦克风分振膜式、____式，手机设备普遍使用后者。", options: [], answer: "背极", answerText: "两类驻极体结构与应用差异。"},
    {id: 47, type: 'fill', question: "麦克风阵列可以实现语音增强、声源定位、____和声源分离等功能。", options: [], answer: "去混响", answerText: "课本 26、27 页麦克风四个功能。"},
    {id: 48, type: 'fill', question: "减小量化噪声两种主流手段：提升____位数、语音场景采用非均匀压扩量化。", options: [], answer: "量化", answerText: "量化噪声解决方案填空。"},
    {id: 49, type: 'fill', question: "采样率不足两倍信号最高频率会产生____失真，又称折叠失真。", options: [], answer: "混叠", answerText: "频谱折叠畸变。"},
    {id: 50, type: 'fill', question: "模数转换完整三大流程依次为____、____、____。", options: [], answer: "采样；量化；编码", answerText: "略。"},
    {id: 51, type: 'fill', question: "一段立体声音频采样率 32kHz，量化精度 16bit，则该音频比特率为____kbps。", options: [], answer: "1024", answerText: "利用公式：比特率 = 采样率 × 量化位数 × 声道数。带入数据得：32000×16×2÷1000=1024kbps，代入音频比特率标准公式完成换算。"},
    {id: 52, type: 'fill', question: "无压缩原始音频编码缩写____，完整中文名称____调制，通用存储后缀为.wav和____。", options: [], answer: "PCM；脉冲编码；raw", answerText: "PCM 编码基础定义与文件后缀。"},
    {id: 53, type: 'fill', question: "WAV 文件底层封装容器格式____，整体分为____与____两大核心模块。", options: [], answer: "RIFF；文件头；数据块", answerText: "2.6 章节 WAV 结构。"},
    {id: 54, type: 'judge', question: "声压的单位是分贝（dB）。（）", options: [], answer: "错误", answerText: "声压单位是 Pa，dB 是声压级单位。"},
    {id: 55, type: 'judge', question: "类居民住宅区白天环境噪声不能超过 55dB。（）", options: [], answer: "正确", answerText: "国内城市噪声管控标准。"},
    {id: 56, type: 'judge', question: "SNR 信噪比数值越低，录音纯净无杂音。（）", options: [], answer: "错误", answerText: "SNR 数值越高，噪声占比越少，人声越清晰。"},
    {id: 57, type: 'judge', question: "高阻抗麦克风长线远距离传输抗干扰更强。（）", options: [], answer: "错误", answerText: "高阻抗线材极易拾取电磁干扰，只适合短距离。"},
    {id: 58, type: 'judge', question: "心形指向麦克风能明显抑制后方、侧面环境杂音。（）", options: [], answer: "正确", answerText: "心形指向只对正前方声源高灵敏。"},
    {id: 59, type: 'judge', question: "灵敏度 - 25dB 的麦克风，拾取微弱环境音能力弱于 - 40dB 款式。（）", options: [], answer: "错误", answerText: "-25dB 数值更大，灵敏度更高，拾取小声更清晰。"},
    {id: 60, type: 'judge', question: "均匀量化对微弱语音信噪比表现优秀。（）", options: [], answer: "错误", answerText: "均匀量化弱信号误差大，噪声明显。"},
    {id: 61, type: 'judge', question: "采样频率等于语音最高频率两倍时不会产生任何失真。（）", options: [], answer: "错误", answerText: "定理要求必须大于 2 倍，等于临界值仍会出现混叠失真。"},
    {id: 62, type: 'judge', question: "MP3 属于无损音频压缩编码。（）", options: [], answer: "错误", answerText: "MP3 是有损压缩，压缩后细节永久丢失。"},
    {id: 63, type: 'judge', question: "标准 WAV 文件只存储音频采样数据，不携带任何头部参数区块。（）", options: [], answer: "错误", answerText: "WAV 包含 RIFF、fmt、data 等头部 Chunk 存储音频参数。"},
    {id: 64, type: 'essay', question: "对比心形、超心形、全指向三类麦克风的指向特性，分别说明适合的场景，并解释户外嘈杂采访优先超心形的底层原因。", options: [], answer: "（1）全指向：360° 灵敏度均等，适合多人圆桌会议、现场环境音录制，无法抑\n制侧后噪声；\n心形：仅正前方灵敏，后侧大幅衰减，适合室内单人录音、演讲；\n超心形（单指向）拾音锥更窄，侧后方声音衰减幅度大于 15dB，降噪能力最强；\n（2）户外环境杂声源多，超心形能最大程度过滤四周背景噪音，只保留目标人\n声，因此外景采访首选。", answerText: "（1）全指向：360° 灵敏度均等，适合多人圆桌会议、现场环境音录制，无法抑\n制侧后噪声；\n心形：仅正前方灵敏，后侧大幅衰减，适合室内单人录音、演讲；\n超心形（单指向）拾音锥更窄，侧后方声音衰减幅度大于 15dB，降噪能力最强；\n（2）户外环境杂声源多，超心形能最大程度过滤四周背景噪音，只保留目标人\n声，因此外景采访首选。"},
    {id: 65, type: 'essay', question: "简述麦克风阵列波束形成四大核心功能，再说明双麦线形阵列与六麦环形阵列波束分布差异，以及智能音箱选用六麦环形的原因。", options: [], answer: "（1）四大功能：语音增强降噪、声源方位定位、消除房间混响、多声源人声分\n离；\n（2）双麦线形阵列 0~180° 仅生成 3 个 60° 波束，只能覆盖半平面； 六麦环\n形均分 360° 圆周，生成 6 个独立 60° 波束，全方位无死角拾取任意角度人声；\n（3）家用音箱用户说话方位不固定，环形阵列全空间覆盖，远场语音识别效果\n优于线形双麦。", answerText: "（1）四大功能：语音增强降噪、声源方位定位、消除房间混响、多声源人声分\n离；\n（2）双麦线形阵列 0~180° 仅生成 3 个 60° 波束，只能覆盖半平面； 六麦环\n形均分 360° 圆周，生成 6 个独立 60° 波束，全方位无死角拾取任意角度人声；\n（3）家用音箱用户说话方位不固定，环形阵列全空间覆盖，远场语音识别效果\n优于线形双麦。"},
    {id: 66, type: 'essay', question: "一段立体声语音音频，采样率 32kHz，量化精度 16bit，录制时长 4 分 30 秒，1MB=1024×1024Byte。要求：①计算该音频比特率（单位 kbps）；②计算音频总比特；③换算文件总存储容量（保留 2 位小数 MB）。", options: [], answer: "（1）比特率公式：比特率 = 采样率 × 量化位数 × 声道数 ÷ 1000\n比特率 = 32000 × 16 × 2 ÷ 1000 = 1024 kbps\n（2）时长换算：4 分 30 秒 = 4×60+30 = 270 s\n总比特 = 1024000 bit/s × 270 s = 276480000 bit\n（3）总字节 = 总比特 ÷ 8 = 276480000 ÷ 8 = 34560000 Byte\n容量 MB = 34560000 ÷ (1024×1024) ≈ 32.96 MB", answerText: "（1）比特率公式：比特率 = 采样率 × 量化位数 × 声道数 ÷ 1000\n比特率 = 32000 × 16 × 2 ÷ 1000 = 1024 kbps\n（2）时长换算：4 分 30 秒 = 4×60+30 = 270 s\n总比特 = 1024000 bit/s × 270 s = 276480000 bit\n（3）总字节 = 总比特 ÷ 8 = 276480000 ÷ 8 = 34560000 Byte\n容量 MB = 34560000 ÷ (1024×1024) ≈ 32.96 MB"},
    {id: 67, type: 'essay', question: "现有两段同一段人声录音，分别采用两种编码存储：素材 1：8kHz、8bit A 律单声道，码率 64kbps；素材 2：16kHz、16bit 线性 PCM 单声道，码率自行计算；两段音频均录制 12 分钟。要求：①计算素材 2 比特率；②分别算出两段音频总字节；③求两种格式存储容量差值（Byte）。", options: [], answer: "（1）素材 2 比特率：16000×16×1÷1000=256 kbps\n（2）时长：12min=720s\n素材 1 每秒字节：64000÷8=800 Byte/s，总字节 = 800×720=576000 Byte\n素材 2 每秒字节：256000÷8=3200 Byte/s，总字节 = 3200×720=2304000 Byte\n（3）容量差值 = 2304000 - 576000 = 1728000 Byte", answerText: "（1）素材 2 比特率：16000×16×1÷1000=256 kbps\n（2）时长：12min=720s\n素材 1 每秒字节：64000÷8=800 Byte/s，总字节 = 800×720=576000 Byte\n素材 2 每秒字节：256000÷8=3200 Byte/s，总字节 = 3200×720=2304000 Byte\n（3）容量差值 = 2304000 - 576000 = 1728000 Byte"},

    // ── 第3章 语音特征提取 ──
    {id: 68, type: 'single', question: "语音预加重标准系数 α 取值为（）", options: ["0.9", "0.97", "1.0", "0.85"], answer: "B", answerText: "预加重公式固定 α=0.97，用于补偿口唇高频衰减。"},
    {id: 69, type: 'single', question: "帧移取值常规为 10ms，其核心作用是（）", options: ["减少总帧数，降低计算量", "帧间重叠，平滑短时特征变化", "扩大单帧有效时长", "提升采样频率"], answer: "B", answerText: "帧间重叠避免帧与帧特征突变，保证时序连续性。"},
    {id: 70, type: 'single', question: "矩形窗带来的主要缺陷是（）", options: ["时域截断引发频谱泄露，旁瓣幅值大", "带宽过窄无法分析低频", "计算复杂度极高", "无法用于 DFT 运算"], answer: "A", answerText: "矩形窗边界突变，频域大量旁瓣，频谱泄露严重。"},
    {id: 71, type: 'single', question: "汉明窗与汉宁窗对比，正确描述是（）", options: ["汉明窗旁瓣抑制更强", "汉宁窗带宽更大", "汉明窗时域两端衰减更快", "二者频谱泄露程度完全一致"], answer: "A", answerText: "汉明窗次旁瓣衰减 40dB，汉宁仅 30dB，语音处理首选汉明窗。"},
    {id: 72, type: 'single', question: "FFT 变换要求窗长 N 满足什么条件（）", options: ["任意整数", "2 的整数次幂", "质数", "偶数即可"], answer: "B", answerText: "基 2FFT 算法约束采样点数为 2n。"},
    {id: 73, type: 'single', question: "语音短时分析的核心理论依据是（）", options: ["语音长期平稳", "短时平稳性", "频率线性", "人耳线性感知"], answer: "B", answerText: "10~30ms 内语音频谱近似不变，为分帧基础。"},
    {id: 74, type: 'single', question: "Mel 滤波器组带宽分布规则为（）", options: ["全频段等宽均匀分布", "低频线性间隔、高频对数间隔", "低频对数、高频线性", "所有三角滤波器带宽完全相等"], answer: "B", answerText: "模拟人耳低频分辨强、高频分辨弱的听觉特性。"},
    {id: 75, type: 'single', question: "Bark 临界频带的核心用途是（）", options: ["模拟频域掩蔽效应，PLP 特征核心基础", "计算 MFCC 倒谱系数", "优化 FFT 运算速度", "消除分帧频谱泄露"], answer: "A", answerText: "Bark 临界频带用于建模听觉掩蔽，是 PLP 特征专属模块。"},
    {id: 76, type: 'single', question: "线性预测（LPC）与倒谱分析核心区别是（）", options: ["LPC 时域建模，倒谱频域同态滤波解卷积", "LPC 用于清音，倒谱用于浊音", "LPC 依赖 FFT，倒谱无需傅里叶变换", "LPC 提取 Mel 特征，倒谱提取 Bark 特征"], answer: "A", answerText: "二者均分离激励与声道，分析域完全不同。"},
    {id: 77, type: 'single', question: "以下哪种特征抗噪声性能最优（）", options: ["原始语谱图", "FBank", "MFCC", "PLP"], answer: "D", answerText: "PLP 融合 Bark 临界频带、等响度曲线，模拟完整人耳听觉，鲁棒性更强。"},
    {id: 78, type: 'fill', question: "语音预处理三大核心步骤依次为____、____、____。", options: [], answer: "预加重；分帧；加窗", answerText: "3.1 节开篇明确预处理三模块，三者顺序不可颠倒。"},
    {id: 79, type: 'fill', question: "预加重通常采用一阶____滤波器来增强高频分量。", options: [], answer: "高通", answerText: "：课本 36 页预加重公式可以看出，该差分运算会提升信号高频部分的幅值，从滤波分类上属于一阶高通滤波器。"},
    {id: 80, type: 'fill', question: "语音处理最优窗函数是____窗。", options: [], answer: "汉明", answerText: "汉明窗旁瓣抑制能力优于汉宁、矩形窗，能大幅减少频谱泄露。"},
    {id: 81, type: 'fill', question: "频率是客观物理量，对应人耳主观感知____；声强对应主观____；波形结构决定声音____。", options: [], answer: "音调；响度；音色", answerText: "听觉三维感知完整对应关系，结合等响度、Mel 曲线配套概念。"},
    {id: 82, type: 'fill', question: "原始 DFT 复杂度为 O(N2)，FFT 优化后复杂度为____。", options: [], answer: "O(Nlog2N)", answerText: "FFT 大幅降低 DFT 复数乘法运算次数。"},
    {id: 83, type: 'fill', question: "STFT 同时保留____维度与时序维度信息，输出二维矩阵称为语谱数据，可视化图像名为____。", options: [], answer: "频率；语谱图", answerText: "语谱图横轴时间、纵轴频率、色彩代表频谱能量大小。"},
    {id: 84, type: 'fill', question: "Mel 滤波器采用____形滤波单元。", options: [], answer: "三角", answerText: "一组不等宽三角滤波器模拟人耳低频分辨精细的特性。"},
    {id: 85, type: 'fill', question: "邻近强声掩盖弱声的听觉现象称为____掩蔽。", options: [], answer: "频域", answerText: "同一频段强声源抬高听觉阈值，掩盖相邻微弱语音信号。"},
    {id: 86, type: 'fill', question: "Bark 临界频带用于建模____掩蔽效应，是____特征独有的预处理模块，MFCC仅使用 Mel 滤波无 Bark 分析。", options: [], answer: "频域；PLP", answerText: "区分 MFCC 与 PLP 听觉模拟差异，Bark 完整模拟耳蜗掩蔽机制。"},
    {id: 87, type: 'fill', question: "MFCC 在 FBank 流程后增加____变换，该操作目的消除特征维度____性。", options: [], answer: "DCT / 离散余弦；相关", answerText: "两类声学特征核心区分步骤，DCT 降低特征冗余适配传统语音模型。"},
    {id: 88, type: 'judge', question: "语音预处理的目的仅为缩小音频文件存储体积。（）", options: [], answer: "错误", answerText: "预处理包含三项独立作用：预加重补偿口唇高频衰减、分帧利用短时平稳实现短时频谱分析、加窗抑制矩形窗带来的频谱泄露，全程没有压缩音频、减小文件大小的作用。"},
    {id: 89, type: 'judge', question: "预加重可以替代前置低通滤波器消除环境低频噪声。（）", options: [], answer: "错误", answerText: "预加重仅均衡语音自身频谱，无法消除外部环境引入的低频干扰噪声。"},
    {id: 90, type: 'judge', question: "未做特殊加权的分帧操作等价于添加矩形窗。（）", options: [], answer: "正确", answerText: "直接截断语音波形无渐变加权，等同于幅值恒为 1 的矩形窗，会带来频谱泄露问题。"},
    {id: 91, type: 'judge', question: "只包含单一频率、无谐波的声音称为纯音。（）", options: [], answer: "正确", answerText: "音叉发声是典型纯音，人类语音不属于纯音。"},
    {id: 92, type: 'judge', question: "人耳刚好能感知微弱声音的临界阈值称为听阈。（）", options: [], answer: "正确", answerText: "安静环境下低于听阈的声音人耳完全无法识别。"},
    {id: 93, type: 'judge', question: "2000~4000Hz 是人耳最灵敏频段。（）", options: [], answer: "正确", answerText: "等响度曲线显示该区间同等声强主观响度最高。"},
    {id: 94, type: 'judge', question: "线性预测分析（LPC）主要用于描述声道特性。（）", options: [], answer: "正确", answerText: "语音是激励信号与声道冲击响应卷积而成，LPC 采用全极点 AR 模型，核心作用分离激励与声道分量，专门拟合、提取声道共振特性。"},
    {id: 95, type: 'judge', question: "倒谱分析先执行 IDFT，再对频谱取对数幅度。（）", options: [], answer: "错误", answerText: "标准倒谱流程：STFT→取对数谱→IDFT，对数是卷积转加法的关键前置操作。"},
    {id: 96, type: 'judge', question: "深度学习更适合使用 FBank 特征。（）", options: [], answer: "正确", answerText: "FBank 保留完整频谱，神经网络可自主学习特征关联。"},
    {id: 97, type: 'judge', question: "MFCC 完整复刻人耳等响度、频域掩蔽全部听觉特性。（）", options: [], answer: "错误", answerText: "MFCC 仅使用简单 Mel 三角滤波，等响度、Bark 掩蔽是 PLP 独有的处理步骤。"},
    {id: 98, type: 'essay', question: "明语音预处理三步（预加重、分帧、加窗）各自作用、存在缺陷与优化方案。", options: [], answer: "预加重：采用一阶高通滤波，补偿口唇辐射造成高频能量衰减；仅均衡语音自身\n频谱，无法消除环境低频噪声。\n分帧：依托语音短时平稳性，按 20ms 帧长、10ms 帧移切分语音，实现短时频\n谱分析；单纯截断等价矩形窗，会产生频谱泄露失真。\n加窗：将矩形窗替换为汉明窗，平滑帧两端波形，大幅抑制频域旁瓣，减少频谱\n泄露；汉明窗代价是主瓣带宽加倍，频率分辨能力轻微下降。\n完整处理流程：原始语音→预加重→重叠分帧→汉明窗加权，再送入 STFT 做\n频谱分析。", answerText: "预加重：采用一阶高通滤波，补偿口唇辐射造成高频能量衰减；仅均衡语音自身\n频谱，无法消除环境低频噪声。\n分帧：依托语音短时平稳性，按 20ms 帧长、10ms 帧移切分语音，实现短时频\n谱分析；单纯截断等价矩形窗，会产生频谱泄露失真。\n加窗：将矩形窗替换为汉明窗，平滑帧两端波形，大幅抑制频域旁瓣，减少频谱\n泄露；汉明窗代价是主瓣带宽加倍，频率分辨能力轻微下降。\n完整处理流程：原始语音→预加重→重叠分帧→汉明窗加权，再送入 STFT 做\n频谱分析。"},
    {id: 99, type: 'essay', question: "简述 MFCC 特征提取的基本步骤。", options: [], answer: "（1）语音信号预处理（预加重、分帧、加窗）（2）进行短时傅里叶变换（STFT）得到频谱（3）通过 Mel 滤波器组进行频率变换（4）对滤波器输出取对数（5）进行离散余弦变换（DCT）得到 MFCC 系数", answerText: "（1）语音信号预处理（预加重、分帧、加窗）（2）进行短时傅里叶变换（STFT）得到频谱（3）通过 Mel 滤波器组进行频率变换（4）对滤波器输出取对数（5）进行离散余弦变换（DCT）得到 MFCC 系数"},
    {id: 100, type: 'essay', question: "Mel 标准计算公式 mel(f)=2595lg10(1+f/700)，分别计算 f=700Hz、f=4000Hz 对应的 Mel 值（结果保留整数）。", options: [], answer: "代入 f=700Hz，得：\nmel=2595lg10(1+700/700)=2595×lg2≈2595×0.3010≈781Mel\n代入 f=4000Hz，得：\nmel=2595lg10(1+400/700)=2595×lg(47/7)≈2595×0.8270≈2146Mel", answerText: "代入 f=700Hz，得：\nmel=2595lg10(1+700/700)=2595×lg2≈2595×0.3010≈781Mel\n代入 f=4000Hz，得：\nmel=2595lg10(1+400/700)=2595×lg(47/7)≈2595×0.8270≈2146Mel"},
    {id: 101, type: 'essay', question: "一帧语音 DFT 变换点数 N=1024，分别计算原始 DFT、基 2 FFT 的运算次数，并求出 FFT 相比 DFT 运算缩减倍数。", options: [], answer: "（1）原始 DFT 复杂度 O(N2)，总运算量：\n1024 × 1024 = 1048576 次\n基 2 FFT 复杂度 O(Nlog2N)，log21024=10，总运算量：\n1024 × 10 = 10240 次\n（2）运算缩减倍数= DFT 运算量 ÷ FFT 运算量\n1048576 ÷ 1024 = 1024 倍", answerText: "（1）原始 DFT 复杂度 O(N2)，总运算量：\n1024 × 1024 = 1048576 次\n基 2 FFT 复杂度 O(Nlog2N)，log21024=10，总运算量：\n1024 × 10 = 10240 次\n（2）运算缩减倍数= DFT 运算量 ÷ FFT 运算量\n1048576 ÷ 1024 = 1024 倍"},

    // ── 第4章 HMM ──
    {id: 102, type: 'single', question: "在语音识别中，HMM 通常用于建模（）", options: ["语言模型", "声学模型", "特征提取", "编码过程"], answer: "B", answerText: "HMM 刻画语音发音双重随机过程，在语音识别中专门构建声学模型。"},
    {id: 103, type: 'single', question: "HMM 双重随机过程中，马尔可夫链建模哪层随机性（）", options: ["同一状态下发音观测差异", "观测符号输出概率", "隐状态时序转移", "环境噪声变化"], answer: "C", answerText: "两层随机：马尔可夫链→状态 / 内容不确定；观测概率矩阵→发音方式不确定。"},
    {id: 104, type: 'single', question: "马尔可夫链核心性质称为（）", options: ["后效性", "无后效性", "全概率性", "贝叶斯性质"], answer: "B", answerText: "马尔可夫链满足无后效性，仅和当前状态相关。"},
    {id: 105, type: 'single', question: "普通马尔可夫链和 HMM 最核心区别是（）", options: ["马尔可夫链状态与观测一一对应；HMM 隐状态不可观测", "马尔可夫链无状态转移概率", "马尔可夫链仅用于天气预测", "HMM 不满足马尔可夫无后效性"], answer: "A", answerText: "普通马尔可夫链状态 = 观察，HMM 状态≠观察。"},
    {id: 106, type: 'single', question: "在 HMM 中，观测概率 bj(k)含义是（）", options: ["从 i 转移到 j 概率", "t 时刻 j 的前向概率", "初始选中 j 概率", "状态 j 输出第 k 种观测符号的概率"], answer: "D", answerText: "B 矩阵：给定隐状态 j，输出观测符号的概率。"},
    {id: 107, type: 'single', question: "在 HMM 中，计算总概率 P(O|λ)，前向算法终止步骤公式为（）Nα ii=1 TNβ ii=1 1", options: ["P=", "P=", "P=max αT i", "P= αt i"], answer: "A", answerText: "所有最后时刻状态前向概率相加得到观测序列总生成概率。"},
    {id: 108, type: 'single', question: "前向 + 后向联合计算 HMM 的 P(O|λ)优势不包括（）", options: ["任意时间步快速计算总概率", "可计算单时刻状态后验概率", "大幅降低存储开销", "避免重复路径计算"], answer: "C", answerText: "联合算法需要同时存储 α、β，存储开销更大，不属于优势。"},
    {id: 109, type: 'single', question: "Viterbi 数组φt(j)的作用是（）", options: ["存储所有路径概率值", "计算总生成概率", "更新观测矩阵 B", "记录 t 时刻状态 j 的最优前驱状态，用于回溯完整最优路径"], answer: "D", answerText: "无φ数组，无法反向读出完整隐状态序列。"},
    {id: 110, type: 'single', question: "Viterbi 算法输出的最大概率路径可近似替代（）", options: ["全部路径概率和 P(O|λ)", "单个状态后向概率", "观测输出概率矩阵", "初始分布 π"], answer: "A", answerText: "最优路径概率占总概率绝大部分，可近似估算 P(O|λ)。"},
    {id: 111, type: 'single', question: "HMM 训练模型参数依靠的算法是（）", options: ["Baum-Welch", "前向算法", "后向算法", "DTW"], answer: "A", answerText: "Baum-Welch 基于 EM 实现 HMM 参数迭代训练。"},
    {id: 112, type: 'fill', question: "以随机过程、条件概率为基础，隐马尔可夫是典型的____模型。", options: [], answer: "概率统计", answerText: "其理论诞生于概率统计领域，依靠概率计算完成推理与训练。"},
    {id: 113, type: 'fill', question: "HMM 中，状态是____的，而观测是____的。", options: [], answer: "隐含/不可观测/不可见的；可见", answerText: "HMM 的核心特点为隐状态无法直接观察，观测序列能够直接获取。"},
    {id: 114, type: 'fill', question: "HMM 五元组参数中，代表观测概率矩阵的符号是____。", options: [], answer: "B", answerText: "HMM 参数定义：N 状态数、M 观测数、π 初始、A 转移、B 观测输出矩阵。"},
    {id: 115, type: 'fill', question: "HMM 三大基础问题分别为____、最佳路径问题、____，对应算法依次为前向- 后向、Viterbi、Baum-Welch。", options: [], answer: "模型评估问题；模型训练问题", answerText: "4.2 章节总纲三大问题，构成训练 - 评估 - 解码完整闭环。"},
    {id: 116, type: 'fill', question: "穷举法计算 P(O|λ)最大缺陷是存在大量____运算。", options: [], answer: "重复路径", answerText: "多条路径共用中间片段，暴力枚举重复计算，复杂度指数爆炸。"},
    {id: 117, type: 'fill', question: "HMM 训练阶段迭代终止判定依据是 P(O|λ)数值趋于____。", options: [], answer: "稳定收敛", answerText: "持续更新参数直至观测似然不再明显上升，停止迭代。"},
    {id: 118, type: 'fill', question: "后向算法初始化时，所有时刻 T 的后向变量βT(i)统一赋值为____。", options: [], answer: "1", answerText: "后向算法初始化规则标准公式βT(i)=1。"},
    {id: 119, type: 'fill', question: "求解 HMM 最佳隐状态路径的动态规划算法名称为____。", options: [], answer: "Viterbi/维特比", answerText: "PPT 明确最佳路径对应维特比算法。"},
    {id: 120, type: 'fill', question: "Viterbi 递推公式中对前驱状态概率取____运算，而非求和。", options: [], answer: "max /最大值", answerText: "Viterbi 核心操作为取最大。"},
    {id: 121, type: 'fill', question: "Baum-Welch 算法的底层理论框架为____算法。", options: [], answer: "EM/期望最大化", answerText: "B-W 分为 E 求期望、M 最大化两步，依托 EM 理论。"},
    {id: 122, type: 'judge', question: "HMM 完整参数包含 N、M、π、A、B 五个核心要素。（）", options: [], answer: "正确", answerText: "分别代表状态数、观测数、初始、转移、观测矩阵。"},
    {id: 123, type: 'judge', question: "马尔可夫过程只有时间离散、状态离散这一种形式。（）", options: [], answer: "错误", answerText: "分为四类，马尔可夫链只是其中离散组合的一种。"},
    {id: 124, type: 'judge', question: "马尔可夫链的无后效性代表未来状态会受全部历史状态共同影响。（）", options: [], answer: "错误", answerText: "无后效性仅依赖当前状态，与过往状态无关。"},
    {id: 125, type: 'judge', question: "马尔可夫链用于刻画相同文字下语速、音量的随机变化。（）", options: [], answer: "错误", answerText: "语速这类观测随机由 B 矩阵刻画，马尔可夫链负责内容状态跳转。"},
    {id: 126, type: 'judge', question: "穷举法计算观测概率适合长时序观测序列使用。（）", options: [], answer: "错误", answerText: "序列越长路径数量指数暴涨，计算开销无法承受。"},
    {id: 127, type: 'judge', question: "前向算法最终将最后一刻所有状态的前向概率相加，得到观测总概率。（）", options: [], answer: "正确", answerText: "全部末尾状态概率求和是前向算法最终计算步骤。"},
    {id: 128, type: 'judge', question: "仅单独运行前向算法，无法算出任意时刻状态后验概率γt(i)。（）", options: [], answer: "正确", answerText: "计算 γ 必须同时拥有前向 α、后向 β 两组变量。"},
    {id: 129, type: 'judge', question: "HMM 语音识别解码阶段，核心使用 Viterbi 算法完成识别输出。（）", options: [], answer: "正确", answerText: "通过最优状态链将声学特征转换为音素、文字。"},
    {id: 130, type: 'judge', question: "Viterbi 与前向算法都属于动态规划类算法。（）", options: [], answer: "正确", answerText: "二者都通过分步保存中间结果，避免重复计算。"},
    {id: 131, type: 'judge', question: "Baum-Welch 迭代流程固定为先执行 E 步，再执行 M 步。（）", options: [], answer: "正确", answerText: "循环交替计算期望、更新参数直至收敛。"},
    {id: 132, type: 'essay', question: "简述 HMM 的双重随机过程分别指什么？", options: [], answer: "一重是马尔可夫链刻画的状态转移的随机性；二重是依存于状态的观察事件的随\n机性。", answerText: "一重是马尔可夫链刻画的状态转移的随机性；二重是依存于状态的观察事件的随\n机性。"},
    {id: 133, type: 'essay', question: "简述 HMM 三大基础问题、对应算法，以及三者在语音识别中的作用。", options: [], answer: "（1）模型评估问题：给定模型与观测序列，计算 P(O|λ)；使用前向 - 后向算法；\n作用：量化模型匹配语音的程度，检验训练好的声学模型优劣。\n（2）最佳路径问题：给定模型与观测，求解概率最大的隐状态序列；使用 Viterbi\n算法；作用：语音识别核心解码步骤，从声学特征反推音素 / 文字序列。\n（3）模型训练问题：仅依靠观测数据，学习最优π、A、B 参数；使用 Baum-Welch\n算法（EM 框架）；作用：无标注语音数据下，迭代训练得到声学模型。\n完整流程：先用 Baum-Welch 训练模型，再用前向算法评估模型好坏，最后用\nViterbi 完成语音识别解码。", answerText: "（1）模型评估问题：给定模型与观测序列，计算 P(O|λ)；使用前向 - 后向算法；\n作用：量化模型匹配语音的程度，检验训练好的声学模型优劣。\n（2）最佳路径问题：给定模型与观测，求解概率最大的隐状态序列；使用 Viterbi\n算法；作用：语音识别核心解码步骤，从声学特征反推音素 / 文字序列。\n（3）模型训练问题：仅依靠观测数据，学习最优π、A、B 参数；使用 Baum-Welch\n算法（EM 框架）；作用：无标注语音数据下，迭代训练得到声学模型。\n完整流程：先用 Baum-Welch 训练模型，再用前向算法评估模型好坏，最后用\nViterbi 完成语音识别解码。"},
    {id: 134, type: 'essay', question: "已知 HMM 如下图。隐状态 S1、S2，初始概率π=[1,0]。若观测序列为 O={AB}，使用前向算法分步计算每一步αt ，画出格型图，并求 P(O|λ)。", options: [], answer: "（1）t=1，观测O1 = O，公式：O1 O = OO OO O ：\nO1 O1 = O1 O1 O = 1 × 0.2 = 0.2\nO1 O2 = O2 O2 O = 0 × 0.6 = 0\nt=2，观测O2 = O，公式：O2 O =\n2\nO O OOO OO O ：\nO=1 1\nO2 O1 = [O1 O1 O11 + O1 O2 O21 ]O1 O = (0.2 × 0.4 + 0 × 0) × 0.8 = 0.064\nO2 O2 = [O1 O1 O12 + O1 O2 O22 ]O2 O = (0.2 × 0.6 + 0 × 0.9) × 0.4 = 0.048\n（2）格型图：\n（3）总概率，公式：\nO O O = O2 O1 +O2 O2 = 0.064 + 0.048 = 0.112", answerText: "（1）t=1，观测O1 = O，公式：O1 O = OO OO O ：\nO1 O1 = O1 O1 O = 1 × 0.2 = 0.2\nO1 O2 = O2 O2 O = 0 × 0.6 = 0\nt=2，观测O2 = O，公式：O2 O =\n2\nO O OOO OO O ：\nO=1 1\nO2 O1 = [O1 O1 O11 + O1 O2 O21 ]O1 O = (0.2 × 0.4 + 0 × 0) × 0.8 = 0.064\nO2 O2 = [O1 O1 O12 + O1 O2 O22 ]O2 O = (0.2 × 0.6 + 0 × 0.9) × 0.4 = 0.048\n（2）格型图：\n（3）总概率，公式：\nO O O = O2 O1 +O2 O2 = 0.064 + 0.048 = 0.112"},

    // ── 第5章 GMM-HMM ──
    {id: 135, type: 'single', question: "高斯混合模型（GMM）用于建模的是（）", options: ["状态转移概率", "观测概率分布", "初始状态概率", "词序列概率"], answer: "B", answerText: "GMM-HMM 中每个隐状态的观测概率由 GMM 拟合，因此 GMM 负责建模观测概率分布。"},
    {id: 136, type: 'single', question: "GMM 中，每个高斯分量通常由（）三个参数决定。", options: ["均值、方差、权重", "均值、频率、权重", "方差、频率、概率", "均值、能量、学习率"], answer: "A", answerText: "GMM 完整参数包含混合权重、各高斯分量均值、方差 ，对应选项均值、方差、权重。"},
    {id: 137, type: 'single', question: "GMM 可以看作对复杂分布的（）", options: ["离散表示", "线性变换", "加权近似", "随机采样"], answer: "C", answerText: "GMM 通过多个单高斯加权叠加，近似拟合任意复杂连续分布，属于加权近似。"},
    {id: 138, type: 'single', question: "GMM 权重系数 ck 必须满足（）约束条件。", options: ["ck > 1", "ck < 0", "Σck = 1", "Σck = 0"], answer: "C", answerText: "GMM 定义：所有权重之和等于 1，权重代表各高斯分量的混合占比。"},
    {id: 139, type: 'single', question: "用于 GMM 初始化聚类的经典算法是（）", options: ["ck > 1", "ck < 0", "Σck = 1", "Σck = 0"], answer: "C", answerText: "GMM 采用 K-means 算法初始化各高斯的参数。"},
    {id: 140, type: 'single', question: "半连续 GMM-HMM 与连续 GMM-HMM 核心区别是（）", options: ["半连续每个状态独立 GMM", "半连续所有状态共享同一组高斯混合分量", "半连续观测是离散符号", "半连续无状态转移"], answer: "B", answerText: "连续 HMM 每个状态独立 GMM；半连续 HMM 全部状态共享一套高斯。"},
    {id: 141, type: 'single', question: "某连续语音 GMM-HMM 每个状态配置 4 个高斯混合分量，若 HMM 共 3个发射状态，则整套模型高斯总数为（）", options: ["3", "4", "7", "12"], answer: "D", answerText: "3 状态 ×4 高斯 / 状态 = 12 个高斯分量。"},
    {id: 142, type: 'single', question: "在 GMM-HMM 中，Viterbi 重估计属于哪种判决方式（）", options: ["软判决", "硬判决", "贝叶斯判决", "最大后验判决"], answer: "B", answerText: "Viterb 重估计是硬判决，每个观测值仅对应唯一状态；Baum-Welch 是软判决。"},
    {id: 143, type: 'single', question: "MLLR 和 MAP 是两种模型自适应算法，MLLR 相比 MAP 的优势是（）", options: ["每条 HMM 单独更新", "EM 迭代", "一套线性变换可适配全部模型", "不用原始模型参数"], answer: "C", answerText: "MLLR 只需估计一组线性变换矩阵，即可适配全部高斯 / HMM。"},
    {id: 144, type: 'single', question: "当自适应数据量极少时，（）算法适配效果更稳定。", options: ["MLLR", "MAP", "K-means", "Viterbi"], answer: "B", answerText: "MAP 特点：少量发音数据即可完成微调，适合小数据自适应。"},
    {id: 145, type: 'fill', question: "工程处理长序列特征时，通常会舍弃原始概率计算，统一采用______似然完成运算。", options: [], answer: "对数", answerText: "对数变换将连乘转为累加，能解决计算机浮点数下溢问题。"},
    {id: 146, type: 'fill', question: "在语音识别中，GMM 用于估计 HMM 中的____概率。", options: [], answer: "观测", answerText: "每个 HMM 隐状态输出观测的概率由 GMM 拟合计算，因此语音识别里 GMM 专门用来估计 HMM 的观测概率。"},
    {id: 147, type: 'fill', question: "单变量高斯分布记为 N x μ,σ2 ，μ代表______，σ2 代表______，全实数域积分结果为______。", options: [], answer: "均值；方差；1", answerText: "5.2 节高斯分布基础定义与概率密度归一化性质。"},
    {id: 148, type: 'fill', question: "GMM 的是多个____分布的线性组合。", options: [], answer: "正态/高斯", answerText: "GMM 整体分布由多个单高斯函数加权线性组合构成。"},
    {id: 149, type: 'fill', question: "GMM 模型参数集合包含权重、______与方差矩阵。", options: [], answer: "均值", answerText: "GMM 三类核心参数。"},
    {id: 150, type: 'fill', question: "GMM 初始化采用 K-means，步骤依次为初始化、______、更新中心点、______至收敛。", options: [], answer: "最近邻分类；迭代", answerText: "算法 5.1 K-means 完整四步流程。"},
    {id: 151, type: 'fill', question: "GMM 混合权重全部相加结果等于______。", options: [], answer: "1", answerText: "约束Kc =1，满足概率归一化规则。所有权重代表各个高斯分量在整k=1 k体分布中的占比。"},
    {id: 152, type: 'fill', question: "GMM-HMM 中每个隐状态的观测概率由______建模。", options: [], answer: "GMM/高斯混合模型", answerText: "状态输出概率依靠 GMM 计算。传统离散 HMM 无法处理连续声学特征，引入 GMM 后解决该问题。"},
    {id: 153, type: 'fill', question: "在 GMM-HMM 训练中，EM 算法分为两大步骤，______步计算样本归属各高斯的后验γ n,k ，______步更新ck 、μk 、Σk 三类参数。", options: [], answer: "E；M", answerText: "算法 5.2 EM 完整迭代流程。"},
    {id: 154, type: 'fill', question: "两种主流语音模型自适应算法，MAP 的中文全称是最大后验概率估计，MLLR 的中文全称是______。", options: [], answer: "最大似然线性回归", answerText: "略。"},
    {id: 155, type: 'judge', question: "高斯 68-95-99.7 法则中，95% 样本落在μ+2σ区间内。（）", options: [], answer: "正确", answerText: "μ+σ包含 68% 数据，μ+2σ包含 95% 数据，μ+3σ包含 99.7% 数据。该规则常用来快速筛选异常样本。"},
    {id: 156, type: 'judge', question: "GMM 中的每个高斯分量都有相同的均值和方差。（）", options: [], answer: "错误", answerText: "每个高斯分量拥有独立的均值与方差，各分量参数互不相同。"},
    {id: 157, type: 'judge', question: "GMM 是一种判别模型。（）", options: [], answer: "错误", answerText: "GMM 用于拟合观测数据的生成分布，属于生成模型而非判别模型，二者建模逻辑完全不同。"},
    {id: 158, type: 'judge', question: "GMM 初始化中，K-means 依靠欧式距离完成样本与聚类中心的匹配分配。（）", options: [], answer: "正确", answerText: "K-means 算法 Step2 说明采用欧式距离衡量远近，将样本划分至最近聚类。欧式距离是高维特征聚类最通用距离指标。"},
    {id: 159, type: 'judge', question: "EM 算法常用于 GMM 参数估计。（）", options: [], answer: "正确", answerText: "EM 迭代求解 GMM 的混合权重、均值、方差三类参数。"},
    {id: 160, type: 'judge', question: "EM 算法迭代终止条件为对数似然函数数值变化小于预设阈值。（）", options: [], answer: "正确", answerText: "算法 5.2 第 5 步规定收敛判断逻辑，对数似然代表模型拟合程度。迭代中似然持续上升并趋于平稳时停止训练。"},
    {id: 161, type: 'judge', question: "GMM-HMM 中隐状态的观测概率依靠伯努利分布建模。（）", options: [], answer: "错误", answerText: "GMM-HMM 使用 GMM 计算观测概率，而非伯努利。伯努利仅适用于二分类离散数据，无法拟合连续声学特征。"},
    {id: 162, type: 'judge', question: "GMM-HMM 训练仅需要更新 HMM 转移参数，无需调整 GMM 均值。（）", options: [], answer: "错误", answerText: "训练需要同步更新初始概率、转移概率、GMM 权重、均值、方差五大类参数。"},
    {id: 163, type: 'judge', question: "离散 HMM 结构内部也需要搭配 GMM 完成观测概率计算。（）", options: [], answer: "错误", answerText: "离散 HMM 输入为离散符号，无高斯组件；只有连续、半连续 HMM 引入 GMM 拟合连续特征。"},
    {id: 164, type: 'judge', question: "使用 MLLR 自适应算法 时，必须为每一个 HMM 单独训练一组线性变换矩阵。（）", options: [], answer: "错误", answerText: "MLLR 核心优势：一套全局变换矩阵适配全部模型高斯。无需逐一对每个 HMM 单独训练，计算效率远高于 MAP。"},
    {id: 165, type: 'essay', question: "GMM 初始化为什么采用 K-means？简述 K-means 四步流程。", options: [], answer: "（1）K-means 快速对特征聚类，得到初始高斯均值、权重，避免 EM 随机初始\n化局部最优；\n（2）步骤：①初始化 K 个聚类中心；②每个样本分配到距离最近中心；③更\n新聚类中心；④迭代至收敛。", answerText: "（1）K-means 快速对特征聚类，得到初始高斯均值、权重，避免 EM 随机初始\n化局部最优；\n（2）步骤：①初始化 K 个聚类中心；②每个样本分配到距离最近中心；③更\n新聚类中心；④迭代至收敛。"},
    {id: 166, type: 'essay', question: "理解 GMM 的定义，并描述 GMM 和 HMM 的关系。", options: [], answer: "（1）GMM 即高斯混合模型，由 K 个带权重的多元高斯分布加权组合而成。\n（2）传统离散 HMM 仅能处理离散观测，语音是连续特征，因此用 GMM 替\n换 HMM 的发射概率模块，构成连续 HMM（GMM-HMM）。GMM 建模单帧\n静态声学特征分布，HMM 建模语音时序动态变化，二者结合完整建模语音序列，\n是传统语音识别经典声学模型。", answerText: "（1）GMM 即高斯混合模型，由 K 个带权重的多元高斯分布加权组合而成。\n（2）传统离散 HMM 仅能处理离散观测，语音是连续特征，因此用 GMM 替\n换 HMM 的发射概率模块，构成连续 HMM（GMM-HMM）。GMM 建模单帧\n静态声学特征分布，HMM 建模语音时序动态变化，二者结合完整建模语音序列，\n是传统语音识别经典声学模型。"},
    {id: 167, type: 'essay', question: "某 GMM-HMM 采用 4 阶高斯混合模型，各高斯分量权重 ck、观测 ot 代入对应高斯得到的概率密度 N(ot; μk, Σk) 如下：\nc1=0.1, N1=0.04; c2=0.2, N2=0.15; c3=0.3, N3=0.10; c4=0.4, N4=0.20\n请计算该帧观测 ot 的对数似然 log P(ot|λ)。", options: [], answer: "逐项计算每个高斯分量的加权概率：\nc1*N1 = 0.1*0.04 = 0.004\nc2*N2 = 0.2*0.15 = 0.030\nc3*N3 = 0.3*0.10 = 0.030\nc4*N4 = 0.4*0.20 = 0.080\nP(ot|λ) = 0.004+0.030+0.030+0.080 = 0.144\nlog P(ot|λ) = ln(0.144) ≈ -1.938", answerText: "逐项计算每个高斯分量的加权概率：\nc1*N1 = 0.1*0.04 = 0.004\nc2*N2 = 0.2*0.15 = 0.030\nc3*N3 = 0.3*0.10 = 0.030\nc4*N4 = 0.4*0.20 = 0.080\nP(ot|λ) = 0.004+0.030+0.030+0.080 = 0.144\nlog P(ot|λ) = ln(0.144) ≈ -1.938"},

    // ── 第6章 基于 HMM 的语音识别 ──
    {id: 168, type: 'single', question: "汉语语音识别中，以下哪种建模单元词汇量扩大后模型数量会爆炸式增长？（）", options: ["音素", "整词", "音节", "三音子"], answer: "B", answerText: "整词以每个词为独立 HMM，词汇量大时模型数量爆炸，扩展性极差。"},
    {id: 169, type: 'single', question: "若采用 HMM 描述语音的发音过程，则 HMM 允许的状态转移方式为（）", options: ["仅自环、向右转移", "仅向左转移", "只能自环", "任意状态互相跳转"], answer: "A", answerText: "发音 HMM 仅允许状态自转移、向右前向转移，不能回退左侧状态。"},
    {id: 170, type: 'single', question: "连续语音识别中，字词 HMM 由哪种单元串联而成（）", options: ["整词", "音素 / 三音子", "句子", "语法"], answer: "B", answerText: "串接 HMM：连续识别中词语由子词音素单元拼接得到。"},
    {id: 171, type: 'single', question: "串接 HMM 中，Viterbi 算法核心求解目标是（）", options: ["计算全局对数似然", "更新 GMM 均值方差", "寻找最大概率隐藏状态序列", "构建三音子决策树"], answer: "C", answerText: "Viterbi 解码：穷举所有路径，找出给定观测下概率最大的隐藏状态序列。"},
    {id: 172, type: 'single', question: "串接 HMM 中，前一个音素终止状态到下一个音素起始状态的跳转称为（）", options: ["自转移", "前向转移", "回退转移", "空转移"], answer: "D", answerText: "相邻音素 HMM 首尾连接的跳转弧为空转移，无对应语音观测帧。"},
    {id: 173, type: 'single', question: "固定语法(打开|关闭)灯光解码时，前几帧仅计算哪类模型（）", options: ["打开、关闭动作 HMM", "灯光 HMM", "静音 sil", "停顿 sp"], answer: "A", answerText: "固定语法解码：前序动作词先解码，到达词末尾空转移后才启动名词HMM。"},
    {id: 174, type: 'single', question: "随机数字串语法 (SENT-START (<$digit>) SENT-END) 中符号<>的含义是（）", options: ["仅识别单个 0~9 数字，只能输出一位数", "可识别任意长度、连续多组 0~9 数字（无位数限制）", "只能识别固定长度的两位数字串", "识别数字时 0 不能出现在首位"], answer: "B", answerText: "<digit>标识代表可循环匹配 digit 单元，能够识别任意位数、连续的 0-9数字序列，不限定数字长度，可识别 1 位、3 位、多位数长串等所有数字组合，不局限单一数字示例。"},
    {id: 175, type: 'single', question: "仅考虑单侧相邻音素上下文的音子模型是（）", options: ["决策树音子", "单音子", "双音子", "三音子"], answer: "D", answerText: "双音子仅单侧上下文；三音子同时包含左、右两侧相邻音素。"},
    {id: 176, type: 'single', question: "三音子模型数量爆炸、训练数据不足的核心解决手段是（）", options: ["增加高斯分量", "改用单音子", "状态绑定", "减少语音帧数"], answer: "C", answerText: "三音子模型通过决策树聚类做状态绑定，发音相似三音子共享 GMM 参数。"},
    {id: 177, type: 'single', question: "采用决策树状态绑定方法时，决策树叶子节点存放的内容是（）", options: ["独立三音子状态集合", "音素分类问题", "高斯混合权重", "状态转移矩阵"], answer: "A", answerText: "决策树不断二分分裂，最终叶子节点为发音相似的三音子状态集合。"},
    {id: 178, type: 'fill', question: "连续语音中词语 HMM 由____单元 HMM 串接而成，单元间跳转称为____。", options: [], answer: "音素；空转移", answerText: "串接 HMM 核心定义。"},
    {id: 179, type: 'fill', question: "语音语法识别分为两类：____语法（句式固定）、____语法（词语数量自由）。", options: [], answer: "固定；随机", answerText: "两大语法体系。"},
    {id: 180, type: 'fill', question: "连续语音音素相互干扰、发音形变的现象叫____，解决该问题使用____模型。", options: [], answer: "协同发音；三音子", answerText: "三音子建模左右上下文抵消连读干扰。"},
    {id: 181, type: 'fill', question: "音子三类：单音子、____、____，其中工业主流为____。", options: [], answer: "双音子；三音子；三音子", answerText: "音子分类对比。"},
    {id: 182, type: 'fill', question: "句首、句尾静音对应的标识是____。", options: [], answer: "sil", answerText: "识别网络标准静音节点标记。"},
    {id: 183, type: 'fill', question: "词语中间短暂停顿的标识是____。", options: [], answer: "sp", answerText: "命令词网络中词间停顿专用符号。"},
    {id: 184, type: 'fill', question: "三音子标记格式规则：左 - 中心 +____。", options: [], answer: "右", answerText: "示例 sil-d+a，右侧音素写在加号后。"},
    {id: 185, type: 'fill', question: "普通话三音子组合数量庞大，核心约束条件为____不足，无法充分训练全部模型。", options: [], answer: "训练语音数据", answerText: "三音子数量问题。"},
    {id: 186, type: 'fill', question: "决策树生成所需问题集的方式有两种：____、____。", options: [], answer: "人工设计；自动生成", answerText: "问题集分类。"},
    {id: 187, type: 'fill', question: "决策树分裂的判断指标为____。", options: [], answer: "似然增益", answerText: "课本 104 页公式 6-6。"},
    {id: 188, type: 'judge', question: "汉语无调音节总数量大约为 400 个。（）", options: [], answer: "正确", answerText: "汉语无调音节约 400 个，以音节为建模单元数量可控。"},
    {id: 189, type: 'judge', question: "整词建模适合海量词汇连续语音识别场景。（）", options: [], answer: "错误", answerText: "词汇量大时整词 HMM 数量爆炸，扩展性极差，仅适用于极小词表。"},
    {id: 190, type: 'judge', question: "单个音素 HMM 有效发声状态是 S1、S5。（）", options: [], answer: "错误", answerText: "S1 起始、S5 结束为空状态，S2、S3、S4 才是发声状态。"},
    {id: 191, type: 'judge', question: "Viterbi 解码网格图中，横轴代表语音观测时间帧，纵轴代表各类发音状态。（）", options: [], answer: "正确", answerText: "例：课本 ba 音节 Viterbi 网格图标注说明。"},
    {id: 192, type: 'judge', question: "串接 HMM 解码时，空转移会占用一帧语音观测特征。（）", options: [], answer: "错误", answerText: "空转移无对应语音帧，仅连接两个音素模型。"},
    {id: 193, type: 'judge', question: "单音子模型能够刻画音素左右两侧上下文连读影响。（）", options: [], answer: "错误", answerText: "单音子无任何上下文信息，无法建模协同发音。"},
    {id: 194, type: 'judge', question: "普通话三音子组合数量很少，不存在数据稀疏问题。（）", options: [], answer: "错误", answerText: "状态绑定定义：相似三音子共用权重、均值、方差。"},
    {id: 195, type: 'judge', question: "状态绑定让发音相近的三音子共享同一套 GMM 参数。（）", options: [], answer: "正确", answerText: "状态绑定定义：相似三音子共用权重、均值、方差。"},
    {id: 196, type: 'judge', question: "三音子模型训练第一步是直接构建决策树。（）", options: [], answer: "错误", answerText: "训练流程起点为单音子模型训练。"},
    {id: 197, type: 'judge', question: "三音子模型迭代训练过程中，需要重新做语音与音素的帧对齐。（）", options: [], answer: "正确", answerText: "三音子训练流程图迭代步骤包含重新对齐。"},
    {id: 198, type: 'essay', question: "什么是协同发音？为什么三音子模型能解决该问题，三音子存在什么缺陷，配套解决方案是什么？", options: [], answer: "（1）协同发音：连续语音流中，前后相邻音素相互干扰、发音产生形变的连读\n现象。\n（2）解决原理：单音子无上下文，双音子仅单侧上下文；三音子格式为左 - 中\n心 + 右，同时刻画中心音素左右两侧相邻音素，完整还原连读发音变化。\n（3）缺陷：普通话三音子组合近 3 万种，训练语音数据稀疏，无法充分训练全\n部模型。\n（1）解决方案：基于发音属性构建决策树，对发音近似的三音子做状态绑定，\n共享同一套 GMM 参数，压缩参数规模、缓解数据不足。", answerText: "（1）协同发音：连续语音流中，前后相邻音素相互干扰、发音产生形变的连读\n现象。\n（2）解决原理：单音子无上下文，双音子仅单侧上下文；三音子格式为左 - 中\n心 + 右，同时刻画中心音素左右两侧相邻音素，完整还原连读发音变化。\n（3）缺陷：普通话三音子组合近 3 万种，训练语音数据稀疏，无法充分训练全\n部模型。\n（1）解决方案：基于发音属性构建决策树，对发音近似的三音子做状态绑定，\n共享同一套 GMM 参数，压缩参数规模、缓解数据不足。"},
    {id: 199, type: 'essay', question: "某原始状态集 S 整体似然 L(S)=-260；将 S 拆分为左右子集 SL、SR，拆分后似然分别为 L(SL)=-140，L(SR)=-112，计算似然增益，并判断本次状态分裂是否有效。", options: [], answer: "计算似然增益：Δ =L(SL)+L(SR)-L(S) = -140 + (-112) - (-260) = 8\n判断规则：Δ>0 分裂有增益，本次分裂有效。", answerText: "计算似然增益：Δ =L(SL)+L(SR)-L(S) = -140 + (-112) - (-260) = 8\n判断规则：Δ>0 分裂有增益，本次分裂有效。"},

    // ── 第7章 DNN-HMM ──
    {id: 200, type: 'single', question: "DNN-HMM 架构中被完全替换的传统声学模块是（）", options: ["HMM 状态转移矩阵", "GMM 高斯混合模型", "Viterbi 解码", "sil 静音节点"], answer: "B", answerText: "DNN 替代 GMM 计算 HMM 各状态后验概率，HMM 时序结构完整保留。"},
    {id: 201, type: 'single', question: "与 GMM 相比，DNN 的主要优势是（）", options: ["计算更简单", "不需要训练", "表达能力更强", "参数更少"], answer: "C", answerText: "GMM 属于浅层模型表征能力弱，DNN 多层非线性结构对复杂语音分布表达能力更强。"},
    {id: 202, type: 'single', question: "神经元线性加权计算公式 z = Σ(wi * xi) + b 中，b 代表（）", options: ["输入特征", "连接权重", "偏置项", "激活输出"], answer: "C", answerText: "神经元数学模型：b 为偏置，用于平移线性求和结果。"},
    {id: 203, type: 'single', question: "逐层计算网络输出的流程称为（）", options: ["反向传播", "前向传播", "梯度下降", "预训练"], answer: "B", answerText: "前向传播输入从底层逐层向上计算预测值。"},
    {id: 204, type: 'single', question: "隐藏层若无激活函数，多层网络等价于单层线性变换，原因是（）", options: ["线性变换复合仍为线性", "权重全部归零", "偏置失效", "梯度消失"], answer: "A", answerText: "连续线性运算叠加后仅等价单一线性映射，无法拟合非线性语音分布。"},
    {id: 205, type: 'single', question: "DNN-HMM 训练流程第一步核心操作是（）", options: ["反向传播训练 DNN", "GMM-HMM 生成帧 - 状态对齐标注", "搭建全连接网络", "Softmax 输出层初始化"], answer: "B", answerText: "DNN-HMM 训练先依靠成熟 GMM-HMM 做语音帧与三音 HMM 状态强制对齐。"},
    {id: 206, type: 'single', question: "基础全连接 DNN 最大固有缺陷是（）", options: ["参数量过少", "无法建模长时序语音依赖", "不能使用 ReLU", "输出无法归一化"], answer: "B", answerText: "DNN 单帧独立输入，无记忆单元，无法存储前后帧时序关联信息。"},
    {id: 207, type: 'single', question: "标准 RNN 长序列训练核心缺陷是（）", options: ["参数量巨大", "梯度消失 / 梯度爆炸", "无法使用 Softmax", "只能处理单帧"], answer: "B", answerText: "梯度沿时序反复相乘，远距离梯度指数衰减，丢失早期语音信息。"},
    {id: 208, type: 'single', question: "LSTM 中专门用于长期记忆传递的核心组件是（）", options: ["隐藏状态 ht", "细胞状态 Ct", "遗忘门", "输出门"], answer: "B", answerText: "细胞状态为记忆传送带，梯度衰减极小，可保留数十帧前发音特征。"},
    {id: 209, type: 'single', question: "TDNN-F 轻量化核心数学手段是（）", options: ["傅里叶变换", "SVD 奇异值矩阵分解", "梯度裁剪", "Dropout"], answer: "B", answerText: "将单层大权重矩阵拆解为两个低维瓶颈矩阵，大幅减少参数。"},
    {id: 210, type: 'fill', question: "DNN-HMM 架构完整保留 HMM 时序、转移、静音结构，仅用 DNN 替换传统____计算模块。", options: [], answer: "GMM/高斯混合模型", answerText: "DNN-HMM 模型架构。"},
    {id: 211, type: 'fill', question: "DNN 隐藏层必须添加____，否则多层叠加仅等价单层线性变换，无法拟合语音____分布。", options: [], answer: "激活函数；非线性", answerText: "激活函数必要性。"},
    {id: 212, type: 'fill', question: "三类基础激活函数：Sigmoid 取值____、Tanh 取值____、ReLU 取值____；其中____以 0 为中心；____激活函数能解决梯度消失现象。", options: [], answer: "(0,1)；(-1,1)；[0,+∞)；Tanh；ReLU", answerText: "激活函数对比。"},
    {id: 213, type: 'fill', question: "多分类任务 DNN 输出层必须使用的激活函数是____。", options: [], answer: "Softmax", answerText: "Softmax 归一输出为各类别概率，总和为 1，适配多分类。"},
    {id: 214, type: 'fill', question: "训练 DNN 时用于衡量预测标签与真实标签差距的函数是____。", options: [], answer: "激活函数", answerText: "交叉熵损失：模型训练目标最小化损失函数值。"},
    {id: 215, type: 'fill', question: "随机梯度下降 SGD 更新权重公式 w' = w - η * Δw 中 η 是____。", options: [], answer: "学习率", answerText: "控制每次参数更新幅度，过大会震荡，过小收敛极慢。"},
    {id: 216, type: 'fill', question: "CNN 卷积核 3×3、频率维度 40、步长 1，单层卷积输出频率维度为____。", options: [], answer: "38", answerText: "计算公式：(40-3)/1 +1=38。"},
    {id: 217, type: 'fill', question: "LSTM 遗忘门激活函数为____，输出区间____，数值 1 代表完整保留历史细胞记忆。", options: [], answer: "Sigmoid；[0,1]", answerText: "门控统一激活规则。"},
    {id: 218, type: 'fill', question: "GRU 简化 LSTM 结构，仅保留____门、____门，合并原遗忘门与输入门功能。", options: [], answer: "更新；复位", answerText: "GRU 与 LSTM 结构差异。"},
    {id: 219, type: 'fill', question: "TDNN 等价仅在时间轴运算的一维 CNN，轻量化改进版本为____，依靠 SVD奇异值矩阵分解压缩参数量。", options: [], answer: "TDNN-F", answerText: "TDNN 轻量化手段。"},
    {id: 220, type: 'judge', question: "生物神经元依靠轴突接收外界信号，树突向下一级神经元输出信息。（）", options: [], answer: "错误", answerText: "树突接收信号，轴突向外传输信号，二者功能相反。"},
    {id: 221, type: 'judge', question: "Softmax 计算时同步减去全局最大值 Zmax，会改变各类别概率相对比值。（）", options: [], answer: "错误", answerText: "所有数值同步减常数，指数比值不变，仅防止浮点溢出。"},
    {id: 222, type: 'judge', question: "语音序列 DNN 训练标准损失函数是均方误差 MSE。（）", options: [], answer: "错误", answerText: "多分类语音任务统一使用多帧交叉熵损失函数。"},
    {id: 223, type: 'judge', question: "SGD 学习率ε设置越大，参数更新越稳定，损失不会震荡。（）", options: [], answer: "错误", answerText: "学习率过大会造成损失函数来回震荡，无法收敛至最小值。"},
    {id: 224, type: 'judge', question: "GMM 模型强制各语音特征维度相互独立，DNN 无该约束，可直接使用 FBank特征。（）", options: [], answer: "正确", answerText: "DNN-HMM 优势。"},
    {id: 225, type: 'judge', question: "CNN 语音输入标准格式为一维单帧 MFCC 向量。（）", options: [], answer: "错误", answerText: "CNN 输入是时间×频率二维 FBank 时频谱图。"},
    {id: 226, type: 'judge', question: "CNN 仅拥有局部时频视野，无法建模长距离语音时序依赖。（）", options: [], answer: "正确", answerText: "CNN 无记忆单元，仅提取局部频谱，无长时序建模能力。"},
    {id: 227, type: 'judge', question: "LSTM 遗忘门输出数值等于 1 时，代表彻底清空历史细胞记忆。（）", options: [], answer: "错误", answerText: "输出 1 = 完整保留记忆；输出 0 = 全部遗忘。"},
    {id: 228, type: 'judge', question: "LSTM、GRU 属于循环网络，推理时支持全批量并行计算。（）", options: [], answer: "错误", answerText: "循环网络当前时刻依赖上一帧隐藏状态，只能串行逐帧计算。"},
    {id: 229, type: 'judge', question: "工业标准 CNN+TDNN-F 架构中，TDNN-F 负责提取原始 FBank 局部频谱。（）", options: [], answer: "错误", answerText: "CNN 为前端频谱提取，TDNN-F 后端建模时序关联。"},
    {id: 230, type: 'essay', question: "DNN-HMM 三步训练流程。", options: [], answer: "Step1：基于 GMM-HMM 系统，实现训练数据帧与状态的对齐；\nStep2：构建 DNN-HMM。用 DNN 替换原 GMM 模块，DNN 输出节点一一对\n应全部 HMM 发射状态；\nStep3：优化 DNN-HMM。通过反向传播算法，从状态级别的帧对齐序列中得到\nDNN 的参数。", answerText: "Step1：基于 GMM-HMM 系统，实现训练数据帧与状态的对齐；\nStep2：构建 DNN-HMM。用 DNN 替换原 GMM 模块，DNN 输出节点一一对\n应全部 HMM 发射状态；\nStep3：优化 DNN-HMM。通过反向传播算法，从状态级别的帧对齐序列中得到\nDNN 的参数。"},
    {id: 231, type: 'essay', question: "DNN 抗过拟合的三个方法。", options: [], answer: "（1）增加训练数据。\n（2）权重衰减方法。\n（3）随机丢弃/dropout 正则化方法。", answerText: "（1）增加训练数据。\n（2）权重衰减方法。\n（3）随机丢弃/dropout 正则化方法。"},
    {id: 232, type: 'essay', question: "已知 3×3 卷积核权重矩阵为：局部 3×3 FBank 输入特征块为：1 0 −10 1 11 1 −13 1 −24 7 61 8 0（1）计算卷积输出单值；（2）若语音 FBank 单通道 40 维，卷积核频率维度尺寸 3，滑动步长 1，求单层卷积输出频率维度。", options: [], answer: "（1）[3×1 + 1×0 + (-2)×(-1)]+(4×0 + 7×1 + 6×1)+[1×1 + 8×1 + 0×(-1)]\n= 3+0+2+0+7+6+1+8+0 = 27\n（2）输出维度 =\n输入维度−卷积核尺寸\n步长\n+1\n40−3\n代入，得： 1 + 1 = 38\n即，卷积输出频率维度 = 38", answerText: "（1）[3×1 + 1×0 + (-2)×(-1)]+(4×0 + 7×1 + 6×1)+[1×1 + 8×1 + 0×(-1)]\n= 3+0+2+0+7+6+1+8+0 = 27\n（2）输出维度 =\n输入维度−卷积核尺寸\n步长\n+1\n40−3\n代入，得： 1 + 1 = 38\n即，卷积输出频率维度 = 38"},

    // ── 第11章 端到端语音识别 ──
    {id: 233, type: 'single', question: "端到端（E2E）语音识别的核心特点是（）", options: ["使用 GMM 建模", "将各模块独立训练", "直接从语音到文本建模", "依赖人工规则"], answer: "C", answerText: "端到端 E2E 能够直接实现语音输入到文本输出的建模。"},
    {id: 234, type: 'single', question: "在端到端模型中，传统语音识别的哪一部分被替代（）", options: ["特征提取", "发音词典", "声学模型", "以上全部"], answer: "D", answerText: "端到端 E2E 语音识别把传统声学模型、语言模型、发音词典多模块融合为单一网络，从而直接实现语音输入到文本输出的建模。"},
    {id: 235, type: 'single', question: "CTC 引入空白符号 <blank> 的核心作用是（）", options: ["增加模型参数量", "解决语音帧与文本标签长度不等长对齐问题", "加速反向传播", "替代 Softmax 层"], answer: "B", answerText: "语音输入帧数 T 远大于文本字符数 U，空白、重复字符实现单调对齐。"},
    {id: 236, type: 'single', question: "CTC 对齐路径必须满足的约束是（）", options: ["时序单调对齐", "可前后乱序匹配", "一字符匹配多帧无限制", "无需空白符号"], answer: "A", answerText: "CTC 规定输入帧按时间顺序匹配标签，对齐具备单调性。"},
    {id: 237, type: 'single', question: "CTC 全局 P(Y|X)的计算逻辑是（）", options: ["取最优单条路径概率", "全部合法对齐路径概率求和", "所有路径概率取最大值", "所有路径取几何平均"], answer: "B", answerText: "课本 194 页公式 11-1。"},
    {id: 238, type: 'single', question: "下列哪一种 CTC 解码算法保留多条候选前缀、精度更高（）", options: ["贪婪搜索", "单帧贪心", "前缀搜索", "暴力枚举"], answer: "C", answerText: "前缀搜索维护多条候选路径，相比单帧贪心识别准确率更高。"},
    {id: 239, type: 'single', question: "严格意义上 CTC 不属于完全端到端的核心原因是（）", options: ["训练依赖标注", "解码需外部语言模型辅助，训练解码割裂", "必须使用 RNN 编码器", "输入只能是 FBank"], answer: "B", answerText: "CTC 训练和解码环节分离，依赖外部 LM，非纯 E2E。"},
    {id: 240, type: 'single', question: "RNN-T 三大核心组件不包含（）", options: ["编码器 Encoder", "预测网络 Prediction", "联合网络 Joint", "CTC 损失层"], answer: "D", answerText: "RNN-T 自有 Transducer 损失，不使用 CTC Loss。"},
    {id: 241, type: 'single', question: "RNN-T 预测网络 Prediction Network 等效于（）", options: ["内置语言模型", "声学模型", "池化层", "Attention 层"], answer: "A", answerText: "输入上一步输出标签，建模文本前后依赖，内部集成 LM 逻辑。"},
    {id: 242, type: 'single', question: "基础无 Attention Seq2Seq 的致命缺陷是（）", options: ["输入输出等长", "不能处理语音", "无法使用 RNN", "长序列信息压缩至单向量丢失细节"], answer: "D", answerText: "仅用最后一帧编码向量承载全部长语音，远距离特征丢失严重。"},
    {id: 243, type: 'fill', question: "端到端语音识别输入仅为语音____，直接输出文本序列，无需中间音素、词典映射。", options: [], answer: "声学特征", answerText: "E2E 极简输入输出链路。"},
    {id: 244, type: 'fill', question: "CTC 通过_______字符和_______字符，可建立跟输入序列的一一对应关系。", options: [], answer: "空白；重复", answerText: "语音输入帧数远多于文本字符，依靠重复字符、空白字符搭建等长中间序列，实现帧与标签一一匹配。"},
    {id: 245, type: 'fill', question: "CTC、RNN-T 的损失均通过_______动态规划递推计算，暴力枚举路径复杂度不可接受。", options: [], answer: "前向-后向", answerText: "两类时序损失统一求解手段。"},
    {id: 246, type: 'fill', question: "CTC 原生缺陷：假设各帧输出标签____，无法建模文本上下文依赖；训练与解码流程割裂，严格来说不属于完整端到端。", options: [], answer: "相互独立", answerText: "CTC 固有独立假设短板。"},
    {id: 247, type: 'fill', question: "给定 CTC 输出序列： b - - o o k -，最终输出为：____。", options: [], answer: "bok", answerText: "CTC 解码规则为移除全部空白符号，再删除连续重复字符。"},
    {id: 248, type: 'fill', question: "CTC、RNN-T 和 AED 中，支持实时流式识别的主流端到端模型是____。", options: [], answer: "RNN-T", answerText: "RNN-T 核心落地优势。"},
    {id: 249, type: 'fill', question: "RNN-T 模型由编码器、预测网络和____组成。", options: [], answer: "联合网络", answerText: "RNN-T 模型分为编码器、预测网络、联合网络三大部分，联合网络融合两路特征后输出分类概率。"},
    {id: 250, type: 'fill', question: "AED 模型完整中文名称是基于____的编码器 - 解码器模型。", options: [], answer: "注意力/Attention", answerText: "AED 为 Attention-based Encoder-Decoder。"},
    {id: 251, type: 'fill', question: "基础 Seq2Seq 存在长距离依赖丢失缺陷，引入____机制改进后得到 AED 模型，每一步 Decoder 会依据全部____隐藏层计算权重。", options: [], answer: "注意力/Attention；编码器/Encoder", answerText: "Attention 解决长语音信息丢失的核心设计。"},
    {id: 252, type: 'fill', question: "语音 Hybrid CTC/Attention 混合模型共用____网络，分出两条独立解码分支：CTC 分支、Attention 分支。", options: [], answer: "编码器/Encoder", answerText: "双流共享架构。"},
    {id: 253, type: 'judge', question: "端到端模型对数据量要求较低。（）", options: [], answer: "错误", answerText: "端到端语音识别模型想要取得良好识别性能，需要耗费大量标注语音语料、更多算力与训练时间，对标注数据量要求很高，因此该说法错误。"},
    {id: 254, type: 'judge', question: "传统解码器采用 Viterbi 维特比搜索，E2E 解码器为神经网络自回归模块。（）", options: [], answer: "正确", answerText: "注意两者区别。"},
    {id: 255, type: 'judge', question: "CTC 对齐路径允许时序回退、乱序匹配语音帧。（）", options: [], answer: "错误", answerText: "CTC 对齐具备严格单调时序约束，只能按时间向后匹配，不可回退。"},
    {id: 256, type: 'judge', question: "CTC 贪婪解码会维护多条候选前缀，识别精度高于前缀搜索。（）", options: [], answer: "错误", answerText: "贪婪仅单帧取最大，局部最优；前缀搜索保留多条候选，精度更高。"},
    {id: 257, type: 'judge', question: "CTC 训练和解码流程一体化，属于完全纯粹的端到端模型。（）", options: [], answer: "错误", answerText: "CTC 训练、解码割裂，依赖外部 LM，不属于完整 E2E。"},
    {id: 258, type: 'judge', question: "Pruned Transducer 依靠剪枝策略减少 U 维度，大幅降低训练显存占用。（）", options: [], answer: "正确", answerText: "张量[B,T,U,C]内存开销过大，剪枝压缩 U。"},
    {id: 259, type: 'judge', question: "RNN-T 预测网络的作用是提取语音时序声学特征。（）", options: [], answer: "错误", answerText: "提取语音特征是编码器 Encoder 的功能，预测网络负责建模文本上下文。"},
    {id: 260, type: 'judge', question: "AED 解码器属于自回归结构，生成字符依赖上一步输出文本。（）", options: [], answer: "正确", answerText: "每一步输入包含前一时刻预测标签。"},
    {id: 261, type: 'judge', question: "Attention 对齐存在严格单调时序约束，和 CTC 对齐规则一致。（）", options: [], answer: "错误", answerText: "Attention 无时序强制约束，可自由匹配任意语音帧。"},
    {id: 262, type: 'judge', question: "混合 CTC-AED 模型只能做单阶段解码，无法分两步处理。（）", options: [], answer: "错误", answerText: "Two-pass 两阶段解码方案。"},
    {id: 263, type: 'essay', question: "简要说明 CTC 的核心优缺点，同时说明严格意义上 CTC 不属于完整端到端模型的原因。", options: [], answer: "（1）优点：\n①无需人工预生成帧文本硬对齐；\n②引入空白+重复字符，语音、文本不等长匹配；\n③对齐严格单调，训练稳定收敛快。\n（2）缺点：\n①假设每帧标签独立，无法建模文本上下文；\n②训练、解码割裂，必须外接语言模型提升通顺度，不算纯 E2E。\n（3）非完整 E2E 原因：\nCTC 训练环节和解码环节相互割裂，训练阶段无内置语言建模能力，解码时依\n赖外部 LM、WFST 等组件，无法依靠单一网络独立完成语音到文字全流程转\n换。", answerText: "（1）优点：\n①无需人工预生成帧文本硬对齐；\n②引入空白+重复字符，语音、文本不等长匹配；\n③对齐严格单调，训练稳定收敛快。\n（2）缺点：\n①假设每帧标签独立，无法建模文本上下文；\n②训练、解码割裂，必须外接语言模型提升通顺度，不算纯 E2E。\n（3）非完整 E2E 原因：\nCTC 训练环节和解码环节相互割裂，训练阶段无内置语言建模能力，解码时依\n赖外部 LM、WFST 等组件，无法依靠单一网络独立完成语音到文字全流程转\n换。"},
    {id: 264, type: 'essay', question: "简述 RNN-T 三大组件各自功能，并说明 RNN-T 相比 CTC 的核心改进。", options: [], answer: "（1）三大组件功能：\n①编码器 Encoder：接收原始语音特征，提取时序声学隐藏特征；\n②预测网络：以上一步输出文本为输入，等效轻量化语言模型，建模文本上下文\n依赖；\n③联合网络：融合编码器声学特征、预测网络文本特征，送入 Softmax 输出联\n合分类概率。\n（2）RNN-T 对比 CTC 核心改进：\nCTC 假设帧标签独立、无内置语言建模；RNN-T 内置预测网络，训练时联合优\n化声学与文本语言依赖，无需外接外部语言模型。", answerText: "（1）三大组件功能：\n①编码器 Encoder：接收原始语音特征，提取时序声学隐藏特征；\n②预测网络：以上一步输出文本为输入，等效轻量化语言模型，建模文本上下文\n依赖；\n③联合网络：融合编码器声学特征、预测网络文本特征，送入 Softmax 输出联\n合分类概率。\n（2）RNN-T 对比 CTC 核心改进：\nCTC 假设帧标签独立、无内置语言建模；RNN-T 内置预测网络，训练时联合优\n化声学与文本语言依赖，无需外接外部语言模型。"},

    // ── 第12章 Transformer 结构 ──
    {id: 265, type: 'single', question: "Transformer Encoder 的主要组成模块是（）", options: ["Masked Attention 和 Cross Attention", "Self-Attention 和 Feed Forward", "CNN 和 RNN", "GMM 和 HMM"], answer: "B", answerText: "Encoder 包含自注意力 Self-Attention、前馈网络 Feed Forward 两个子层，Masked 注意力、交叉注意力仅存在 Decoder。"},
    {id: 266, type: 'single', question: "在 Transformer Encoder 中，Self-Attention 的主要作用是（）", options: ["只提取相邻帧之间的局部关系", "将语音信号转换为频谱图", "建模语音序列中不同时间位置之间的依赖关系", "直接计算词错误率"], answer: "C", answerText: "Encoder 的自注意力可计算序列任意位置的关联权重，能建模整条语音序列所有时间帧之间的全局依赖，不局限相邻局部；A、B、D 均不属于自注意力的功能。"},
    {id: 267, type: 'single', question: "位置编码与输入嵌入向量的融合运算方式为（）", options: ["矩阵相乘", "逐元素相加", "矩阵拼接", "卷积融合"], answer: "B", answerText: "融合公式 X'=X+PE，同维度向量逐元素叠加，向嵌入向量注入序列位置时序信息。"},
    {id: 268, type: 'single', question: "多头注意力各单头输出完成后，第一步操作是（）", options: ["直接送入前馈层", "单独计算掩蔽", "单独归一化", "拼接所有头输出"], answer: "D", answerText: "多头机制：每个头独立计算注意力输出，全部头结果拼接后，再通过线性矩阵融合维度。"},
    {id: 269, type: 'single', question: "多头注意力流程正确排序是（）①线性投影拆分 Q/K/V ②分头计算缩放点积注意力 ③拼接所有头输出 ④线性融合", options: ["①②③④", "①③②④", "②①③④", "②③①④"], answer: "A", answerText: "原始输入先线性投影分为多组 QKV，每个头独立计算注意力，结果拼接后经线性变换得到最终多头输出。"},
    {id: 270, type: 'single', question: "Transformer 前馈网络 FFN 中间使用的激活函数为（）", options: ["GeLU", "ReLU", "Sigmoid", "Tanh"], answer: "B", answerText: "前馈网络在两层线性层中间插入 ReLU 非线性激活。"},
    {id: 271, type: 'single', question: "Transformer Decoder 中用于防止看到未来信息的是（）", options: ["Self-Attention", "Masked Attention", "Cross Attention", "Feed Forward"], answer: "B", answerText: "Masked Masked Attention 会添加因果掩码，将序列未来位置填充负无穷，避免模型读取未生成的后续 token，实现时序约束；Self-Attention 无屏蔽效果，Cross Attention 负责关联编码器特征，Feed Forward 仅做单帧非线性变换。"},
    {id: 272, type: 'single', question: "若移除 Decoder 的因果 Mask，会出现什么问题（）", options: ["预测时可以提前看到未来 token，生成逻辑失效", "模型无法读取编码器输入特征", "多头注意力无法完成拼接融合", "位置编码无法叠加至输出嵌入"], answer: "A", answerText: "Mask 核心作用是屏蔽目标序列未来位置；去掉 Mask 后，模型预测第i 个 token 时能直接看到 i+1、i+2 等后续字符，违背自回归生成的因果逻辑，训练与推理完全失效。"},
    {id: 273, type: 'single', question: "交叉注意力模块中，查询 Quary 的来源是（）", options: ["原始输入嵌入", "Decoder 上一层输出", "Encoder 最终输出", "位置编码"], answer: "C", answerText: "交叉注意力 Quary 取自解码器上层文本特征，Key、Value 取自编码器全局输入特征，建立输入输出序列的对齐关系。"},
    {id: 274, type: 'single', question: "预测时可以提前看到未来 token，生成逻辑失效推理阶段 Decoder 的输入特征来源是（）", options: ["全局真实标注文本", "编码器原始输入", "上一轮自身生成的全部 token 序列", "固定常量位置编码"], answer: "C", answerText: "推理为自回归生成模式，无完整标注文本；每一轮将上一步输出的全部文本拼接，作为下一轮解码器输入，逐 token 迭代生成。"},
    {id: 275, type: 'fill', question: "语音版 Transformer 会先对原始语音特征进行______操作，再叠加位置编码注入时序信息。", options: [], answer: "卷积下采样", answerText: "语音模型输入流程：语音特征→1D 卷积下采样→位置编码→Encoder→Decoder。"},
    {id: 276, type: 'fill', question: "Transformer 摒弃 RNN 循环结构，依靠______补充时序位置信息，原生无法感知序列顺序。", options: [], answer: "位置编码", answerText: "Transformer 无循环单元，必须额外注入位置特征。"},
    {id: 277, type: 'fill', question: "位置编码中，偶数维通常使用____函数，奇数维通常使用____函数。", options: [], answer: "sin；cos", answerText: "位置编码分段计算公式。"},
    {id: 278, type: 'fill', question: "缩放点积注意力完整流程：Q*K^T 矩阵相乘 → 除以______缩放 → 可选 Mask 掩蔽 → Softmax 归一化 → 乘 V 得到输出 Z。", options: [], answer: "√(d_k)", answerText: "标准注意力公式中指出，除以键向量维度平方根，可以防止内积数值过大导致 Softmax 梯度消失。"},
    {id: 279, type: 'fill', question: "Attention 权重通常由打分结果经过____函数归一化得到。", options: [], answer: "Softmax", answerText: "该函数将注意力打分转为每行和为 1 的概率权重。"},
    {id: 280, type: 'fill', question: "交叉注意力三元组中，Query 取自______上层输出，Key、Value 取自______完整编码输出。", options: [], answer: "解码器/Decoder；编码器/Encoder", answerText: "Query 代表待生成文本，Key、Value 存储输入序列全局特征。"},
    {id: 281, type: 'fill', question: "残差连接的作用是缓解深层网络______，传递原始输入特征。", options: [], answer: "梯度消失", answerText: "残差直连通路稳定反向传播。"},
    {id: 282, type: 'fill', question: "层归一化会将单样本特征标准化至均值为______、方差为______的标准正态分布，加速模型收敛。", options: [], answer: "0；1", answerText: "层归一化消除特征尺度差异，稳定训练梯度。"},
    {id: 283, type: 'fill', question: "在 Transformer Decoder 中，Masked Attention 的作用是防止当前位置看到____信息，从而保证生成过程符合从左到右的顺序。", options: [], answer: "未来", answerText: "因果掩码屏蔽序列后续未生成的未来 token，约束生成只能依赖前文。"},
    {id: 284, type: 'fill', question: "推理阶段 Transformer 解码器采用______自回归生成模式，每一轮输入为上一轮完整生成文本，串行逐 token 输出。", options: [], answer: "串行", answerText: "推理无完整标注文本，只能迭代用上一轮全部输出作为输入逐字生成。"},
    {id: 285, type: 'judge', question: "Transformer 相比传统 RNN，序列可并行计算是其独有的核心优势。（）", options: [], answer: "正确", answerText: "RNN 串行逐帧计算，Transformer 依靠自注意力实现全序列并行运算。"},
    {id: 286, type: 'judge', question: "卷积下采样可以减少语音特征的时间长度，从而降低后续计算量。（）", options: [], answer: "正确", answerText: "true"},
    {id: 287, type: 'judge', question: "一维卷积仅沿序列时间维度滑动，适配时序类数据。（）", options: [], answer: "正确", answerText: "1D 卷积专门处理语音、文本一维时间序列。"},
    {id: 288, type: 'judge', question: "多头注意力中每个头拥有独立的 WQ、WK、WV 权重矩阵。（）", options: [], answer: "正确", answerText: "多头划分至不同特征子空间，各组投影权重互不共享。"},
    {id: 289, type: 'judge', question: "前馈网络 FFN 能够建模不同 token 之间的上下文依赖关系。（）", options: [], answer: "错误", answerText: "FFN 仅处理单个 token，跨 token 依赖依靠注意力。"},
    {id: 290, type: 'judge', question: "每个 Encoder、Decoder 子层输出后都配套残差连接与层归一化。（）", options: [], answer: "正确", answerText: "所有子层统一标配结构。"},
    {id: 291, type: 'judge', question: "因果 Mask 有两种实现方式，分别是 Mask 矩阵与注意力分数按位相加、按位相乘。（）", options: [], answer: "正确", answerText: "掩蔽常用负无穷相加，也存在相乘实现形式。"},
    {id: 292, type: 'judge', question: "Mask 因果矩阵对角线及下方为无效区域，右上区域保留原始注意力分数。（）", options: [], answer: "错误", answerText: "对角线及下方是前文有效信息，右上未来位置填充负无穷屏蔽。"},
    {id: 293, type: 'judge', question: "Cross Attention 同时存在于 Encoder 和 Decoder 两层结构中。（）", options: [], answer: "错误", answerText: "交叉注意力仅解码器独有，编码器不存在。"},
    {id: 294, type: 'judge', question: "Transformer 训练和推理阶段 Decoder 的输入方式完全相同。（）", options: [], answer: "错误", answerText: "训练用教师强制（Teacher Forcing）策略，目标序列整体右移并行输入；推理自回归逐字符迭代输入，二者输入逻辑不同。"},
    {id: 295, type: 'essay', question: "简述 Transformer 相比 RNN 的核心优势。", options: [], answer: "RNN 串行逐帧计算，必须等待上一时刻输出才能计算下一时刻；Transformer 舍\n弃循环结构，依靠自注意力实现整条序列所有 token 并行计算，大幅提升训练\n速度；同时自注意力可直接捕捉长距离全局依赖，长文本效果更好。", answerText: "RNN 串行逐帧计算，必须等待上一时刻输出才能计算下一时刻；Transformer 舍\n弃循环结构，依靠自注意力实现整条序列所有 token 并行计算，大幅提升训练\n速度；同时自注意力可直接捕捉长距离全局依赖，长文本效果更好。"},
    {id: 296, type: 'essay', question: "简述 Transformer 中三种注意力机制、各自所在模块与作用。", options: [], answer: "Transformer 包含自注意力、掩蔽注意力、交叉注意力三类注意力：\n自注意力：仅存在 Encoder 编码器，输入为语音特征序列，用于建模输入语音\n内部全部帧的全局依赖；\n掩蔽注意力：Decoder 解码器第一层，施加因果掩码屏蔽未来 token，保证生成\n只能读取前文，约束从左到右的生成顺序；\n交叉注意力：Decoder 解码器第二层，Quary 来自解码器上层输出，Key、Value\n取自编码器完整输出，建立输入语音与输出文本的跨序列语义对齐。", answerText: "Transformer 包含自注意力、掩蔽注意力、交叉注意力三类注意力：\n自注意力：仅存在 Encoder 编码器，输入为语音特征序列，用于建模输入语音\n内部全部帧的全局依赖；\n掩蔽注意力：Decoder 解码器第一层，施加因果掩码屏蔽未来 token，保证生成\n只能读取前文，约束从左到右的生成顺序；\n交叉注意力：Decoder 解码器第二层，Quary 来自解码器上层输出，Key、Value\n取自编码器完整输出，建立输入语音与输出文本的跨序列语义对齐。"},
    {id: 297, type: 'essay', question: "位置编码的作用、生成方式和融合方法。", options: [], answer: "作用：Transformer 无循环结构，无法天然感知时序，位置编码补充位置先后信\n息；\n生成：通过 sin、cos 三角函数固定计算；\n融合：与输入嵌入向量逐元素相加 X'=X+PE。", answerText: "作用：Transformer 无循环结构，无法天然感知时序，位置编码补充位置先后信\n息；\n生成：通过 sin、cos 三角函数固定计算；\n融合：与输入嵌入向量逐元素相加 X'=X+PE。"},
    {id: 298, type: 'essay', question: "输入语音特征为 3000 帧、80 维 FBank，经过两层一维卷积完成卷积下采样；卷积参数：第一层 1D Conv：kernel=3，stride=1，padding=1；第二层 1D Conv：kernel=3，stride=2，padding=1；分别计算两层卷积输出的帧数，并说明整体下采样倍数。", options: [], answer: "第一层卷积输出帧数：\n3000 + 2 × 1 − 3\n2999\n+1 =\n+ 1 = 3000\n1\n1\n即，第一层输出：3000 帧。\n第二层卷积输出帧数：\n3000 + 2 × 1 − 3\n2999\n+1 =\n+ 1 ≈ 1500\n2\n2\n即，第二层输出：1500 帧。\n下采样倍数：\n原始 3000 帧，最终输出 1500 帧，实现 2 倍下采样。", answerText: "第一层卷积输出帧数：\n3000 + 2 × 1 − 3\n2999\n+1 =\n+ 1 = 3000\n1\n1\n即，第一层输出：3000 帧。\n第二层卷积输出帧数：\n3000 + 2 × 1 − 3\n2999\n+1 =\n+ 1 ≈ 1500\n2\n2\n即，第二层输出：1500 帧。\n下采样倍数：\n原始 3000 帧，最终输出 1500 帧，实现 2 倍下采样。"},

    // ── 第13章 Conformer 结构 ──
    {id: 299, type: 'single', question: "Conformer 相比原始 Transformer，主要改进的是哪一部分？（）", options: ["Decoder", "Encoder", "Softmax 层", "损失函数"], answer: "B", answerText: "Conformer 仅对 Transformer Encoder 进行了改进。"},
    {id: 300, type: 'single', question: "Conformer 在 Transformer 基础上主要加入了哪类模块？（）", options: ["卷积模块", "循环模块", "聚类模块", "语法模块"], answer: "A", answerText: "Conformer 仅对 Encoder 改进，核心新增深度可分离卷积模块，无循环、聚类、语法模块。"},
    {id: 301, type: 'single', question: "Conformer Block 中，卷积模块通常位于（）", options: ["两个前馈模块之前", "多头自注意力模块之前", "多头自注意力模块之后、第二个前馈模块之前", "层归一化之后"], answer: "C", answerText: "根据 Conformer Block 结构，顺序为 1/2 前馈→多头自注意力→卷积模块→1/2 前馈→层归一化，卷积在多头自注意力后、第二个前馈前。"},
    {id: 302, type: 'single', question: "相比纯 Transformer，Conformer 在 ASR 中额外引入卷积模块的原因是（）", options: ["完全替代注意力机制", "增强局部时序特征建模能力", "减少输入特征维度", "避免使用位置编码"], answer: "B", answerText: "原生 Transformer 仅依靠注意力捕捉全局依赖，缺少语音相邻帧局部声学建模能力，Conformer 新增深度可分离卷积专门提取局部时序特征，兼顾全局与局部信息。"},
    {id: 303, type: 'single', question: "Conformer 多头自注意力采用的位置编码类型是（）", options: ["正弦余弦绝对位置编码", "可学习绝对编码", "相对位置编码", "固定片段编码"], answer: "C", answerText: "Conformer 借鉴 Transformer-XL 思想，用相对位置编码替换原生绝对位置编码。"},
    {id: 304, type: 'single', question: "深度可分离卷积由哪两种卷积组合而成（）", options: ["1D 卷积 + 2D 卷积", "步长卷积 + 填充卷积", "因果卷积 + 普通卷积", "逐通道卷积 + 逐点卷积"], answer: "D", answerText: "Depthwise 逐通道卷积 + Pointwise 逐点卷积 = 深度可分离卷积。"},
    {id: 305, type: 'single', question: "Conformer 前馈模块使用的激活函数为（）", options: ["ReLU", "Swish", "Sigmoid", "Tanh"], answer: "B", answerText: "Conformer 前馈模块采用带可调参数的 Swish 激活，搭配 Dropout 防过拟合。"},
    {id: 306, type: 'single', question: "流式语音识别输入 Conformer 的基础单元是（）", options: ["chunk 语音片段", "完整整段语音", "单帧 FBank 特征", "字符 token"], answer: "A", answerText: "流识别分段输入，每次送入一个 chunk，依靠缓存保存历史上下文。"},
    {id: 307, type: 'single', question: "流式 Conformer 相对位置编码需要额外添加的参数是（）", options: ["lorder", "offset 偏移量", "stride 步长", "padding 填充"], answer: "B", answerText: "chunk 分段输入破坏连续时序，offset 用来修正相对位置计算偏差。"},
    {id: 308, type: 'single', question: "流式 Conformer 缓存历史 chunk 的目的是（）", options: ["减少模型参数量", "增大下采样倍数", "提供左侧上下文依赖，降低重复计算量", "替换位置编码"], answer: "C", answerText: "逐 chunk 输入缺少上文，缓存历史 chunk 为自注意力、卷积提供左侧时序信息。"},
    {id: 309, type: 'fill', question: "Conformer 基于 Transformer 改造，仅改动______，新增______模块，同时将绝对位置编码替换为______。", options: [], answer: "编码器/Encoder；卷积；相对位置编码", answerText: "改动仅发生在编码器。"},
    {id: 310, type: 'fill', question: "Conformer 在语音识别中表现较好，是因为它兼顾了 Transformer 的长距离建模能力和 CNN 的____建模能力。", options: [], answer: "局部", answerText: "卷积模块提取相邻语音帧局部声学特征，弥补纯 Transformer 缺少局部建模的短板。"},
    {id: 311, type: 'fill', question: "Conformer 卷积模块中，逐通道卷积计算完成后会经过______激活。", options: [], answer: "GLU", answerText: "Depthwise 卷积输出接入 GLU 激活单元。"},
    {id: 312, type: 'fill', question: "128 通道特征经过 GLU 激活后，通道数量压缩为______通道。", options: [], answer: "64", answerText: "输入 128 通道，GLU 输出 64 通道送入逐通道卷积。"},
    {id: 313, type: 'fill', question: "深度可分离卷积包含逐通道卷积和______卷积。", options: [], answer: "逐点", answerText: "二者组合构成轻量化卷积模块。"},
    {id: 314, type: 'fill', question: "深度可分离卷积能够有效降低 Conformer 模型______数量。", options: [], answer: "参数", answerText: "拆分空间、通道计算，减少权重。"},
    {id: 315, type: 'fill', question: "Conformer Block 最底部模块是带 1/2 缩放系数的______模块。", options: [], answer: "前馈", answerText: "Block 流程起点：1/2 前馈模块。"},
    {id: 316, type: 'fill', question: "Conformer 多头自注意力的相对位置编码思想源自______模型。", options: [], answer: "Transformer-XL", answerText: "相对位置编码借鉴 Transformer-XL。"},
    {id: 317, type: 'fill', question: "相对位置编码符号为____，i-j 代表 token i 与 token j 之间的______差值。", options: [], answer: "Ri-j；相对位置", answerText: "区别于全局绝对位置编码 PEi。"},
    {id: 318, type: 'fill', question: "Conformer 流识别机制中，CTC 输出后可搭配 Transformer 解码器和______解码器。", options: [], answer: "FST", answerText: "两种主流后处理解码方案。"},
    {id: 319, type: 'judge', question: "Conformer 多头自注意力依旧使用正弦余弦绝对位置编码。（）", options: [], answer: "错误", answerText: "替换为 Transformer-XL 衍生的相对位置编码。"},
    {id: 320, type: 'judge', question: "Transformer-XL 通过缓存上一片段向量，拓展上下文长度。（）", options: [], answer: "正确", answerText: "缓存历史片段突破固定窗口限制。"},
    {id: 321, type: 'judge', question: "逐点卷积负责提取单通道局部特征，逐通道卷积做通道融合。（）", options: [], answer: "错误", answerText: "逐通道提取局部，逐点负责跨通道融合。"},
    {id: 322, type: 'judge', question: "层归一化 LN 针对整个批次样本计算均值方差，和 BN 完全一致。（）", options: [], answer: "错误", answerText: "LN 归一化单样本，BN 归一化整批次。"},
    {id: 323, type: 'judge', question: "Conformer 卷积模块内置 GLU 门控激活函数，原生 Transformer 没有 GLU激活单元。（）", options: [], answer: "正确", answerText: "深度可分离卷积中间 GLU 是 Conformer 专属结构。"},
    {id: 324, type: 'judge', question: "Conformer Block 前后两个前馈模块都带有 1/2 缩放系数。（）", options: [], answer: "正确", answerText: "公式中 FFN 均乘 1/2 平衡输出幅值。"},
    {id: 325, type: 'judge', question: "前馈模块中的 Dropout 作用是减少模型参数量。（）", options: [], answer: "错误", answerText: "Dropout 用于防止过拟合，不改变参数量。"},
    {id: 326, type: 'judge', question: "Conformer 流式卷积使用因果卷积，可以读取右侧未来时序帧。（）", options: [], answer: "错误", answerText: "因果卷积仅使用当前 + 左侧历史帧。"},
    {id: 327, type: 'judge', question: "流式识别 chunk 尺寸固定 320ms，不支持自定义修改。（）", options: [], answer: "错误", answerText: "chunk 时长可自行设置。"},
    {id: 328, type: 'judge', question: "Conformer 依靠 num_decoding_left_chunks 控制注意力缓存 chunk 数量，原生 Transformer 不存在 chunk 缓存参数。（）", options: [], answer: "正确", answerText: "chunk 分段缓存参数仅用于 Conformer 流式识别。"},
    {id: 329, type: 'essay', question: "对比原生 Transformer Encoder，简述 Conformer Encoder 两处核心改进和各自作用。", options: [], answer: "（1）新增深度可分离卷积模块\n作用：由逐点、逐通道卷积组成，参数量更低；专门提取语音相邻帧局部时序声\n学特征，弥补纯 Transformer 仅能建模全局长依赖、缺少局部邻域建模的短板。\n（2）用相对位置编码替换原生绝对位置编码\n作用：借鉴 Transformer-XL 思路，解决不同片段相同位次 token 无法区分的缺\n陷；流式 chunk 分段输入时搭配 offset 偏移修正时序断裂，适配实时语音识别。", answerText: "（1）新增深度可分离卷积模块\n作用：由逐点、逐通道卷积组成，参数量更低；专门提取语音相邻帧局部时序声\n学特征，弥补纯 Transformer 仅能建模全局长依赖、缺少局部邻域建模的短板。\n（2）用相对位置编码替换原生绝对位置编码\n作用：借鉴 Transformer-XL 思路，解决不同片段相同位次 token 无法区分的缺\n陷；流式 chunk 分段输入时搭配 offset 偏移修正时序断裂，适配实时语音识别。"},
    {id: 330, type: 'essay', question: "输入语音特征为 32 帧（并拼接 3 帧缓存），80 维 FBank，经过两层二维卷积完成卷积下采样；卷积参数：第一层 2D Conv：kernel=3×3，stride=2，padding=0；第二层 2D Conv：kernel=3×3，stride=2，padding=0；分别计算两层卷积输出的时序帧数、频域维数，并说明时序下采样倍数。", options: [], answer: "（1）第一层卷积输出帧数：\n时序帧数：\n35 − 3\n32\n+1 =\n+ 1 = 17\n2\n2\n频域维数：\n80 − 3\n77\n+1 =\n+ 1 ≈ 17\n2\n2\n即，第一层输出：时序 17 帧，频域 39 维。\n（2）第二层卷积输出帧数：\n时序帧数：\n17 − 3\n14\n+1 =\n+1 = 8\n2\n2\n频域维数：\n39 − 3\n36\n+1 =\n+ 1 = 19\n2\n2\n即，第二层输出：时序 8 帧，频域 9 维。\n（3）下采样倍数：\n原始 32 帧，最终输出 8 帧，实现 4 倍下采样。", answerText: "（1）第一层卷积输出帧数：\n时序帧数：\n35 − 3\n32\n+1 =\n+ 1 = 17\n2\n2\n频域维数：\n80 − 3\n77\n+1 =\n+ 1 ≈ 17\n2\n2\n即，第一层输出：时序 17 帧，频域 39 维。\n（2）第二层卷积输出帧数：\n时序帧数：\n17 − 3\n14\n+1 =\n+1 = 8\n2\n2\n频域维数：\n39 − 3\n36\n+1 =\n+ 1 = 19\n2\n2\n即，第二层输出：时序 8 帧，频域 9 维。\n（3）下采样倍数：\n原始 32 帧，最终输出 8 帧，实现 4 倍下采样。"},
];
