// 题目数据库 - 第三部分 (101-200题)
const questionsPart3 = [
    {id: 101, type: 'single', question: '关于卷积神经网络说法不正确的是(        )。', options: ['对图像用卷积核进行卷积运算，实际上是一个滤波的过程。', '卷积神经网络可以包括卷积层，池化层和全连接层。', '常见的池化层有最大池化和平均池化', '卷积神经网络只能有一个卷积核'], answer: 'D', answerText: 'D\n\nCNN可以有多个卷积核来提取不同的特征。'},
    {id: 102, type: 'single', question: '卷积神经网络做图像分类任务通常不包含(        )。', options: ['卷积操作', '池化操作', '全连接层', '均方误差损失函数'], answer: 'D', answerText: 'D\n\n图像分类通常使用交叉熵损失函数，而不是均方误差。'},
    {id: 103, type: 'single', question: '下面不属于人工神经网络的是(        )。', options: ['卷积神经网络', '循环神经网络', '网络森林', '深度神经网络'], answer: 'C', answerText: 'C\n\n网络森林是集成学习方法，不是神经网络。'},
    {id: 104, type: 'single', question: '卷积运算过程正确的顺序是: ①对应位置求乘积  ②所有位置求和  ③输出一个位置的结果  ④移动卷积核。(        )', options: ['①②③④', '①④②③', '②③①④', '④③①②'], answer: 'A', answerText: 'A\n\n卷积运算的正确顺序是：对应位置求乘积 → 所有位置求和 → 输出结果 → 移动卷积核。'},
    {id: 105, type: 'single', question: '卷积核与特征图的通道数的关系是(        )。', options: ['卷积核数量越多特征图通道数越少', '卷积核size越大特征图通道数越多', '卷积核数量越多特征图通道数越多', '二者没有关系'], answer: 'C', answerText: 'C\n\n卷积核的数量决定了输出特征图的通道数。'},
    {id: 106, type: 'single', question: '池化操作的作用是(        )。', options: ['上采样', '下采样', '增加特征图通道数', '选项都不对'], answer: 'B', answerText: 'B\n\n池化操作进行下采样，降低特征图的维度。'},
    {id: 107, type: 'single', question: '卷积神经网络中，对于池化的描述不正确的是(        )。', options: ['选取区域内特征的最大值', '池化可以压缩数据、降低维度', '拆分一个区域', '选取区域内特征的平均值'], answer: 'C', answerText: 'C\n\n池化是对区域内特征进行聚合，而不是拆分。'},
    {id: 108, type: 'single', question: '假设我们需要训练一个卷积神经网络，来完成0~9和英文字母(不区分大小写)的图像分类。该卷积神经网络最后一层是分类层，则最后一层输出向量的维数大小可能是(        )。', options: ['26', '36', '62', '10'], answer: 'B', answerText: 'B\n\n0-9共10个数字，英文字母26个，共36个类别。'},
    {id: 109, type: 'single', question: '一般情况下，我们认为深度学习、机器学习和人工智能之间的层次关系为(        )。', options: ['机器学习 ⊂ 深度学习 ⊂ 人工智能', '深度学习 ⊂ 人工智能 ⊂ 机器学习', '深度学习 ⊂ 机器学习 ⊂ 人工智能', '深度学习 = 机器学习 ⊂ 人工智能'], answer: 'C', answerText: 'C\n\n深度学习是机器学习的子集，机器学习是人工智能的子集。'},
    {id: 110, type: 'single', question: '关于生成对抗网络说法不正确的是(        )。', options: ['判别模型需要输入带标签的真实样本', '生成对抗网络包含生成模型与判别模型', '生成对抗网络不能用来产生新的图片', '生成模型的输入可以是随机噪声矢量。'], answer: 'C', answerText: 'C\n\n生成对抗网络可以用来产生新的图片。'},
    {id: 111, type: 'single', question: '数字图像的最小单位是(        )。', options: ['像素', '分辨率', '点', '位'], answer: 'A', answerText: 'A\n\n像素是数字图像的最小单位。'},
    {id: 112, type: 'single', question: '以下应用场景中, (        )不是计算机视觉的任务。', options: ['视频中感兴趣目标的检测、跟踪和定位', '图像中前景物体与背景的分割', '图像/视频中文字的检测和识别', '图像存储/语音合成'], answer: 'D', answerText: 'D\n\n图像存储和语音合成不是计算机视觉的任务。'},
    {id: 113, type: 'single', question: '下列属于计算机视觉在交通领域中的应用不包括(        )。', options: ['违章闯红灯检测', '汽车尾气的化学成分分析', '汽车车牌识别', '自动驾驶系统'], answer: 'B', answerText: 'B\n\n汽车尾气的化学成分分析不是计算机视觉的应用。'},
    {id: 114, type: 'single', question: '我们日常生活中的上下班，指纹扫描打卡考勤、虹膜扫描，应用到了人工智能中的(        )。', options: ['机器翻译技术', '机器翻译', '虚拟现实', '模式识别'], answer: 'D', answerText: 'D\n\n指纹识别和虹膜识别是模式识别的应用。'},
    {id: 115, type: 'single', question: '彩色图像中，每个像素点通常采用(        )表示色彩值。', options: ['一个值', '二个值', '三个值', '四个值'], answer: 'C', answerText: 'C\n\nRGB彩色图像用三个值（红、绿、蓝）表示每个像素。'},
    {id: 116, type: 'single', question: '一张RGB彩色图片存储在计算机中通常不含以下哪一项(        )。', options: ['黄色通道', '蓝色通道', '绿色通道', '红色通道'], answer: 'A', answerText: 'A\n\nRGB图像只有红、绿、蓝三个通道，没有黄色通道。'},
    {id: 117, type: 'single', question: '在机器学习中，如果数据较少，同时采用的模型较复杂，得到的模型在给定的训练集上误差非常小，接近于0，但是在训练集之外的数据上预测效果很差,这种现象称为(        )。', options: ['经验风险', '过拟合', '欠拟合', '损失函数'], answer: 'B', answerText: 'B\n\n过拟合是指模型在训练集上表现好，但在测试集上表现差。'},
    {id: 118, type: 'single', question: '多数计算机视觉方法可以区分为"基于浅层模型的方法"或"基于深度模型的方法"，后者就是2012年以来广泛应用的深度学习(deep learning)方法。以下说法不正确的是(        )。', options: ['基于浅层模型的方法无法提取图像中的内容特征', '基于浅层模型的方法包括人工设计和提取图像中的内容特征', '基于深度模型的方法通过优化等手段从图像中自动学习内容特征', '从前者到后者的变迁实现了从"经验知识驱动"到"数据驱动"的转变'], answer: 'A', answerText: 'A\n\n基于浅层模型的方法可以提取图像特征，只是需要人工设计。'},
    {id: 119, type: 'single', question: '我们可以将深度学习看成一种端到端的学习方法，这里的端到端指的是(        )。', options: ['输入端-输出端', '输入端-中间端', '输出端-中间端', '中间端-中间端'], answer: 'A', answerText: 'A\n\n端到端学习是从输入直接到输出的学习方法。'},
    {id: 120, type: 'single', question: '自然语言处理的简称是什么?(        )', options: ['NLP', 'ANN', 'NLU', 'APL'], answer: 'A', answerText: 'A\n\nNLP是Natural Language Processing的缩写。'},
    {id: 121, type: 'fill', question: '知识的特性包括____、____、可表示性和可利用性。', options: [], answer: '相对正确性;不确定性', answerText: '答案：相对正确性；不确定性\n\n知识的四个特性是：相对正确性、不确定性、可表示性、可利用性。'},
    {id: 122, type: 'fill', question: '造成知识不确定性的原因主要有由____引起的不确定性，由____引起的不确定性 ， 由____引起的不确定性 ，由____引起的不确定性 。', options: [], answer: '随机性;模糊性;经验;不完全性', answerText: '答案：随机性；模糊性；经验；不完全性\n\n这四个因素都会导致知识的不确定性。'},
    {id: 123, type: 'fill', question: '人工智能中知识的表示方法有____、____和状态空间等。', options: [], answer: '产生式;框架', answerText: '答案：产生式；框架\n\n知识表示方法包括产生式、框架、状态空间、逻辑等。'},
    {id: 124, type: 'fill', question: '一般来说,一个产生式系统由____、____、 控制系统(推理机)三部分组成。', options: [], answer: '规则库;综合数据库', answerText: '答案：规则库；综合数据库\n\n产生式系统的三个主要部分是规则库、综合数据库和推理机。'},
    {id: 125, type: 'fill', question: '产生式系统中推理机要完成的工作包括____、____、执行规则和检查推理终止条件。', options: [], answer: '推理;冲突消解', answerText: '答案：推理；冲突消解\n\n推理机的主要工作是推理、冲突消解、执行规则和检查终止条件。'},
    {id: 126, type: 'fill', question: '一个框架由若干个被称为"____" 的结构组成,  用于描述所论对象某一方面的属性。', options: [], answer: '槽', answerText: '答案：槽\n\n框架由多个槽组成，每个槽描述对象的一个属性。'},
    {id: 127, type: 'fill', question: '在框架理论中,一个框架通常由描述事物的各个方面的槽组成,  每个槽可以划分为若干个____。', options: [], answer: '侧面', answerText: '答案：侧面\n\n每个槽可以进一步划分为多个侧面。'},
    {id: 128, type: 'fill', question: '对于谓词公式P，如果至少存在一个解释使得P在此解释下的真值为T，则称P是____的。', options: [], answer: '可满足', answerText: '答案：可满足\n\n如果存在解释使公式为真，则称该公式是可满足的。'},
    {id: 129, type: 'fill', question: '在谓词公式中，位于量词之后的单个谓词或者用括弧括起来的谓词公式称为量词的 ____。', options: [], answer: '辖域', answerText: '答案：辖域\n\n量词的辖域是其作用范围内的公式。'},
    {id: 130, type: 'fill', question: '不确定性推理主要有两种不确定性，即关于____的不确定性和关于____的不确定性。', options: [], answer: '知识;证据', answerText: '答案：知识；证据\n\n不确定性推理涉及知识和证据两方面的不确定性。'},
    {id: 131, type: 'fill', question: '已知IF 阴天 THEN 下雨 0.7,CF(阴天)=0.5,则:CF(下雨) =____。', options: [], answer: '0.35', answerText: '答案：0.35\n\nCF(下雨) = CF(阴天) × CF(下雨, 阴天) = 0.5 × 0.7 = 0.35'},
    {id: 132, type: 'fill', question: '已知 R1: A1->B1, CF(B1, A1)=0.8,  CF(A1)=1，则CF(B1) =____。', options: [], answer: '0.8', answerText: '答案：0.8\n\nCF(B1) = CF(A1) × CF(B1, A1) = 1 × 0.8 = 0.8'},
    {id: 133, type: 'fill', question: '已知CF(阴天)=0.7,CF(湿度大)=0.5,则CF(阴天and湿度大)= ____,CF(阴天or湿度大)= ____,CF(not阴天)=____', options: [], answer: '0.5;0.7;-0.7', answerText: '答案：0.5；0.7；-0.7\n\nCF(A and B) = min{CF(A), CF(B)} = 0.5\nCF(A or B) = max{CF(A), CF(B)} = 0.7\nCF(not A) = -CF(A) = -0.7'},
    {id: 134, type: 'fill', question: '若已知规则为 :IF   E   THEN   H   ( CF( H , E ) )，当证据E的可信度 CF(E)<0 时，结论H的可信度 CF ( H ) 为____。当证据E的可信度 CF(E)=____时，结论H的可信度 CF ( H ) 为CF( H , E )。', options: [], answer: '0;1', answerText: '答案：0；1\n\n当CF(E)<0时，CF(H)=0；当CF(E)=1时，CF(H)=CF(H,E)。'},
    {id: 135, type: 'fill', question: '在诸如走迷宫、下棋、八数码游戏等游戏中，常用到的一种人工智能的核心技术称为图搜索技术，解这类问题时，常把在迷宫的位置、棋的布局、八数码所排成的形势用图来表，这种图称为_______。', options: [], answer: '状态空间图', answerText: '答案：状态空间图\n\n状态空间图用来表示问题的所有可能状态及其转移。'},
    {id: 136, type: 'fill', question: '状态空间可以用一个四元组表示:( S, O, S 0 , G ) ,其中S是____，O是____的集合，S0是问题的____，G是____的集合。', options: [], answer: '状态集合;操作算子;初始状态;目标状态', answerText: '答案：状态集合；操作算子；初始状态；目标状态\n\n这四个元素构成了状态空间的完整定义。'},
    {id: 137, type: 'fill', question: '盲目搜索包括____搜索和____搜索两种搜索方法。', options: [], answer: '深度优先;宽度优先', answerText: '答案：深度优先；宽度优先\n\n盲目搜索的两种主要方法是深度优先搜索和宽度优先搜索。'},
    {id: 138, type: 'fill', question: '启发式搜索是在搜索中加入了与问题有关的____, 减少搜索范围。', options: [], answer: '启发性信息', answerText: '答案：启发性信息\n\n启发式搜索利用启发性信息来指导搜索。'},
    {id: 139, type: 'fill', question: '遗传算法通过对生物遗传和进化过程中选择 、____、____机理的模仿来完成对问题最优解的自适应搜索过程。', options: [], answer: '交叉;变异', answerText: '答案：交叉；变异\n\n遗传算法的三个主要操作是选择、交叉和变异。'},
    {id: 140, type: 'fill', question: '在遗传算法中，____操作是从当前群体中按照一定概率选出优良的个体，使它们有机会作为父代繁殖下一代子孙。', options: [], answer: '选择', answerText: '答案：选择\n\n选择操作实现了"适者生存"的原则。'},
    {id: 141, type: 'fill', question: '在遗传算法中，____是用来区分群体中个体好坏的标准，是进行自然选择的唯一依据。', options: [], answer: '适应度函数', answerText: '答案：适应度函数\n\n适应度函数评估每个个体的优劣。'},
    {id: 142, type: 'fill', question: '在遗传算法中，____将个体编码的一些位进行随机变化，其主要目的是维持群体的多样性。', options: [], answer: '变异', answerText: '答案：变异\n\n变异操作维持种群的多样性，避免早熟收敛。'},
    {id: 143, type: 'fill', question: '遗传算法的五个基本要素:参数____、初始群体的设定、____的设计、遗传操作设计和控制参数设定。', options: [], answer: '编码;适应度函数', answerText: '答案：编码；适应度函数\n\n这五个要素是遗传算法的核心。'},
    {id: 144, type: 'fill', question: '粒子群优化算法中,粒子本身所找到的最优解称为____,  整个种群目前找到的最优解称为____。', options: [], answer: '个体极值;全局极值', answerText: '答案：个体极值；全局极值\n\n这两个概念是粒子群算法的基础。'},
    {id: 145, type: 'fill', question: '专家系统以____和____为核心,处理非确定性的问题,利用知识得到一个满意解是系统的求解目标。', options: [], answer: '知识库;推理机', answerText: '答案：知识库；推理机\n\n知识库和推理机是专家系统的两个核心部分。'},
    {id: 146, type: 'fill', question: '专家系统一般由知识库、知识获取机构、____、推理机、____和人机接口组成。', options: [], answer: '数据库;解释器', answerText: '答案：数据库；解释器\n\n这些是专家系统的主要组成部分。'},
    {id: 147, type: 'fill', question: '专家系统中从已知条件出发向目标进行推理,这种推理方式是____。', options: [], answer: '正向推理', answerText: '答案：正向推理\n\n正向推理从已知事实推导目标。'},
    {id: 148, type: 'fill', question: '专家系统在推理过程中,先假设求解目标成立,查看是否有某条规则支持该假设,即规则的结论与假设是否一致,然后看结论与假设一致的规则其前提是否成立,这种推理方式是____。', options: [], answer: '逆向推理', answerText: '答案：逆向推理\n\n逆向推理从目标假设反向推导。'},
    {id: 149, type: 'fill', question: '在机器学习中，____就是在已知输入和输出的情况下训练出一个模型，将输入映射到输出。', options: [], answer: '监督学习', answerText: '答案：监督学习\n\n监督学习需要带标签的训练数据。'},
    {id: 150, type: 'fill', question: '支持向量机的目标就是找到具有"____"的划分超平面。', options: [], answer: '最大间隔', answerText: '答案：最大间隔\n\nSVM的核心思想是最大化分类间隔。'},
    {id: 151, type: 'fill', question: '通过充分地利用少量的有标记数据和大量的无标记数据来改善算法性能的机器学习方法称为____学习。', options: [], answer: '半监督', answerText: '答案：半监督\n\n半监督学习结合了有标签和无标签数据。'},
    {id: 152, type: 'fill', question: '神经元模型一般由三部分组成 : ____、线性动态系统和非线性函数映射。', options: [], answer: '加权求和', answerText: '答案：加权求和\n\n神经元的三个主要部分是加权求和、线性系统和激活函数。'},
    {id: 153, type: 'fill', question: '根据神经网络中神经元的连接方式,可划分为不同类型的结构。目前,人工神经网络主要有____型和____型两大类神经网络。', options: [], answer: '前馈;反馈', answerText: '答案：前馈；反馈\n\n前馈网络和反馈网络是两种基本的神经网络结构。'},
    {id: 154, type: 'fill', question: '神经网络的学习是指调整神经网络的____或者____, 使输入和输出具有需要的特性。', options: [], answer: '连接权值;结构', answerText: '答案：连接权值；结构\n\n神经网络学习通过调整权值或结构来改进性能。'},
    {id: 155, type: 'fill', question: 'BP学习算法通过____过程使误差最小, 即选择神经网络权值使期望输出与神经网络实际输出之差的平方和最小。', options: [], answer: '反向学习', answerText: '答案：反向学习\n\nBP算法通过反向传播调整权值。'},
    {id: 156, type: 'fill', question: '卷积神经网络中，通过卷积获得特征之后，如果直接利用这些特征训练分类器，计算量是非常大的，所以需要对不同位置的特征进行聚合统计，这种聚合操作就叫作____。', options: [], answer: '池化', answerText: '答案：池化\n\n池化是对特征进行下采样和聚合的操作。'},
    {id: 157, type: 'fill', question: '一个卷积神经网络(CNN)的结构通常包括输入层、____、____和 全连接层(传统神经网络层)。', options: [], answer: '卷积层;池化层', answerText: '答案：卷积层；池化层\n\nCNN的基本结构包括这四个主要部分。'},
    {id: 158, type: 'fill', question: '卷积神经网络的4个关键技术是____、____、多卷积核以及池化。', options: [], answer: '局部连接;权值共享', answerText: '答案：局部连接；权值共享\n\nCNN的四个关键技术共同实现了高效的特征提取。'},
    {id: 159, type: 'fill', question: '常用的浅层视觉模型处理流程包括: 图像预处理 、____、____、 分类器/回归器 。', options: [], answer: '特征设计与提取;特征汇聚或变换', answerText: '答案：特征设计与提取；特征汇聚或变换\n\n这是浅层视觉模型的标准处理流程。'},
    {id: 160, type: 'fill', question: '一套典型的人脸识别系统包括6个步骤:人脸检测、特征点____、面部子图预处理、____、特征对比和决策。', options: [], answer: '定位;特征提取', answerText: '答案：定位；特征提取\n\n这六个步骤构成了完整的人脸识别流程。'},
    {id: 161, type: 'fill', question: '____模型是将图像可以看作文档，而图像中的局部视觉特征可以看作视觉单词的实例，从而可以直接应用这种方法实现大规模图像检索等任务。', options: [], answer: '视觉词袋', answerText: '答案：视觉词袋\n\n视觉词袋模型是计算机视觉中的重要方法。'},
    {id: 162, type: 'judge', question: '一般认为人类智能是知识与智力的总和，其中知识是一切智能行为的基础，而智力是获取知识并应用知识求解问题的能力。', options: [], answer: '正确', answerText: '正确\n\n这是对人类智能的准确描述。'},
    {id: 163, type: 'judge', question: '电子计算机的诞生为人工智能的研究奠定了物质基础。', options: [], answer: '正确', answerText: '正确\n\n计算机是AI研究的物质基础。'},
    {id: 164, type: 'judge', question: '产生式系统求解问题的过程是一个反复进行"匹配-冲突消解-执行"的过程。', options: [], answer: '正确', answerText: '正确\n\n这是产生式系统的工作原理。'},
    {id: 165, type: 'judge', question: '产生式适合于表达具有因果关系的过程性知识，既可以表示确定性知识，又可以表示不确定性知识。', options: [], answer: '正确', answerText: '正确\n\n产生式是表示过程性知识的有效方法。'},
    {id: 166, type: 'judge', question: '产生式表示法的不足在于它不能表达结构性知识。', options: [], answer: '正确', answerText: '正确\n\n框架表示法更适合表达结构性知识。'},
    {id: 167, type: 'judge', question: '产生式有固定的格式，每一条产生式规则都由前提与结论(操作)两部分组成。', options: [], answer: '正确', answerText: '正确\n\n产生式的标准格式是 IF 前提 THEN 结论。'},
    {id: 168, type: 'judge', question: '产生式是蕴含式。', options: [], answer: '错误', answerText: '错误\n\n产生式是规则，而不是逻辑蕴含式。'},
    {id: 169, type: 'judge', question: '产生式系统的正向推理是从已知事实和结论出发，通过规则判别已知事实与结论是否匹配。', options: [], answer: '错误', answerText: '错误\n\n正向推理是从已知事实出发推导结论。'},
    {id: 170, type: 'judge', question: '—阶谓词逻辑表示法可以表示不确定的知识。', options: [], answer: '错误', answerText: '错误\n\n一阶谓词逻辑只能表示确定性知识。'},
    {id: 171, type: 'judge', question: '产生式系统求解问题是不断地从规则库中选择可用规则与综合数据库中的已知事实进行匹配的过程，规则的每一次成功匹配都不会使综合数据库增加新内容。', options: [], answer: '错误', answerText: '错误\n\n每次成功匹配都会向数据库添加新的事实。'},
    {id: 172, type: 'judge', question: '若p为假、q为假，则蕴含式 p → q 为假。', options: [], answer: '错误', answerText: '错误\n\n当p为假时，p→q总是真。'},
    {id: 173, type: 'judge', question: '若p为真、q为真，则蕴含式 p → q 为假。', options: [], answer: '错误', answerText: '错误\n\n当p为真、q为真时，p→q为真。'},
    {id: 174, type: 'judge', question: '若p为真、q为假，则蕴含式 p ∨ q 为假。', options: [], answer: '错误', answerText: '错误\n\n当p为真时，p∨q为真。'},
    {id: 175, type: 'judge', question: '若p为假、q为真，则蕴含式 p ∧ q 为假。', options: [], answer: '正确', answerText: '正确\n\n当p为假时，p∧q为假。'},
    {id: 176, type: 'judge', question: '一个命题不能同时既为真又为假，但可以在一种条件下为真，在另一种条件为假。', options: [], answer: '正确', answerText: '正确\n\n这是命题的基本性质。'},
    {id: 177, type: 'judge', question: '命题逻辑可以把所描述的事物的结构及其逻辑特征反映出来，也能把不同事物间的共同特征表述出来。', options: [], answer: '错误', answerText: '错误\n\n谓词逻辑才能表达事物的结构和共同特征。'},
    {id: 178, type: 'judge', question: '框架的槽值或侧面值不能是另—个框架的名字。', options: [], answer: '错误', answerText: '错误\n\n槽值可以是另一个框架的名字，实现框架的嵌套。'},
    {id: 179, type: 'judge', question: '给命题公式中各个命题变元的一次真值指派称为命题公式的一个解释。对于每一个解释，谓词公式都可求出一个真值。', options: [], answer: '正确', answerText: '正确\n\n这是解释和真值的定义。'},
    {id: 180, type: 'judge', question: '任何文字的合取式称为子句。', options: [], answer: '错误', answerText: '错误\n\n任何文字的析取式称为子句。'},
    {id: 181, type: 'judge', question: '从初始证据出发，按某种策略不断运用知识库中的已知知识，逐步推出结论的过程称为推理。', options: [], answer: '正确', answerText: '正确\n\n这是推理的定义。'},
    {id: 182, type: 'judge', question: '非单调推理是在推理过程中由于新知识的加入，不仅没有加强已推出的结论，反而要否定它，使推理退回到前面的某一步，重新开始。', options: [], answer: '正确', answerText: '正确\n\n这是非单调推理的特点。'},
    {id: 183, type: 'judge', question: '对于不同的知识及证据，其非确定性程度一般不同，需要不同数据表示其非确定性的程度。', options: [], answer: '正确', answerText: '正确\n\n这是不确定性推理的基础。'},
    {id: 184, type: 'judge', question: '研究搜索技术的一种目的是在问题的状态空间中尽可能有效地找到问题的解。', options: [], answer: '正确', answerText: '正确\n\n搜索技术的目标是有效地找到问题的解。'},
    {id: 185, type: 'judge', question: '搜索算法使用弱启发性信息，必定导致找不到最优。', options: [], answer: '错误', answerText: '错误\n\n弱启发性信息仍可能找到最优解，只是效率较低。'},
    {id: 186, type: 'judge', question: 'A搜索算法是寻找并设计一个与问题有关的h(n)及构造出f(n)=g(n)+h(n)，然后以f(n)的大小来排列待扩展状态的次序，每次选择f(n)值最小者进行扩展。', options: [], answer: '正确', answerText: '正确\n\n这是A算法的定义。'},
    {id: 187, type: 'judge', question: '在图搜索算法中，如果按估价函数f(n)=g(n)+ h(n)作为OPEN表中的节点排序的依据，则该算法就是A*算法。', options: [], answer: '错误', answerText: '错误\n\nA*算法还需要h(n)满足可采纳性条件。'},
    {id: 188, type: 'judge', question: '估价函数f(n)=g(n)+ h(n)表示的是从初始节点经n节点到达目标节点的路径的最小代价估计值。', options: [], answer: '正确', answerText: '正确\n\n这是估价函数的含义。'},
    {id: 189, type: 'judge', question: '如果启发函数h(n)满足h(n)>h*(n)，则满足该条件的A算法称为A*算法，一定可以得到一个耗散值最小的结果。', options: [], answer: '错误', answerText: '错误\n\nA*算法要求h(n)≤h*(n)，而不是h(n)>h*(n)。'},
    {id: 190, type: 'judge', question: '在A算法中，满足单调条件的h(n)必然满足A*算法的条件。', options: [], answer: '正确', answerText: '正确\n\n单调条件保证了可采纳性。'},
    {id: 191, type: 'judge', question: '群智能算法是指模仿人脑的一群神经元工作原理的算法。', options: [], answer: '错误', answerText: '错误\n\n群智能算法模仿动物群体行为，而不是神经元。'},
    {id: 192, type: 'judge', question: '遗传算法主要借用生物进化中"适者生存"的规律。', options: [], answer: '正确', answerText: '正确\n\n遗传算法的核心思想来自进化论。'},
    {id: 193, type: 'judge', question: '遗传算法的适应度函数是用来区分群体中的个体好坏的标准。', options: [], answer: '正确', answerText: '正确\n\n适应度函数评估个体的质量。'},
    {id: 194, type: 'judge', question: '遗传算法中起核心作用的是变异算子。', options: [], answer: '错误', answerText: '错误\n\n选择算子起核心作用，实现"适者生存"。'},
    {id: 195, type: 'judge', question: '遗传算法采用群体搜索策略，同时对搜索空间中的多个解进行评估，因此遗传算法具有较好的全局搜索性能。', options: [], answer: '正确', answerText: '正确\n\n群体搜索是遗传算法的优势。'},
    {id: 196, type: 'judge', question: '一些问题的求解可以转化为目标函数的极值问题，于是可以通过群智能算法求解目标函数的极值来获得问题的解答。', options: [], answer: '正确', answerText: '正确\n\n这是群智能算法的应用方式。'},
    {id: 197, type: 'judge', question: '遗传算法能够保证每次都得到全局最优解。', options: [], answer: '错误', answerText: '错误\n\n遗传算法是随机算法，不能保证全局最优。'},
    {id: 198, type: 'judge', question: '在遗传算法应用中，适应度函数的设计要结合问题本身的要求而定，但适应度函数和问题的目标函数没有关系。', options: [], answer: '错误', answerText: '错误\n\n适应度函数通常由目标函数变换而来。'},
    {id: 199, type: 'judge', question: '在遗传算法中，适应度大的个体被选择的概率大，但不是说一定能够被选上。', options: [], answer: '正确', answerText: '正确\n\n选择是概率性的，不是确定性的。'},
    {id: 200, type: 'judge', question: '遗传算法中，采用交叉方法应能够使父串的特征遗传给子串，子串应能够部分或者全部地继续父串的结构特征和有效基因。', options: [], answer: '正确', answerText: '正确\n\n交叉操作实现了遗传信息的传递。'},
];
