// 题目数据库 - 第一部分 (1-100题)
const questionsPart1 = [
    {id: 1, type: 'single', question: 'AI的英文缩写是(        )。', options: ['Automatic Intelligence', 'Artifical lntelligence', 'Automatice Information', 'Artifical lnformation'], answer: 'B', answerText: 'B\n\nAI 是 Artificial Intelligence（人工智能）的缩写。'},
    {id: 2, type: 'single', question: '(        )是全球无人机行业的领先企业，其客户遍布全球100多个国家。', options: ['科大讯飞公司', '商汤科技公司', '中科曙光公司', '大疆创新科技公司'], answer: 'D', answerText: 'D\n\n大疆创新科技公司是全球无人机行业的领先企业。'},
    {id: 3, type: 'single', question: '以下关于人工智能的表述中，不正确的有(        )。', options: ['人工智能机器就是外观为人形的装置', '人工智能就是要让机器的行为看起来就像是人所表现出的智能行为一样', '人工智能是知识和智力的总和', '人工智能是一门科学，是使机器做那些由人需要通过智能来做的事情'], answer: 'A', answerText: 'A\n\n人工智能机器不一定是人形的装置，这是对AI的误解。'},
    {id: 4, type: 'single', question: '(        )是一个思想实验，用于判断机器是否具有智能。', options: ['交叉验证', '白盒测试', '图灵测试', '黑盒测试'], answer: 'C', answerText: 'C\n\n图灵测试是由艾伦·图灵提出的思想实验，用于判断机器是否具有智能。'},
    {id: 5, type: 'single', question: '人工智能中通常把 (        ) 作为衡量机器智能的准则。', options: ['图灵机', '图灵测试', '中文屋思想实验', '人类智能'], answer: 'B', answerText: 'B\n\n图灵测试是衡量机器智能的准则。'},
    {id: 6, type: 'single', question: '人工智能的目的是让机器能够(        ) ，以实现某些脑力劳动的机械化。', options: ['具有完全的智能', '和人一样工作', '完全代替人的大脑', '模拟、延伸和扩展人的智能'], answer: 'D', answerText: 'D\n\n人工智能的目的是模拟、延伸和扩展人的智能。'},
    {id: 7, type: 'single', question: '以下四个人工智能的应用领域中，与其它三个不同的是(        )。', options: ['人脸识别', '语音识别', '医学影像分析', '图像识别与分类'], answer: 'B', answerText: 'B\n\n语音识别是音频处理，而其他三个都是图像处理领域。'},
    {id: 8, type: 'single', question: '经典概念理论中，命题是一个非真即假的陈述句，以下是命题的有(        ) 。', options: ['这句话是谎言。', '如果下雨，则我打伞。', '您去电影院吗?', '天气真好！。'], answer: 'B', answerText: 'B\n\n命题必须是陈述句，且非真即假。"如果下雨，则我打伞"是陈述句。'},
    {id: 9, type: 'single', question: '以下(        )是命题。', options: ['请别生气!', '期中测试卷难吗?', '今天下雨了。', '看花去!'], answer: 'C', answerText: 'C\n\n"今天下雨了"是陈述句，且非真即假，符合命题定义。'},
    {id: 10, type: 'single', question: '关于命题描述不正确的是(        )。', options: ['命题是一个非真即假的陈述句。', '命题逻辑只能分解到简单命题。', '原子命题指的是可以再分解的命题。', '在逻辑命题中，复合命题用简单命题和逻辑词进行符号化。'], answer: 'C', answerText: 'C\n\n原子命题（简单命题）是不能再分解的命题，而不是可以再分解的。'},
    {id: 11, type: 'single', question: '如下联结词中不属于逻辑联结词的是(        )。', options: ['等价联结词', '否定联结词', '并联联结词', '蕴涵联结词'], answer: 'C', answerText: 'C\n\n逻辑联结词包括：否定、合取、析取、蕴涵、等价。"并联联结词"不是标准的逻辑联结词。'},
    {id: 12, type: 'single', question: '命题"如果你努力学习，那么就可以得奖学金"。如果用p表示"你努力学习"，用 q表示"你可以得奖学金" ，则可以将命题可以符号化为(        )。', options: ['p∧q', '¬ p ∧ ¬ q', 'p ∨ q', 'p → q'], answer: 'D', answerText: 'D\n\n"如果...那么..."表示蕴涵关系，符号化为 p → q。'},
    {id: 13, type: 'single', question: '"李明打篮球或踢足球": 可以用谓词公式表示为(        )。', options: ['Plays (Liming, basketball) ∨ Plays (Liming, football)', 'Plays (Liming, basketball) ∧ Plays (Liming, football)', 'Plays (Liming, basketball) → Plays (Liming, football)', 'Plays (Liming, basketball) → ¬ Plays (Liming, football)'], answer: 'A', answerText: 'A\n\n"或"表示析取关系，用 ∨ 符号表示。'},
    {id: 14, type: 'single', question: '李明的父亲是教师，用谓词逻辑可以表示为Teacher (father (Liming) )这里father (Liming)是(        )。', options: ['常量', '变元', '函数', '一元谓词'], answer: 'C', answerText: 'C\n\nfather(Liming) 是一个函数，它接收一个参数并返回一个值。'},
    {id: 15, type: 'single', question: '下列(        )不是谓词公式。', options: ['P(x)', '¬ P(x)', 'P(x)↔Q(x)', 'P(x)+Q(x)→R(x)'], answer: 'D', answerText: 'D\n\nP(x)+Q(x)→R(x) 中的"+"不是逻辑联结词，因此不是谓词公式。'},
    {id: 16, type: 'single', question: '以下哪些不是知识的特性(        )。', options: ['相对正确性', '确定性', '可表示性', '可利用性'], answer: 'B', answerText: 'B\n\n知识的特性包括：相对正确性、不确定性、可表示性、可利用性。确定性不是知识的特性。'},
    {id: 17, type: 'single', question: '设IF P THEN Q 是一个产生式，其中P是(        )。', options: ['前提或条件', '结论或动作', '确定性度量', '不确定性度量'], answer: 'A', answerText: 'A\n\n产生式的格式是 IF 前提 THEN 结论，P 是前提或条件。'},
    {id: 18, type: 'single', question: '设IF P THEN Q (置信度) 是一个产生式，其中Q是(        )。', options: ['前提或条件', '结论或动作', '确定性度量', '不确定性度量'], answer: 'B', answerText: 'B\n\nQ 是结论或动作。'},
    {id: 19, type: 'single', question: '以下说法正确的是(        )。', options: ['不确定性推理与确定性推理有基本一致的结构，只不过前者包含不确定的环节', '不存在不确定性推理，否则推理毫无意义', '不确定性推理依赖于事实证据、推理策略,但不需要推理知识', '不确定推理的推理规则应当是确定的'], answer: 'A', answerText: 'A\n\n不确定性推理与确定性推理的结构基本一致，只是包含不确定的环节。'},
    {id: 20, type: 'single', question: '以下不是知识表示法的是(        )。', options: ['产生式表示法', '框架表示法', '计算机表示法', '状态空间表示法'], answer: 'C', answerText: 'C\n\n知识表示法包括：产生式、框架、状态空间、逻辑等。计算机表示法不是标准的知识表示法。'},
    {id: 21, type: 'single', question: '不适合用产生式表示法表示的知识是(        )。', options: ['具有经验性及不确定性的知识', '具有结构关系的知识', '可以表示为一系列相对独立的求解问题的操作', '具有静关系的过程性知识'], answer: 'B', answerText: 'B\n\n产生式不适合表示具有结构关系的知识，框架更适合。'},
    {id: 22, type: 'single', question: '用(Li，age，40)表示老李年龄是40岁，这是知识的(        )表示方法。', options: ['状态空间', '框架', '产生式', '选项都不对'], answer: 'C', answerText: 'C\n\n这种三元组表示法属于产生式表示法。'},
    {id: 23, type: 'single', question: '有如下的天气预报:"北京地区今天白天晴，最高气温12度，最低气温-2度" ,用框架表示这一知识时,"天气"这个槽的值应填入(        )。', options: ['晴', '今天白天', '-2度', '12度'], answer: 'A', answerText: 'A\n\n"天气"槽的值是"晴"。'},
    {id: 24, type: 'single', question: '框架表示法中，框架的构成不包括(        )。', options: ['长方形框的图形', '槽名', '槽值', '约束'], answer: 'A', answerText: 'A\n\n框架的构成包括：槽名、槽值、约束。长方形框的图形是表示方式，不是构成部分。'},
    {id: 25, type: 'single', question: '如下知识表示方法的叙述中正确的有(        )。', options: ['可以任意选用一种知识表示方法,不用考虑知识本身的特点', '产生式表示法和框架表示法可以互相替代使用', '状态空间表示法是一种结构化的知识表示法', '框架表示法是一种结构化的知识表示法'], answer: 'D', answerText: 'D\n\n框架表示法是一种结构化的知识表示法。'},
    {id: 26, type: 'single', question: '为了描述一则关于"地震"的消息，可以从中抽象出很多要素。比如:地震的地点、日期、震级、波速比、水氡含量、地形改变等等，并由这些要素关联构成对地震的整体认知，这种知识表示形式是(        )。', options: ['—阶谓词逻辑', '联想表示', '产生式表示', '框架表示'], answer: 'D', answerText: 'D\n\n这是典型的框架表示法，通过多个槽来描述对象的各个方面。'},
    {id: 27, type: 'single', question: 'IF A THEN B   CF(B, A) 表示当前提A为真时，结论B为真的(        )。', options: ['可信度', '信度', '信任增长度', '概率'], answer: 'A', answerText: 'A\n\nCF(B, A) 表示可信度因子，即结论B相对于前提A的可信度。'},
    {id: 28, type: 'single', question: '不确定推理过程的不确定性不包括(        )。', options: ['证据的不确定性', '规则的不确定性', '推理过程的不确定性', '知识表示方法的不确定性'], answer: 'D', answerText: 'D\n\n不确定推理过程的不确定性包括：证据、规则、推理过程的不确定性。知识表示方法的不确定性不属于推理过程的不确定性。'},
    {id: 29, type: 'single', question: '在可信度方法中，若证据A的可信度CF (F)=0, 这意味: (        )。', options: ['对证据A一无所知', '没有意义', '证据A可信', '证据A不可信'], answer: 'A', answerText: 'A\n\nCF(F)=0 表示对证据的可信度一无所知，既不支持也不反对。'},
    {id: 30, type: 'single', question: '以下哪个可信度最接近"假"  (        )。', options: ['-0.1', '0.001', '0', '1'], answer: 'A', answerText: 'A\n\n可信度范围是 [-1, 1]，-0.1 最接近"假"（-1）。'},
    {id: 31, type: 'single', question: '如果证据E的出现使得结论H一定程度为真，则可信度因子(        )。', options: ['CH(H, E)=0', 'CH(H, E)=1', '0<CH(H, E)<1', '-1<CH(H,E）<0'], answer: 'C', answerText: 'C\n\n证据支持结论为真时，可信度因子在 0 到 1 之间。'},
    {id: 32, type: 'single', question: '以下推理不正确的是(        )。', options: ['如果下雨，则地上是湿的; 没有下雨，所以地上不湿。', '如果x是金属，则x能导电; 铜是金属，所以铜能导电。', '如果下雨，则地下就湿; 地上不湿，所以没有下雨。', '小贝喜欢可爱的东西; 哈士奇可爱; 所以小贝喜欢哈士奇。'], answer: 'A', answerText: 'A\n\n这是否定前件谬误。从"如果P则Q"和"非P"不能推出"非Q"。'},
    {id: 33, type: 'single', question: '所谓不确定性推理就是从 (        ) 的初始证据出发，通过运用 (        ) 的知识，最终推出具有一定程度的不确定性但却是合理或者近乎合理的结论的思维过程。', options: ['不确定性， 不确定性', '确定性， 确定性', '确定性， 不确定性', '不确定性， 确定性'], answer: 'A', answerText: 'A\n\n不确定性推理从不确定的证据出发，使用不确定的知识进行推理。'},
    {id: 34, type: 'single', question: '下列计算可信度规则正确的是 (        ) 。', options: ['CF(A and B) = max{CF(A),CF(B)}', 'CF(A or B) = max{CF(A), CF(B)}', 'CF(not A) = CF(A)', 'CF(A or B) = CF(A)-CF(B)'], answer: 'B', answerText: 'B\n\nCF(A or B) = max{CF(A), CF(B)} 是正确的可信度计算规则。'},
    {id: 35, type: 'single', question: '关于可信度方法，下列说法不正确的是 (        ) 。', options: ['CF(H，E)的取值范围: [0,1]。', '若由于相应证据的出现增加结论 H 为真的可信度，则 CF(H，E)> 0，证据的出现越是支持 H 为真，就使CF(H，E) 的值越大。', 'CF(H，E)< 0，证据的出现越是支持 H 为假，CF(H，E)的值就越小。', '若证据的出现与否与 H 无关，则 CF(H，E）=0'], answer: 'A', answerText: 'A\n\nCF(H，E)的取值范围是 [-1, 1]，而不是 [0, 1]。'},
    {id: 36, type: 'single', question: '状态空间通常用四元组(S，O，S0，G)表示，这里的S是(        )。', options: ['状态集合', '目标状态', '状态操作', '初始状态'], answer: 'A', answerText: 'A\n\nS 表示状态集合，O 表示操作算子集，S0 表示初始状态，G 表示目标状态集合。'},
    {id: 37, type: 'single', question: '状态空间表示法不包括(        )，它通过对状态空间的搜索，实现对问题的求解。', options: ['操作算子集', '规则库', '问题的初始状态', '状态集合'], answer: 'B', answerText: 'B\n\n状态空间表示法包括：状态集合、操作算子集、初始状态、目标状态。规则库不是状态空间的组成部分。'},
    {id: 38, type: 'single', question: '在图的盲目搜索中，在扩展当前搜索到的节点时，首先考虑其子节点而非兄弟节点的搜索策略属于(        )优先搜索。', options: ['密度', '深度', '随机', '宽度'], answer: 'B', answerText: 'B\n\n深度优先搜索优先扩展子节点，而宽度优先搜索优先扩展兄弟节点。'},
    {id: 39, type: 'single', question: '盲目搜索的搜索策略包括(        )优先搜索。', options: ['重要度', '深度和宽度', '均匀', '随机'], answer: 'B', answerText: 'B\n\n盲目搜索包括深度优先搜索和宽度优先搜索。'},
    {id: 40, type: 'single', question: '从初始节点S0开始逐层向下扩展，在全部搜索完第k层节点之后，才进入第k+1层节点进行搜索。这种搜索策略属于(        )优先搜索。', options: ['宽度', '随机', '深度', '均匀'], answer: 'A', answerText: 'A\n\n这是宽度优先搜索（广度优先搜索）的定义。'},
    {id: 41, type: 'single', question: '如果问题存在最优解，则下面几种搜索算法中，(        )必然可以得到该最优解。', options: ['宽度优先搜索', '深度优先搜索', '有界深度优先搜索', '启发式搜索'], answer: 'A', answerText: 'A\n\n宽度优先搜索能保证找到最优解。'},
    {id: 42, type: 'single', question: '如果问题存在最优解，则下面几种搜索算法中，(        )可以认为是"智能程度相对比较高"的算法。', options: ['宽度优先搜索', '盲目搜索', '启发式搜索', '深度优先搜索'], answer: 'C', answerText: 'C\n\n启发式搜索利用启发信息，智能程度更高。'},
    {id: 43, type: 'single', question: '启发式搜索可以利用的启发性信息不包括(        )关的信息。', options: ['与具体问题求解过程', '指导搜索过程', '搜索算法的优劣', '最有希望的搜索方向'], answer: 'C', answerText: 'C\n\n启发性信息与问题求解过程有关，用于指导搜索，但不是搜索算法的优劣。'},
    {id: 44, type: 'single', question: '启发式搜索算法包括(        )。', options: ['随机搜索算法', '宽度搜索算法', 'A算法', '深度搜索算法'], answer: 'C', answerText: 'C\n\nA算法是启发式搜索算法。'},
    {id: 45, type: 'single', question: '下列算法中，属于启发式搜索算法的是(        )。', options: ['A*算法', '深度优先搜索算法', '盲目搜索算法', '宽度优先搜索算法'], answer: 'A', answerText: 'A\n\nA*算法是启发式搜索算法。'},
    {id: 46, type: 'single', question: '在启发式搜索算法中，通过(        )引入启发知识，以评估当前的搜索状态并找出一个最有希望的节点进行扩展。', options: ['Close表', 'Open表', '评价函数', '单调函数'], answer: 'C', answerText: 'C\n\n评价函数用于评估搜索状态，引入启发知识。'},
    {id: 47, type: 'single', question: '启发性信息可以加快搜索进程，其作用强度会影响搜索结果，当强度为(        )时，好处是大幅减少了搜索范围，但可能导致找不到最优解。', options: ['弱', '0', '负', '强'], answer: 'D', answerText: 'D\n\n启发性信息强度过强时，可能导致找不到最优解。'},
    {id: 48, type: 'single', question: '博弈搜索方法擅长于求解(        )问题。', options: ['涉及双方博弈', '数学定理证明', '复杂度计算', '逻辑推理'], answer: 'A', answerText: 'A\n\n博弈搜索方法用于解决涉及双方对抗的问题。'},
    {id: 49, type: 'single', question: '由群体行为所表现出的智能称为(        )。', options: ['脑智能', '符号智能', '计算智能', '群智能'], answer: 'D', answerText: 'D\n\n群体行为表现出的智能称为群智能。'},
    {id: 50, type: 'single', question: '以下属于群体智能优化算法的包括(        )。', options: ['模拟植物生长过程的生长算法', '模拟鸟群觅食过程的粒子群算法', '模拟一只鸟飞行过程的飞行算法', '模拟人脑神经元工作的人工神经元算法'], answer: 'B', answerText: 'B\n\n粒子群算法是群智能优化算法，模拟鸟群觅食行为。'},
];
